### ISSUE TITLE
🚧Research and see what it will take for generating documentation

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#100]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

This project item will deal with all of the research involved with generating documentation for Velaptor and other projects as well.

Once the research is done, use what was discovered to create other project items to get the work done.

Look Into:
- [ ] [DocFX](https://dotnet.github.io/docfx/)
    - This will automatically generate documentation that can be pushed to GitHub pages.  GitHub pages is what will be used for the documentation resource for users
- [ ] Look into what it will take to push the documentation changes to GitHub pages from a GitHub actions standpoint.  The idea is that every release will run a github action that will generate the documentation and then push it to GitHub pages
- [ ] Look into [Read The Docs](https://readthedocs.org/) which is a free service for hosting technical documentation for open source projects

Other:
[Six Labors Image Sharp](https://docs.sixlabors.com/) uses DocFX.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Research data is collected to help drive further direction when it comes to documentation
- [ ] Other project items created to do the work based on the research collected

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Groomed

**Comment by kselena** [comment]
Combined issue #22 into this card.
