### ISSUE TITLE
🚧Refactor moq code to nsubstitute

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#1006]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor the following test files from **_Moq_** code to **_NSubstitute_** code

1. TextureFactoryTests.cs
1. TextureTests.cs
1. GpuData TypeExtensionsTests.cs
1. NativelnputFactoryTests.cs
1. ImageLoaderTests.cs
1. RenderMediatorTests.cs
1. FontRendererTests.cs
1. LineRendererTests.cs
1. ShapeRendererTests.cs
1. TextureRendererTests.cs
1. SystemDisplayServiceTests.cs

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All the unit tests have been executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] The file _**TextureFactoryTests.cs**_ has been refactored
- [x] The file _**TextureTests.cs**_ has been refactored
- [x] The file _**GpuDataTypeExtensionsTests.cs**_ has been refactored
- [x] The file _**NativelnputFactoryTests.cs**_ has been refactored
- [x] The file _**ImageLoaderTests.cs**_ has been refactored
- [x] The file _**RenderMediatorTests.cs**_ has been refactored
- [x] The file _**FontRendererTests.cs**_ has been refactored
- [x] The file _**LineRendererTests.cs**_ has been refactored
- [x] The file _**ShapeRendererTests.cs**_ has been refactored
- [x] The file _**TextureRendererTests.cs**_ has been refactored
- [x] The file _**SystemDisplayServiceTests.cs**_ has been refactored
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking-changes`      |
| New Feature              | `✨new-feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by sbundaz** [comment]
I can take this one.
