### ISSUE TITLE
🚧Refactor moq code to nsubstitute

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#1007]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor the following test files from **_Moq_** code to **_NSubstitute_** code

1. SystemDisplayTests.cs
1. MoqExtensions.cs
1. FreeTypelnvokerTests.cs
1. GlfwDisplaysTests.cs
1. GpuBufferBaseTests.cs
1. TextureShaderResourceLoaderServiceTests.cs
1. FontShaderTests.cs
1. LineShaderTests.cs
1. ShapeShaderTests.cs
1. TextureShaderTests.cs
1. AppSettingsServiceTests.cs
1. EventLoggerServiceTests.cs

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All the unit tests have been executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] The file _**SystemDisplayTests.cs**_ has been refactored
- [x] The file _**FreeTypelnvokerTests.cs**_ has been refactored
- [x] The file _**GlfwDisplaysTests.cs**_ has been refactored
- [x] The file _**GpuBufferBaseTests.cs**_ has been refactored
- [x] The file _**TextureShaderResourceLoaderServiceTests.cs**_ has been refactored
- [x] The file _**FontShaderTests.cs**_ has been refactored
- [x] The file _**LineShaderTests.cs**_ has been refactored
- [x] The file _**ShapeShaderTests.cs**_ has been refactored
- [x] The file _**TextureShaderTests.cs**_ has been refactored
- [x] The file _**AppSettingsServiceTests.cs**_ has been refactored
- [x] The file _**EventLoggerServiceTests.cs**_ has been refactored
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking-changes`      |
| New Feature              | `✨new-feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
