### ISSUE TITLE
🚧Render text issue fixed

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#1009]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When rendering text while the window is a size of `1280 x 720` exactly, the text does not render until the window is resized.

Notes On Behavior:
1. Only changing the width by the value of 1 in either direction shows the text
2. Only changing the height by the value of 1 in either direction shows the text
3. After changing the width or height the first time, setting both values back to the original value does not make the text disappear again

Use the code below to get to a testing state quickly for debugging purposes:
[TestScene.txt](https://github.com/user-attachments/files/16643944/TestScene.txt)
[MainWindow.txt](https://github.com/user-attachments/files/16643954/MainWindow.txt)

> [!Note]
> The code files above are actually `.cs` files.  They were set to `.txt` due to GitHub's restriction of file types.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All the unit tests have been executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] Bug has been fixed
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking-changes`      |
| New Feature              | `✨new-feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
