### ISSUE TITLE
🚧Fix unloading cached items issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#1019]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When caching content, the relative part of the path uses forward slashes, while the rest of the resolved path up to the relative path section uses backslashes. This ends up with a cache key that uses both forward and backward slashes. This means that the incoming path (the cache key) to unload the cached content item does not match the actual cache key in the cache.

This results in the unloading of the cached content item to not be unloaded.

To resolve this issue, it's crucial that we ensure all pathing related to content loading, unloading, and caching uses the correct directory separator based on the current operating system.  This way, we can avoid the mix of separators that lead to incorrect cache keys in the content caching system.

**Where to observe the issue:**
This can be observed by trying to unload the audio content in the **VelaptorTesting** application in the audio scene.  When unloading the audio content while moving to different scenes, the audio content does not get unloaded due to the incoming `cacheKey` not matching the actual cache key in the cache.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All the unit tests have been executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] Cache key issue has been fixed
- [x] Audio content has been validated to correctly unload using the cache key
- [x] Texture content has been validated to correctly unload using the cache key
- [x] Atlas content has been validated to correctly unload using the cache key
- [x] Font content has been validated to correctly unload using the cache key
- [x] Resolver tests refactored to pass based on changes
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking-changes`      |
| New Feature              | `✨new-feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
