### ISSUE TITLE
🚧Add VAO, VBO, EBO, and Texture ID caching

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#102]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add caching for the VAO, VBO, EBO, and Texture ID values to improve performance and reduce unnecessary OpenGL function calls.

When the call stack just happens to be setup where the application is making the same consecutive GL bind calls over and over for the same ID, this becomes a small performance bottle neck.  To prevent this from occurring, the ID's for VAO(Vertex Array Objects), VBO(Vertex Buffer Objects), and EBO(Element Buffer Objects) can be cached.

The way to implement this is when a bind call is made, it will first check to see if the cache for that ID shows that it is currently bound.  If it is currently bound, it will NOT make an OpenGL call to bind the buffer.  It will simply move on.  If it is not currently bound, then the intent is that we want it bound.  It will then bind the current ID and then UNBIND all of the other ID values.  This is the important part.  Since OpenGL is a state machine, and there can only be a single bound buffer of that particular type bound in OpenGL at a time, we are trying to match that state to OpenGL.  This way we can keep track what is bound and what is not and then save unnecessary GL calls.

Setup this caching to occur in the `GLInvoker` class.

**TODO:**
- [ ] Create simple `private static` helper methods in `GLInvoker` for unbinding all ID values for each type of buffer ID
- [ ] Add a dictionary of `private static readonly Dictionary<uint, bool> IDList = new ();` for each buffer ID type that will hold the ID state of that particular buffer with its current state in OpenGL.  The dictionary key will be the ID and the value will represent if it is currently bound. 
    - The name of the lists should be:
        - `private static readonly Dictionary<uint, bool> BoundVAOList = new()`
        - `private static readonly Dictionary<uint, bool> BoundVBOList = new()`
        - `private static readonly Dictionary<uint, bool> BoundEBOList = new()`
        - `private static readonly Dictionary<uint, bool> BoundTextureList = new()`
- [ ] Setup the bind method calls to reflect state
    - [ ] In the `BindVertayArray()` method, check whether the ID is already bound.  If so, move on and if not, set all other ID values to false first before setting the ID bind state to true
        - [ ] Make sure to check if the incoming ID is set to 0.  If so then this means it needs to be unbound.  Reflect the state for this scenario.
    - [ ] In the `BindBuffer()` method, check whether the ID is already bound.  If so, move on and if not, set all other ID values to false first before setting the ID bind state to true
        - NOTE: This one method binds Element Array and Array Buffers.  Make sure to check for both kinds and update state accordingly
        - [ ] Make sure to check if the incoming ID is set to 0.  If so then this means it needs to be unbound.  Reflect the state for this scenario.
    - [ ] In the `BindVertayArray()` method, check whether the ID is already bound.  If so, move on and if not, set all other ID values to false first before setting the ID bind state to true
        - [ ] Make sure to check if the incoming ID is set to 0.  If so then this means it needs to be unbound.  Reflect the state for this scenario.
    - [ ] In the `BindTexture()` method, check whether the ID is already bound.  If so, move on and if not, set all other ID values to false first before setting the ID bind state to true
        - [ ] Make sure to check if the incoming ID is set to 0.  If so then this means it needs to be unbound.  Reflect the state for this scenario.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Groomed
