### ISSUE TITLE
🚧Add symbols and xml docs to nuget package

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#1036]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the debug symbols and the XML docs to the Nuget package to improve debugging and provide code docs in the intellisense of the development tools.

**Debugging Symbols:**
Refer to this [ms docs](https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg) URL to get info on how to add the debug symbols to the package.
This will require updating the **dotnet-lib-release.yml** workflow in **Infrastructure**. 

~For this issue, the following needs to be added to the csproj file.~
```xml
<PropertyGroup>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
</PropertyGroup>
```

**XML File**
The setup for this in the csproj file is not complete.  The property `GenerateDocumentationFile` is already added to the csproj and set to a value of `true`. The missing piece is the part to include the xml file in the Nuget package.

~Add this to the `<ItemGroup/>` with the rest of the Nuget additions~
```xml
    <None Include="bin\$(Configuration)\$(TargetFramework)\Velaptor.xml" Pack="true" PackagePath="\" />
```

> [!Warning]
> Make sure to validate that the XML file is being added to the package.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All the unit tests have been executed and passed locally after the PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [ ] Release workflow updated to create .snupkg and to push to nuget
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking-changes`      |
| New Feature              | `✨new-feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Research revealed that there was not need to do the following:
- For this issue, the following needs to be added to the csproj file.
- Add this to the `<ItemGroup/>` with the rest of the Nuget additions

**Comment by CalvinWilkinson** [comment]
Closed without changes.  The symbols and xml docs are added to the nuget package during the build process in Infrastructure
