### ISSUE TITLE
🚧Setup GL callstack feature to only work for Debug builds

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#104]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

The ability to keep track of the call stack of OpenGL calls has been added to the `GLInvoker` class.  Currently, this works for all builds available, but we only want it to run for **Debug** builds.  This will improve performance for **Release** builds.

Add logic in the `GLInvoker` class that checks the app settings to see if using the call stack feature is enabled for disabled. 
The `GLInvoker.AddToGLCallStack()` method will only contain code to queue stack information when in **Debug** mode.  This method will contain the logic to either use the queue stack or not.  The `AppSettingsService` will be injected into the `GLInvoker` class to check the app setting.

### Acceptance Criteria

**This issue is finished when:**
- [ ] The `GLInvoker` class is improved to use app settings for GL call stack collection

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Groomed
