### ISSUE TITLE
🚧Failing tests on MacOS

### ISSUE THREAD

**Issue by sbundaz** [KinsonDigital/Velaptor#1046]
### Complete The Item Below

- [x] I have updated the title without removing the 🚧 emoji.

### Description

Fix various tests that use Windows-type paths instead of cross-platform-type paths. These tests need to be passed on to any operating system.

> [!Note]
> The main code being tested should be built using cross-platform pathing.  If not, we should create a separate issue to address the problem.  The dotnet API includes pathing checking and processing for multiple operating systems, which under the hood will use the correct `\` or `/` characters by detecting the operating system the code is running on.  We want to avoid any code that manually changes the slashes from one to another to avoid GC collections and keep things performant.  Leveraging the built in dotnet API for this will achieve this desired behavior.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] The `ResolveFilePath_WhenInvoked_ResolvesFilePath` test in the **_AudioPathResolverTests.cs_** file has been fixed.
- [x] The `ResolveFilePath_WhenInvoked_ResolvesFilePath` test in the **_TexturePathResolverTests.cs_** file has been fixed.
- [x] The `ResolveFilePath_WhenInvoked_ResolvesFilePath` test in the **_AtlasJSONDataPathResolverTests.cs_** file has been fixed.
- [x] The `ResolveFilePath_WhenInvoked_ResolvesFilePath` test in the **_FontPathResolverTests.cs_** file has been fixed.
- [x] All the unit tests have been executed and passed locally after the PR work is complete. _(Why? Refer to 'Additional Information' below.)_
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking-changes`      |
| New Feature              | `✨new-feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.
