### ISSUE TITLE
🚧Add binding methods to GLExtensions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#105]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

In the `GLExtensions` class, create bind and unbind methods for each particular bind type to help simplify bind and unbind calls which will improve code readability.  These will be like the `private` helper methods in `GPUBufferBase` class.

Once created, delete the similar methods in the `GPUBufferBase` class and replace the calls with the new methods created in the 
`IGLInvokerExtensions` interface and `GLInvokerExtensions` class.

- [ ] `BindVAO()` method created in GL extensions types and removed from `GPUBufferBase` class
- [ ] `BindVBO()` method created in GL extensions types and removed from `GPUBufferBase` class
- [ ] `BindEBO()` method created in GL extensions types and removed from `GPUBufferBase` class
- [ ] 'BindTexture2D()` method created in GL extensions types and removed from `Texture` and `SpriteBatch` class

### Acceptance Criteria

**This issue is finished when:**
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass
