### ISSUE TITLE
🚧Handle premature EBO unbinding

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#108]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

When working with OpenGL, it is not ideal to unbind an EBO(Element Buffer Object) before unbinding the associated VAO(Vertex Array Object).  This is due to a possible OpenGL state which can lead to hard to find bugs and issues.  It is best practice, (not required) in OpenGL to unbind the VAO first before unbinding the EBO.

🛑STOP!! DO THIS FIRST🛑
- [x] Make sure that issue #105 has been implemented first

---

- [x] Add code in the `OpenGLService.UnbindEBO()` method to check and see if any VAO objects are currently bound and if so, unbind the VAO first before unbinding the EBO.

### Acceptance Criteria

**This issue is finished when:**
- [x] Code documentation added if required

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

### Issue Dependencies

- #105

**Comment by kselena** [comment]
Groomed
