### ISSUE TITLE
🚧Refactor all applicable structs to record structs

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#109]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Refactor the following structs to `readonly record` or `record` structs where applicable.  This can be a decent performance improvement by doing this.

This is going to cause refactoring in regards to assigning values to the fields/props of the struct.  The structs that are being converted to `readonly` structs and have `public` fields, will need to have the `public` fields converted to `init` properties.

When it comes to the XML docs, make sure that they are refactored if required.  An example of this is with the `FontAtlasMetrics`.  The current XML docs are for public fields, but they are not the standard XML docs for properties.  When converting these to properties, they will require them to be refactored for properties.

Example:
```diff
/// <summary>
- /// The number of rows in the atlas.
+ /// Gets the number of rows in the atlas.
/// </summary>
- public uint Rows;
+ public uint Rows { get; init; }
```

> **Note**
> Things to consider when refactoring:
> 1. The `init` property still gives the ability to set an initial value when creating a new instance of the struct, but still maintains the ability to follow the rules of what makes a struct `readonly`.
> 2. `record`'s provides built-in version of certain things such as overrides like `GetHashCode()`, `Equals()`, and anything provided `IEquatable<T>`.
> 3. Overloaded operators should be removed.

**Structs To Refactor:**
- `FontAtlasMetrics`
    > **Warning**
    > This will require refactoring in an area that is sensitive to the process of creating font atlas textures.

> **Warning**
> This might require some refactoring of some of the OpenGL invoker calls to make this work.

- [x] #97 Complete
- [ ] Records refactored

### Acceptance Criteria

**This issue is finished when:**
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Issue Dependencies

- #97

**Comment by kselena** [comment]
Groomed

**Comment by CalvinWilkinson** [comment]
Closed issue without implementation:

**Reason:**
The issue was split up into more issues to reduce risk as well as reducing the amount to review and test during review.

**Issues Produced:**
- #801 
- #802 
- #803 
- #804 
- #805
- #806
- #807
