### ISSUE TITLE
🚧Look into setup and use of CodeFactor

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#111]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Look into using code factor for automated code review stuff.

**Resources:**
- [Code Factor](https://www.codefactor.io/)
- [GitHub Action](https://github.com/marketplace/codefactor)

### Acceptance Criteria

**This issue is finished when:**
- [x]  Subject researched
- [x] ~~Cards created to implement the result of the research~~
  - Not implemented.  This is because the PR process I think is partially managed by codefactor and a feature of codefactor.

### Research Results

1. It was discovered that codefactor is free for public repos for unlimited repos and unlimited users
2. Connection of codefactor to github organization was easy.
  - The personal repo access needed no intervention
  - Organizational level repos had to be manually granted in the org settings.

### ToDo Items

- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
