### ISSUE TITLE
🚧Improve GL ErrorCallback

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#112]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

In the `GLInvoker` class, the `SetupErrorCallback()` method sets up the **Debug Message Callback** mechanism for OpenGL.  This currently does this for all build configurations.

The changes should be that with _**Debug**_ builds, the default setting will be enabled for the callback to be setup, and for _**Release**_ builds, the default setting will be disabled.  This is mostly for performance reasons.

### Acceptance Criteria

- [ ] Add a preprocessor directive to only setup the callback if in **Debug** mode.
- [ ] Setup error callback to be enabled and disabled using an app setting
    - [ ] In debug builds, default app setting will be enabled
    - [ ] In release builds, default app setting will be disabled
- [ ] Add comments when NOT in **Debug** mode that explains that this is only used in **Debug** mode.
    - [ ] Add the original code that does execute in **Debug** mode to the comments for **Release** mode, but have it commented out.  This will allow people to see what the code would be with an explanation if they decompile the library.

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Reviewed
