### ISSUE TITLE
🚧Figure out how to post announcements in discord

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#114]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Figure out how to automatically post updates in the announcement channel in discord server

### Acceptance Criteria

Research results documented in this card.

- [ ] Issues created to implement discord integration

### ToDo Items

- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Closed.

**Reason:** This has already been figured out and is done using discord web hook
