### ISSUE TITLE
🚧Perform action updates in all workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#116]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Go through all of the workflows and check the used actions for version updates and update to the latest.
Also go through each workflow and update them to use the new and also already existing improved GitHub actions.

💡NOTE 1💡
The purpose of this is only to improve the workflows in the context of the GitHub actions they use.  This means updating the action versions, refactoring how the action is used based on which version it has been updated to, and removal of jobs or steps that a new GitHub action will take care of.  For example, removing of PowerShell steps/jobs that a GitHub action can now handle.

💡NOTE 2💡
Since all of the github actions will be getting converted to .NET code bases, we have to move to using **Ubuntu** runners instead of **Windows**.  The reason is because .NET actions have to run in docker and currently docker only runs in linux runners.  The thing we have to take into account is **PowerShell**.  Powershell 7+ can run on windows or linux but the YAML has to be a little bit different for this to work.  I am pretty sure that using **PowerShell Core** will work on both runners but you just have to be explicit on what shell you are using.  Refer to [this](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-running-a-script-using-powershell-core) for more info.

**Powershell On Ubuntu Example:**
``` yaml
steps:
  - name: Display the path
    run: echo ${env:PATH}
    shell: pwsh # This is the line that is required
```

### Acceptance Criteria

**This issue is finished when:**
- [x] ~Code documentation added if required~
- [x] ~Unit tests added~
- [x] ~All unit tests pass~
- [ ] Go through each workflow below and update to use new GitHub actions or update already existing
  - [ ] Update uses of _**vget**_ GitHub action
  - [ ] Update use of **_TagVerifier_** GitHub action in _**tag-does-not-exist-status-check.yml**_ workflow
  - [ ] Update uses of _**NugetExistsChecker**_ GitHub action.
    - This used to be named _**NugetVersionChecker**_
  - [ ] Update the **Validate Branch Name** job to use the new _**BranchValidator**_ GitHub action
- [ ]  Look for various ways to use the new _**IssueChecker**_ GitHub action

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Issue Dependencies

1. KinsonDigital/IssueChecker#2
2. KinsonDigital/vget#14
3. KinsonDigital/NugetExistsChecker#4
5. KinsonDigital/BranchValidator#1
6. KinsonDigital/GitHubReleaseChecker#1

### Related Work

- KinsonDigital/issues-repo#9
- #287 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kselena** [comment]
Groomed

**Comment by CalvinWilkinson** [comment]
Closed without changes.

**Reason:** This is no longer required. The reason is that the way that workflows work has been changed.  Instead of using large YAML workflows, [Nuke](https://nuke.build/) is being implemented instead for various reasons for a build system.

The issue created for implementing a new build system is:
- #342
