### ISSUE TITLE
🚧Setup release workflows to include release notes

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#117]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

For the workflow releases below, setup the workflows to attach the release notes as part of the assets that are getting released. Also look into using the content of a file to be used as the body of the release.

- [ ] Update the **_qa-prod-releases.yml_** workflow to attach and display the release notes
- [ ] Update the **_preview-release.yml_** workflow to attach and display the release notes

### Acceptance Criteria

**This issue is finished when:**
~- ☑️ Code documentation added if required~
~- ☑️ Unit tests added~
~- ☑️ All unit tests pass~

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
This work was already done in previous release
