### ISSUE TITLE
🚧Add the Documentation folder to solution explorer

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#118]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add the Documentation folder and required sub folders as a virtual solution folders to the **SolutionItems** folder in the solution explorer so it can be viewed in **Visual Studio** and **JetBrains Rider**

### Acceptance Criteria

**This issue is finished when:**
~☑️Code documentation added if required~
~☑️Unit tests added~
~☑️All unit tests pass~

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
