### ISSUE TITLE
🚧Fix simple issue with Twitter broadcast for workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#119]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Remove single quotes in the _**Send Tweet About Release**_ step in the _**preview-release.yml**_ workflow. 
Refer to image below.

- [ ] _**preview-release.yml**_ workflow updated
- [ ] _**qa-prod-releases.yml**_ workflow updated

---

![image](https://user-images.githubusercontent.com/85414302/147710304-a4ef0da8-b975-4168-b2db-81beddabd3ef.png)

### Acceptance Criteria

**This issue is finished when:**
~☑️Code documentation added if required~
~☑️Unit tests added~
~☑️All unit tests pass~

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
