### ISSUE TITLE
🚧Grammar changes to codebase documentation

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#121]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Fixing grammar/spelling issues in the codebase documentation. 

### Acceptance Criteria

**This issue is finished when:**
- [x] Code documentation added if required
~☑️ Unit tests added~
~☑️ All unit tests pass~

### ToDo Items

- [X] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone
~☑️ Unit tests have been written and/or adjusted for code additions or changes~
~☑️ All unit tests pass~

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
