### ISSUE TITLE
🚧Normalize XML code docs for constructor params across code base

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#122]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Make all XML code documentation consistent for constructor parameters across the entire code base the same for documentation consistency.

The best way to find constructors with the params for a single interface to update is to do a solution wide search for the param interface type and name.

Example: Searching for **_IGLInvoker gl_** for the most part should find all constructors where the parameter type and name match the search string.

To get a list of all interfaces and their names, search for **_interface_**.  These are the types that are getting used as constructor parameters all over the code base that need to have the associated XML code doc normalized.

---

- [x] IScene.cs
- [x] IInvalidContent.cs
- [x] IUnknownContentItem.cs
- [x] IFontStatsService.cs
- [x] IAtlasData.cs
- [x] IContent.cs
- [x] IContentLoadable.cs
- [x] IContentLoader.cs
- [x] IContentUnloadable.cs
- [x] IDisposableItemCache.cs
- [x] IFont.cs
- [x] IItemCache.cs
- [x] ILoader.cs
- [x] IPathResolver.cs
    - This is very contextual depending on how it is used.  There is system font, texture, content font, atlas JSON data and more resolvers.  Depending on how it is used will depend on its description.
- [x] ISound.cs
- [x] ITexture.cs
- [x] ISoundFactory.cs
- [x] IAtlasDataFactory.cs
- [x] ITextureFactory.cs
- [x] ISpriteBatch.cs
- [x] IGameInput.cs
- [x] IKeyboardInput.cs
- [x] IMouseInput.cs
- [x] IFreeTypeExtensions.cs
- [x] IFreeTypeInvoker.cs
- [x] IGLFWInvoker.cs
- [x] IGLInvoker.cs
- [x] IGLInvokerExtensions.cs
- [x] IShaderLoaderService.cs
- [x] ITemplateProcessorService.cs
- [x] IGPUBuffer.cs
- [x] IGameWindowFacade.cs
- [x] IShaderProgram.cs
- [x] IBatchManagerService.cs
- [x] IEmbeddedResourceLoaderService.cs
- [x] IFontAtlasService.cs
- [x] IImageService.cs
- [x] ISystemMonitorService.cs
- [x] IControl.cs
- [x] ISizable.cs
- [x] IWindow.cs
- [x] IWindowActions.cs
- [x] IWindowProps.cs

### Acceptance Criteria

**This issue is finished when:**
- [x] Code documentation added if required
~- ☑️ Unit tests added~
~- ☑️ All unit tests pass~

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
~- ☑️ Unit tests have been written and/or adjusted for code additions or changes~
~- ☑️ All unit tests pass~

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
@kselena Quick FYI.  We still need to go through each of these and figure out what we want each one to say.  We can add that to the card for each checkbox item as well for reference.  This is why I have the 
<img width="58" alt="image" src="https://user-images.githubusercontent.com/85414302/148208588-d3a3f9b8-6a2e-4810-b391-6642cad90c36.png"> label added to the card.  Still need to groom it.
