### ISSUE TITLE
🚧Move all cache related types to its own namespace

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#123]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

- [ ] Move all of the caching types to its own namespace called `Velaptor.Caching`.
- [ ] Change all of the cache types from `public` to 'internal`

### Acceptance Criteria

**This issue is finished when:**
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
This was done in #84
