### ISSUE TITLE
🚧Improve Font Texture Atlas Layout

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#126]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Currently the font texture atlas that is created while loading fonts is not optimized.  There is a lot of extra space between characters as well as a lot of extra empty space at the bottom.  This can be optimized to reduce the memory footprint on the CPU side as well as the GPU side be removing this extra space and rearranging the glyphs.

**Current Font Texture Atlas Layout:**
<img width="780" alt="image" src="https://user-images.githubusercontent.com/85414302/149020974-4ac5eb3b-61cd-4dde-812b-5f7a2a826dd2.png">

### Acceptance Criteria

**This issue is finished when:**
- [ ] Optimize the layout of the glyphs by rendering them to the texture from biggest to smallest from left to right, then top to bottom.
    - This will require calculating the number of glyphs and figuring out how to lay out the rows and columns to be as close to equal as possible. This will require some work to figure out how to do this because of the difference between the widths and heights from glyph to glyph.
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
