### ISSUE TITLE
🚧Rework content disposal system

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#127]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

When disposing of `IContent` items during the game loop, the app throws an **_OpenGL_** exception.  This is due to the fact that during the disposal process, the GPU side of things are destroyed which is what is supposed to happen.  The problem is that when the batch is ended and Velaptor tells _**OpenGL**_ to render what is in the batch, the texture has been destroyed which is why an _**OpenGL**_ error occurs.

The idea is to remove the `Dispose()` method and pattern from `IContent` items, which forces the user to have to use the `IContentLoader` implementation to unload content.

To prevent an _**OpenGL**_ error from occurring, the user calls `IContentLoader.Unload()`, which will send an `Observable` notification that will remove the batch item immediately upon disposal to prevent an attempt to render it when the batch ends.

This means that the batcher (`TextureBatchService`), as well as other batchers, will have to subscribe to the **_Observable_** to receive a notification from `IContentLoader` with a special ID to find the batch item so it can be removed.

Create an `Observable` that will replace the `Dispose()` methods in each `IContentLoader` implementation.  These methods are only meant to be called once by _**Velaptor**_ to be able to free resources when the application is shut down.  Currently the `Dispose()` method can be called anytime by the user of the library which means this will unload the content system as a whole which is only meant to occur when the app is closed.  This will crash the application and needs to be prevented.

### Acceptance Criteria

**This issue is finished when:**
- [x] Remove `IsPooled` property from `IContent`
- [x] Create a new `Observable` called `RemoveBatchItemObservable`
    - Purpose: Used to remove a batch item in the `TextureBatchService`
    - [x] Make this class a singleton which will be instantiated from the **IoC Container** upon creation
    - [x] Will send out the texture ID in the broadcast so that way the proper batch item can be found for removal
- [x] Create a new `Observable` called `ShutDownObservable`
    - Purpose: Used to signal that the application is shutting down and all content needs to be disposed of.  This will send out `Dispose` observable notifications to dispose of all the content items.
    - [x] Make this class a singleton which will be instantiated from the **IoC Container** upon creation
    - [x] Setup each `ILoader` implementation to subscribe to this observable to get a notification to shut down by unloading all of the currently loaded content and remove disposal code
        - [x] AtlasLoader
        - [x] FontLoader
        - [x] SoundLoader
        - [x] TextureLoader
- [x] Create a new `Observable` called `DisposeObservable`
    - Purpose: Disposes of a content item.  This replaces the public `IDisposable` implementations to prevent user from invoking them.
    - [x] Make this class a singleton which will be instantiated from the **IoC Container** upon creation
    - [x] Setup each `ITexture` implementation to subscribe to this observable to get a notification to dispose of resources
    - [x] Unsubscribe from the observable when the observable notification is received
- [x] Setup `SpriteBatch` implementation
    - [x] Remove `IDisposable` interface from `ISpriteBatch` interface
    - [x] Inject `ShutDownObservable`
    - [x] Move disposal code to subscription method
- [x] Setup `IShaderProgram` implementations
    - [x] Remove `IDispose` from `IShaderProgram` interface
    - [x] `TextureShader`
        - [x] Remove `IDisposable` interface from `IShaderProgram` interface
        - [x] Inject `ShutDownObservable`
        - [x] Move disposal code to subscription method
    - [x] `FontShader`
        - [x] Inject `ShutDownObservable`
        - [x] Move disposal code to subscription method
- [x] Setup `IGPUBuffer<T>` implementations
    - [x] Remove `IDispose` from `IGPUBuffer<T>` interface
    - [x] `TextureBuffer`
        - [x] Remove `IDisposable` interface from `IGPUBuffer<T>` interface
        - [x] Inject `ShutDownObservable`
        - [x] Move disposal code to subscription method
    - [x] `FontBuffer`
        - [x] Inject `ShutDownObservable`
        - [x] Move disposal code to subscription method

_**NOTE: It was decided to no implement these due to future changes**_
- ~☑️ Setup the each UI control implementation to send out a notification to the `TextureBatchService` using the `RemoveBatchItemObservable` to remove any pending batch items that will be rendered~
    - ~☑️ `Label`~
    - ~☑️ `Button`~
- ~☑️ Setup `TextureBatchService`~
    - ~☑️ Inject `RemoveBatchItemObservable` observable for subscription and use~
    - ~☑️ The notification will come with the **_Texture ID_** identify which batch item to remove~
        - ~🗒️The idea of "removing" a batch item is not actually physically removing the item from the batch list, but simply settings its `shouldRender` to a value of false and calling its `Empty()` method.~
    - ~☑️ Disposing of the service will unsubscribe from the observable~
- [x] Code documentation added if required

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
All of the _**Observables**_ have had the postfix of "Observable" refactored to "Reactor" to allow more control over type references without having to spread using alias setups all over the code base.  This was to have the ability to have our own name instead.
