### ISSUE TITLE
🚧Research and investigate different ways to manage caching

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#129]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Look into different ways to cache items to help improve the caching system.

Refer to this link [here](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.caching.memorycache?view=dotnet-plat-ext-6.0) for more information

### Acceptance Criteria

**This issue is finished when:**
~☑️ Code documentation added if required~
~☑️ Unit tests added~
~☑️ All unit tests pass~

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [ ] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
