### ISSUE TITLE
🚧Refactor name of GLExtensions to class name

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#135]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Refactor the name of the `GLInvokerExtensions` class and `IGLInvokerExtensions` interface to the values below.

`GLInvokerExtensions` class `👉🏼OpenGLService`
`IGLInvokerExtensions` interface `👉🏼IOpenGLService`

### Acceptance Criteria

**This issue is finished when:**
- [x] `GLInvokerExtensions` class name refactored
- [x] `GLInvokerExtensions` interface name refactored
- [x] All references and updated
- [x] All parameter names updated
- [x] All private class field names updated
- [x] All parameter doc descriptions refactored and all matching
- [x] Code documentation added if required
- [ ] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Related Work

- #105 
- #108 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
