### ISSUE TITLE
🚧Research radians perf improvement

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#136]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Do some research and performance profiling on the current method of getting radians vs using the `Math.Atan2()` method.

The idea here is that if the `Math.Atan2()` method is faster, then we can change out the implementation of the `PublicTextensionMethods.ToRadians()` method with code to use the `Math.Atan2()`

Also refer to this video for more information [Trigonometry • Math for Game Devs [Part 3] - 1:47:24](https://youtu.be/1NLekEd770w)

### Acceptance Criteria

**This issue is finished when:**
- [ ] If the using the method `Math.Atan2()` is more performant, create an issue to implement this work
- ~☑️ Code documentation added if required~
- ~☑️ Unit tests added~
- ~☑️ All unit tests pass~

### ToDo Items

- ~☑️ Draft pull request created and linked to this issue~
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- ~☑️ Issue linked to proper milestone~
- ~☑️ Unit tests have been written and/or adjusted for code additions or changes~
- ~☑️ All unit tests pass~

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Investigation reveled that standard performance of calculating radians is very performant.
This card was also originally meant to research perf for getting angle between lines but has proved to be much more complicated then that.
