### ISSUE TITLE
🚧Add discord badge to project README

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#137]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add a discord badge to the project README file.

Use [Shields IO](https://shields.io/)

### Acceptance Criteria

**This issue is finished when:**
- [x] A badge is added to the README file

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

Not Required:
- ~Unit tests have been written and/or adjusted for code additions or changes~
- ~All unit tests pass~

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
