### ISSUE TITLE
🚧Update branching diagram

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#139]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the branching diagram to accommodate the new _**preview/feature**_  branching workflow

Use the draw.io app to do this

### Acceptance Criteria

**This issue is finished when:**
- [ ] Branching diagram update

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
