### ISSUE TITLE
🚧Add caching to the font atlas creation process

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#140]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add caching to the font atlas creating process by adding a caching implementation of `IItemCache<TCacheKey, out TCacheType>` interface.

The purpose of this is to improve content loading performance when loading fonts.  Currently when loading a font, the final atlas texture that is created from the data of the `FontAtlasService` is cached but the data used to create the `Texture` object is not cached. 

**Places where the atlas is created:**
`FontLoader.Load()` Line # 213
`TextureCache.GetItem()` Line # 226

During the font loading process, the data is created from scratch every time.  It is built 2 times for every font.  Once in the `FontLoader` and once in the `TextureCache`.
Caching the data itself could greatly improve performance.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Caching added to the `FontAtlasService` implementation
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [ ] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
