### ISSUE TITLE
🚧Update Branching Documentation

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#147]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the **Preview Branches** section to call out that _**preview feature branches**_ get merged into the preview branch and that is the only way to get changes into the branch.

Add the section below the **Preview Branches** section about **Preview Feature Branches**

### Acceptance Criteria

**This issue is finished when:**
- [x] Branching documentation updated relating to how changes are brought into a preview branch
- [x] Branching documentation updated by adding a section about **preview feature branches**

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Related Work

- KinsonDigital/issues-repo#9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
