### ISSUE TITLE
🚧Update PR templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#150]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the preview release pull request template.   
This is located in the PR template file named _**preview-release-pr.md**_

Remove the entire description section.  Since this is for simply getting preview release branches into release branches, there is no detailed description required. 
![image](https://user-images.githubusercontent.com/85414302/152269140-4b78a59b-a2c9-4850-b79a-2ce731c37d0d.png)

---

Also remove the unit testing section.
![image](https://user-images.githubusercontent.com/85414302/152269292-5c64de90-2ee5-4126-a1ac-901611a669f9.png)

Add a new check box asking the user if they added a breaking changes label to the card
![image](https://user-images.githubusercontent.com/85414302/154361957-b973587d-0862-4552-a38b-9cf17831fc94.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] Description section removed
- [x] Unit testing section removed
- [x] Add new check box to add breaking changes label
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
It was discovered that the approach that was taken to create markdown links to images in the repository to display the badge images for the PR templates do not work in the markdown for issues.

PR was reverted and this issue will be reopened to implement it differently.  A new PR will be created and added to the issue.
