### ISSUE TITLE
🚧Update discord link in twitter announcement for all workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#151]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

The discord link is incorrect in the twitter announcements for the associated workflows.
Update the discord link to the following:
- https://discord.gg/qewu6fNgv7

### Acceptance Criteria

**This issue is finished when:**
- [x] Discord link updated
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
