### ISSUE TITLE
🚧Setup Codecov to collect code coverage data

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#152]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Currently, the Velaptor library is not publishing code coverage results to [Codecov](https://app.codecov.io)

This is a shame.  Let's fix this!!!

Set up **_Codecov_** to collect coverage data from the project and verify that the code coverage GitHub secret is correct.

### Acceptance Criteria

**This issue is finished when:**
- [x] Code coverage collection with [Codecov](https://app.codecov.io) setup

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [x] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
### **Explanation:**
After some investigation, it was discovered that code coverage publishing was setup in the workflows to publish to _**codecov**_ using the _**codecov**_ action.

Further investigation revieled that the action version being used was out of date.  Upon looking in the GitHub marketplace for the action, a new major version was released with the current version _**v1.5.2**_ being used being deprecated.  

This lead me to believe that was the reason for the lack of publishing of reports.  I upgraded the action to _**v2.1.0**_ but the reports were still not being published.   I stood up a self hosted runner to do some debugging and verify some things and realized that the report is being generated but for some reason is still not being picked up by the _**codecov**_ GitHub action.

### **Here are some references:**
- [GitHub Action](https://github.com/marketplace/actions/codecov)
- [Repo With Issue](https://github.com/KinsonDigital/Velaptor/runs/5231708201?check_suite_focus=true)
    - Look at the **Execute Unit Tests** and **Publish Code Coverage Results** tasks to see what is being generated and that it is not being picked up.
- [Codecov Opened Issue](https://github.com/KinsonDigital/Velaptor/runs/5231708201?check_suite_focus=true)

**Comment by CalvinWilkinson** [comment]
Unassigned from preview release v1.0.0-preview.7
It will take longer then what is required to get this issue solved before the release.
