### ISSUE TITLE
🚧Simplify null parameter checks for all constructors

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#153]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Using a guard pattern using a static class to wrap and simplify the throwing of exceptions, create the guard class and implement throughout the code base.

Great video [here](https://www.youtube.com/watch?v=MHIheQ2_Yb4&t=318s) to demonstrate this.

### Acceptance Criteria

**This issue is finished when:**
- [x] Guard class created with unit tests
- [x] Use `[CallerArgumentExpression]` for method params to help improve the exception message
- [x] Replace `EnsureThat.StringParamIsNotNullOrEmpty()` exception message with _**The string parameter must not be null or empty.**_
    - This will require changes to unit tests.
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
