### ISSUE TITLE
🚧Add ability to render line primitives

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#154]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add the ability for users to render primitive lines.  The lines should have the following features.
- Solid colors
- Line thickness

> **Note**
> Do not use the already implemented rectangle buffer and related code for simulating lines.
> This would only give the ability to render vertical and horizontal lines, but not diagonal lines.

NOTE: Refer to the private repo called **_RenderLines_** for a basic demo application that can be used to build upon to figure out how to do this.

### Acceptance Criteria

**This issue is finished when:**

- [x] Create a struct named `Line` for use in rendering calls and other uses for library users
    - make `public`
- [x] Create a read-only struct named `LineGPUData` for holding data related to rendering lines that need to be sent to the GPU
    - make `internal`
- [x] Create struct named `LineVertexData`
    - make `internal`
- [x] Create a new `GPUBufferBase<TData>` implementation named `LineGPUBuffer` for rendering lines
   - make `internal`
- [x]  Create rectangle vertex and fragment shader code files
    - These need to be embedded in resources
- [x] Create a new GPU buffer class named `LineGPUBuffer` for sending rectangle data to the GPU

### Main Line Rendering Method
- [x] Create a private main method that all other render line methods will call.  This will render filled and not filled with all possible options
```cs
private void RenderLine(
    Vector2 stop,
    Vector2 stop,
    Color color,
    uint thickness, int layer)
```

### SpriteBatch `RenderLine()` Overloads

- [x] `Render(Line line, int layer = 0)`
    - Color = White
    - Thickness = 1
- [x] `RenderLine(Vector2 start, Vector2 end, int layer = 0)`
    - Color = White
    - Thickness = 1
- [x] `RenderLine(Vector2 start, Vector2 end, uint thickness, int layer = 0)`
    - Color = White
- [x] `RenderLine(Vector2 start, Vector2 end, Color color, int layer = 0)`
    - Thickness = 1
- [x] `RenderLine(Vector2 start, Vector2 end, Color color, uint thickness, int layer = 0)`
- [x] Ability to render a line from point A to point B
- [x] Ability to choose a solid color for the line
- [x] Ability to choose line thickness

---

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes added to the issue.

**Reason:**  This is due to the removal of a public constant named `BatchSize` in the public interface `IRenderer`.

Even though this is a public API change and this makes it a breaking change, there is no use for this constant for a public user so it was probably never used and the impact is really minimal.
