### ISSUE TITLE
🚧Add circle rendering

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#155]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add the ability to give the users to render primitive lines.  The lines should have the following features.
- Filled circles
- Empty circles
- Solid colors
- Horizontal color gradients
- Vertical color gradients
- Empty circles line thickness

> **Note** The code for rectangles can be reused.  The rectangle can be easily converted to a circle by making the radius X and Y the max values. You can take advantage of this by creating a rectangle and locking the radius X and Y to the maximum amounts.  You can use the same GPU buffer code to render the rectangles as circles.

### Acceptance Criteria

**This issue is finished when:**

- [x] Create a struct named `CircleShape` for the use of rendering calls
    - make `public`
- [x] Rename the `RectBatchItem` struct to `ShapeBatchItem`

### Renderer `Render()` method

- [x] `Render(CircleShape circle, int layer = 0)`

---

Filled Circle Details:
- [x] Ability to set the solid fill color
- [x] Ability to set diameter and radius
- [x] Ability to render horizontal color gradients
- [x] Ability to render vertical color gradients

Empty Circle Details:
- [x] Ability to control the border-color
- [x] Ability to set diameter and radius
- [x] Ability to render horizontal color gradients
- [x] Ability to render vertical color gradients
- [x] Ability to control the empty border thickness

Other:
- [x] Create a new scene to test out the circle
- [x] Code documentation added if required
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [x] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

### Related Work

- #75 
- #154 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
