### ISSUE TITLE
🚧Update documentation updates section for pull request templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#158]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

For all of the applicable pull request templates, update the description of the 📃Documentation Updates📃 section.

**Refer to image below:**
![image](https://user-images.githubusercontent.com/85414302/153012175-6b7f6a03-254b-468d-aff4-98c98ed5553b.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] Update the description to the following:
    - Contains changes that require documentation updates to **_existing_** code docs or Velaptor documentation.

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [x] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
