### ISSUE TITLE
🚧Update project item issue template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#159]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Remove the bottom 2 ToDo items in the project item issue template.

The reason is because the **Acceptance Criteria** already covers this and it is redundant

**Refer to image below:**
![image](https://user-images.githubusercontent.com/85414302/153013046-75984b00-efff-473c-8fcd-292ce2875211.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] Bottom to unit test related ToDo items removed

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
