### ISSUE TITLE
🚧Refactor texture GPU structs to be readonly for performance

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#161]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Make both the `TextureQuadData` and `TextureVertexData` structs readonly to gain its performance benefits.

This will most likely not make it as easy to construct new instances of these structs for use and unit testing.
Create a factor to make it easier to construct new instances of these if required.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Make the `TextureVertexData` struct readonly
- [ ] Make the `TextureQuadData` struct readonly
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Closed

**Reason:** This was already implemented in a another issue
