### ISSUE TITLE
🚧Create a backers markdown file

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#162]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create a markdown file to list out monthly backers of the project.

Setup the file with the following contents:

Velaptor is a new MIT-licensed open source project with its ongoing development and is looking for awesome sponsors and backers. If you'd like to help and be listed here, please consider [ sponsoring Velaptor development](https://github.com/sponsors/KinsonDigital).

### Acceptance Criteria

**This issue is finished when:**
- [ ] Backers file added to the solution

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
