### ISSUE TITLE
🚧Update the sponsorship tiers

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#163]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the sponsorship tiers with links for the following

![image](https://user-images.githubusercontent.com/85414302/153586561-eb14e557-d341-4a41-baa0-8639be8b5ed1.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] Sponsor links updated
- [x] For any sponsor tiers that mention a twitter account, convert the word **twitter** into a link to my twitter account

### ToDo Items

- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Issue Dependencies

- #162 
- KinsonDigital/CASL#77

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
