### ISSUE TITLE
🚧Create custom exceptions for no keyboard and mouse

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#17]
### Title Updated

- [X] I have updated the title by replacing the '\<title\>' section.

### Description
Create custom exceptions for lack of keyboard and mice detected in the system.

### Acceptance Criteria

**This issue is finished when:**
1. [x] Create custom exception named **NoKeyboardException**
2. [x] Create custom exception named **NoMiceException**
3. [x] Exceptions in `GLWindowFacade.Init()` method replaced with new exception

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

**Comment by CalvinWilkinson** [comment]
Re-opened due to premature closing of the PR.  This should only be closed once the PR has been code reviewed and approved.
