### ISSUE TITLE
🚧Refactor WindowSizeEventArgs ctor param data types

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#171]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Refactor the data types of both the `width` and `height` constructor parameters and properties for the `WindowSizeEventArgs` class from `int` to `uint`.

This will of also force a change to be done in the unit testing file for this class in the _**WindowSizeEventArgsTests.cs**_ file.

**Refer to the changes below:**

_**WindowSizeEventArgs.cs**_ File Changes:
```diff
    /// <summary>
    /// Holds information about an event when a window resizes.
    /// </summary>
    internal class WindowSizeEventArgs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WindowSizeEventArgs"/> class.
        /// </summary>
        /// <param name="width">The width of the window.</param>
        /// <param name="height">The height of the window.</param>
-        public WindowSizeEventArgs(int width, int height)
+       public WindowSizeEventArgs(uint width, uint height)
        {
            Width = width;
            Height = height;
        }

        /// <summary>
        /// Gets the width of the window.
        /// </summary>
-        public int Width { get; }
+       public uint Width { get; }

        /// <summary>
        /// Gets the height of the window.
        /// </summary>
-        public int Height { get; }
+       public uint Height { get; }
    }
```

_**WindowSizeEventArgsTests.cs**_ File Changes:
```diff
        [Fact]
        public void Ctor_WhenInvoked_SetsProperties()
        {
            // Arrange
-            var eventArgs = new WindowSizeEventArgs(123, 456);
+           var eventArgs = new WindowSizeEventArgs(123u, 456u);

            // Act
            var actualWidth = eventArgs.Width;
            var actualHeight = eventArgs.Height;

            // Assert
-            Assert.Equal(123, actualWidth);
+           Assert.Equal(123u, actualWidth);
-            Assert.Equal(456, actualHeight);
+           Assert.Equal(456u, actualHeight);
        }
```

### Acceptance Criteria

**This issue is finished when:**
- [x] Both constructor parameter data types refactored
- [x] Both properties updated
- [x] Unit tests updated accordingly (_**if required**_)
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SyedMSawaid** [comment]
I would like to work on this.

**Comment by CalvinWilkinson** [comment]
@SyedMSawaid You got it!!
Issue assigned and setup for you to work on.
