### ISSUE TITLE
🚧Create Guard for FreeTypeInvoker

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#172]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create a new **_Guard_** method named `NotNullPointer()` in the `EnsureThat` static class.

Use this guard in the `FreeTypeInvoker` class to check for null/zero pointers for each method

### Acceptance Criteria

**This issue is finished when:**
- [ ] Create new guard in `EnsureThat` class
- [ ] Implement new guard in each method of the `FreeTypeInvoker`
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
