### ISSUE TITLE
🚧Use new pointer Guard to check for null pointers in GLFWInvoker

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#173]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Use the new pointer Guard in the `EnsureThat` class created in issue #172 in the new `GLFWInvoker` class in certain methods to make sure that the pointer is not null or zero.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Use the **Guard** in the `GetMonitorContentScale()` method
- [ ] Use the **Guard** in the `GetVideoMode()` method
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Issue Dependencies

- #172

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
