### ISSUE TITLE
🚧Use null/empty string guard in GLInvoker methods

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#174]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Find all methods with a string parameter in the `GLInvoker` class and use the `EnsureThat.StringParamIsNotNullOrEmpty()` guard on the param.

### Acceptance Criteria

**This issue is finished when:**
- [x] All methods in `GLInvoker` class with a string param have guard checking for a null/empty string
- [x] Code documentation added if required
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AndreBonda** [comment]
Hi, I want to do it.
