### ISSUE TITLE
🚧Refactor entire codebase to use global using directives feature

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#180]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Refactor the entire code base to take advantage of [Global Using Directorys](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#global-using-directives) feature.

This is a many tile change and will probably require use of the small file filter tool that I made so that way I can keep track of what files I have processed.

### Acceptance Criteria

**This issue is finished when:**
- [ ] All files refactored to use new global using directive feature
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Issue Dependencies

- #97 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
