### ISSUE TITLE
🚧Refactor to file scoped namespacing

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#181]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Refactor the entire code base to take advantage of [File-Scoped Namespace Declaration](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#file-scoped-namespace-declaration) feature.

### Acceptance Criteria

**This issue is finished when:**
- [x] All files refactored to use the new file-scoped namespace declaration feature.

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Issue Dependencies

- #97

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
