### ISSUE TITLE
🚧Refactor entire code base to use constant interpolated string feature

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#182]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Refactor the entire code base to take advantage of [Constant Interpolated Strings](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#constant-interpolated-strings) feature.

Do a search throughout the code base to find areas where this can be done.  This might be able to be achieved using the code analyzers in the solution.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Code base refactored to use new constant interpolated string feature.
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Issue Dependencies

- #97

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
