### ISSUE TITLE
🚧Finish upgrading codebase to NET 6.0+ and newest verion of C# 10

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#184]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

There was important additional content that did not get pushed before completing PR #179

To fix this issue, the PR was reverted which produced PR #183

This PR was created for the purpose of implementing the forgotten changes for issue #97

### Acceptance Criteria

**This issue is finished when:**
- [x] Projects upgrade to C# lang version **v10** and _**NET 6.0**_
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
