### ISSUE TITLE
🚧Create buttons for Non-Animated Graphics Scene

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#187]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Instead of using the arrow keys on the keyboard to flip the octagon texture horizontally and vertically, create 4 buttons around the texture that will perform this task.

One button will be on the left side, one on the right, one above and one below.  Each one will have the proper graphic, icon, or text to represent which direction the texture flip will occur.

**Sample Setup:**
![image](https://user-images.githubusercontent.com/85414302/154818961-7093984c-0634-44bb-9464-04e2654c4bb9.png)

### Acceptance Criteria

**This issue is finished when:**
- [ ] A button on the left side of the texture to flip the texture horizontally to the left
- [ ] A button on the right side of the texture to flip the texture horizontally to the right
- [ ] A button below the texture to flip the texture vertically to the bottom
- [ ] A button above the texture to flip the texture vertically to the top
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Issue Dependencies

- #97 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
