### ISSUE TITLE
🚧Improve release notes

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#188]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add the 2 production and preview release note template files to the **_~/ReleaseNotes_** directory.
Also update all of the release notes to match the release note templates in regards to emojis and layout.

**Template Files:**
- [Preview-Release-Notes-TEMPLATE.md](https://github.com/KinsonDigital/Velaptor/files/9125795/Preview-Release-Notes-TEMPLATE.md)
- [Production-Release-Notes-TEMPLATE.md](https://github.com/KinsonDigital/Velaptor/files/9125798/Production-Release-Notes-TEMPLATE.md)

Also add links to the github issues for all of the release notes for version **_v1.0.0-preview.8_**.

Make the issue link layout match the release notes for version **_v1.0.0-preview.9_**

### Acceptance Criteria

**This issue is finished when:**
- [x] Update all of the emojis for the existing release notes
- [x] Release note template files added
- [x] Issue links for each item in **_v1.0.0-preview.8_** release notes updated to new style.
- [x] All release notes refactored

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
