### ISSUE TITLE
🚧Create release notes for v1.0.0-preview.7

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#190]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create release notes for preview release _**v1.0.0-preview.7**_.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Release notes created

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
