### ISSUE TITLE
🚧Update release PR templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#194]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

1. Add a new section to the **preview** and **production** release PR templates that will list out all of the issues that have been released.  Name the section **Issues Released**
    - Refer to PR #193 for example
2. Update the **✅Code Review Checklist✅** section.  Refer to image below.
3. Remove the code review checklist item 👉🏼"My code follows the coding style of this project. "

![image](https://user-images.githubusercontent.com/85414302/154856687-22b976b2-db34-4c32-81d9-d828855a6feb.png)

### Acceptance Criteria

**This issue is finished when:**
- [ ] Preview release PR template updated
- [ ] Production release PR template updated
- [ ] Code review checklist item updated to:
    - Issues being release listed in the **Issues Released** section

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [ ] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
