### ISSUE TITLE
🚧Increase markdown headers in issue templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#195]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Go through all of the issue templates and increase the header markdown "section titles" by one

### Acceptance Criteria

**This issue is finished when:**
- [ ] All issue templates updated

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Looking into this it was discovered that this cannot be done with YAML style issue templates.  Maybe markdown style issue templates but not YAML style.

Because of this, it was decided it was not worth losing the benefits of the YAML style templates.

Issue closed.
