### ISSUE TITLE
🚧Improve button control by using primitive rectangles

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#196]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Currently the button has to load a texture to display the face of the button.  This is expensive and not very customizable for a standard button.

Change the button to be able to use rectangles to render the face of the button. 

### Acceptance Criteria

**This issue is finished when:**
- [x] The button renders its face using rectangles instead of textures
- [x] Textures are removed from the project
- [x] The color of the face of the button is customizable
- [x] When the width or height of the button is changed, the label automatically centers itself
- [x] When the width or height of the button is smaller then the rectangle bounds of the label, the text does not render outside of the bounds of the button face.
- [x] The button has a `bool` border property that can be turned on and off
- [x] The button has a `Border Color` property
- [x] The button has a `Border Thickness` property
- [x] The button has a `CornerRadius` property
- [x] Add `AutoSize` property of type `bool` to the `Label` control
    - When true, the width and height of the `Label` will automatically be controlled based on the size of the font
    - If `AutoSize` is set to `false`, then the user can control the `Width` and `Height` of the control and only the characters contained within the bounds of will be rendered.
- [x] Add `AutoSize` property of type `bool` to the `Button` control
    - When true, the width and height of the `Button`  will automatically be controlled based on the size of the button `Label` text
    - If `AutoSize` is set to `false`, then the user can control the `Width` and `Height` of the control.
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
