### ISSUE TITLE
🚧Update code base to use C# 10 and .NET 6.0

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#197]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Some how during the _**v1.0.0-preview.7**_ release, the issues dealing with updating the entire project to _**C# 10**_ and **.NET 6.0** failed.  This somehow was missed with the reverting of a PR due to a mistake trying to be rectified with the preview release.

This issue resolves this and sets all of the projects in the solution/code base to the proper **intended** version of C# and NET SDK.

Refer to the **Related Workd** section below to get a list of the PR's and Issues related to this from the last release.

### Acceptance Criteria

**This issue is finished when:**
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### **Issues:**
- #97 
- #184

### **Pull Requests:**
- #179 
- #183 
- #185 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
