### ISSUE TITLE
🚧Add branch to status check workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#199]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

For all of the applicable status check workflows, add a branch filter for the _**preview/v\*.\*.\*-preview.\***_ branches so status checks can be ran when pull requests are bringing _**preview feature**_ branch changes into a **preview** branch.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Update **build-status-check** workflow
- [ ] Update **unit-testing-status-check** workflow
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
