### ISSUE TITLE
[Project Item] - Add my test feature

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#20]
### Title Updated

- [X] I have updated the title by replacing the '\<title\>' section.

### Description

As a user, I want a new shiny feature, because I said so.

### Acceptance Criteria

**This issue is finished when:**
1. [ ] Code documentation added
2. [ ] Unit tests added
3. [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [ ] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [ ] Issue linked to the proper project
- [ ] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by CalvinWilkinson** [comment]
This was for testing purposes
