### ISSUE TITLE
🚧Swap out various testing application controls for a slider control

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#207]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Throughout the various scenes in the **Velaptor Testing Application**, swap out various buttons with the new slider control to improve the experience for testing.

This will make it easier and more intuitive for testing as well as reduce QA time testing.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Buttons in each scene replaced with slider control where applicable.

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Issue Dependencies

- #186 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
**Closed Without Implementation**

**Reason:**
This is due to the change in direction in regards to the UI control API side of Velaptor.  It was decided to deprecate and stop development of the UI API.
