### ISSUE TITLE
🚧Rework the Mouse and Keyboard classes

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#209]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

## **Description**

Completely rework how the `Mouse` and `Keyboard` classes receive updates to its state.

### **Issue 1:**
Currently, the methods `SetState()`, `SetXPos()`, `SetYPos()`, `SetScrollWheelSpeed()`, and `SetScrollWheelDirection()` methods are all public but should not be.  They only serve the purpose of setting the state of the mouse with calls from `GLFW`.

### **Issue 2:**
These methods called out in **_Issued 1_** need to be hidden from the user but cannot be due to the `IMouseInput`, `IKeyboardInput`, and `IGameInput` interfaces.  The methods are being used as a way for `GLFW` to communicate about the state of the `Mouse` and `Keyboard`.  Instead of using a public interface to communicate the state of the `Mouse` or `KeyBoard`, use the [observable pattern](https://docs.microsoft.com/en-us/dotnet/standard/events/observer-design-pattern) to communicate between `GLFW` and the 2 input classes.  This will simply everything greatly. 

### **Issued 3:**
The interfaces `IMouseInput`, `IKeyboardInput`, and `IGameInput` are currently forcing all of these methods to be public when they should not be.  The `IGameInput` interface needs to be removed from the code base.

### **Issue 4:**
Currently the `IGameInput` interface holds a static `Dictionary<K, T>` to hold all of the keyboard key and mouse button states.  This is not ideal and has caused some unit testing issues as well.  The `Mouse` and `Keyboard` classes are already registered with the **IoC** container as a singleton, which means if the states are held privately in both the `Mouse` and `Keyboard` classes, there is no need for the static `Dictionary<K, T>`.

## **Acceptance Criteria**

**This issue is finished when:**
**Mouse:**
- [x] `Mouse` class contains non-static private dictionary to hold button states
- [x] Create new `internal` `Reactable<T>` implementation that will be **constructor** injected into the `Mouse` class for mouse position state.  This is what will be used by `GLWindow` to communicate the changes to the mouse state.   The reactable generic type parameter will be a tuple of `(int x, int y)`
    - Will communicate the following:
        - X position of mouse
        - Y position of mouse
- [x] Create new `internal` `Reactable<T>` implementation that will be **constructor** injected into the `Mouse` class for updating mouse button state.  This is what will be used by `GLWindow` to communicate the changes to the mouse state.   The reactable generic type parameter will be the tuple `(MouseButton button, bool isDown)`
    - Will communicate the following:
        - Button state
- [x] Create new `internal` `Reactable<T>` implementation that will be **constructor** injected into the `Mouse` class for updating mouse wheel state.  This is what will be used by `GLWindow` to communicate the changes to the mouse state.   The reactable type parameter will be the tuple `(MouseScrollDirection scrolDirection, int wheelValue)`
    - Will communicate the following:
        - Speed of mouse scroll wheel
        - Direction of mouse scroll wheel

**Keyboard:**
- [x] `Keyboard` class contains non-static private dictionary to hold button states
- [x] Create new `internal` `Reactable<T>` implementation that will be **constructor** injected into the `Keyboard` class.  This is what will be used by `GLWindow` to communicate the changes to the keyboard key state.   The reactable type parameter will be the a tuple of type `(KeyCode key, bool keyState)`
    - This will communicate the state of a single keyboard key

**Other:**
- [x] Code documentation added if required
- [x] Unit tests added
- [x] All unit tests pass
- [x] Create a new card to move `Reactable` subscription disposals to the `OnCompleted` implementation

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Issue Dependencies

- #210 
- #235 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Issue created to move Reactable subscription disposals to the OnCompleted implementations.
- #239

**Comment by CalvinWilkinson** [comment]
Issue complete for version v1.0.0-preview.9
