### ISSUE TITLE
🚧Research how to rework GLWindow and GLWindowFacade

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#210]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

⚠️WARNING⚠️
Be very careful with this.   `GLWindowFacade` provides mouse and keyboard state updates and controls the firing of various game loop updates to the `GLWindow` class.  Breaking changes are not expected but there is a high chance that issues can be introduced.  Lots of testing will have to be performed for this.

Research how to rework how the `GLWindow` and `GLWindowFacade` classes.
Use this information to create new issues to perform the work.

It seems to be overly complicated to have a `GLWindow` class that internally uses the `GLWindowFacade` class to provide the necessary window functionality from **OpenGL**.   Look into possibly removing the `GLWindowFacade` class entirely.  This would result in only having/needing the `GLWindow` class.

It seems like the only thing holding the `GLWindowFacade` class back from being unit tested, is the single `glWindow` field of type `Silk.NET.Windowing.IWindow` in the `GLWindowFacade` class.

Maybe there is a way we can properly **constructor** inject the `SILK.IWindow` instance into the `GLWindow` class instead which would mean we do not need the `GLWindowFacade` class at all.

This will greatly simply the code in this area as well as the need for unit tests.  This can also reduce the chance of bugs being introduced with future changes.

### Acceptance Criteria

**This issue is finished when:**
- [x] Rework researched
- [x] Issues created to perform the work
- [x] Update issue #209 dependencies with the issues created from this research

### ToDo Items

- ☑️ ~~Draft pull request created and linked to this issue~~ No code changes required
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Related Work

- #209 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
