### ISSUE TITLE
🚧Add caching to the Font.Measure process

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#212]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Currently, the `Font.Measure()` method takes some string data and measures the total width and height of the text to be rendered based on the text itself, and the font attributes such as font type, size, and style.

This is a bit of a costly operation.  Add caching to this method to help with performance.  This can be done by creating an `internal`  implementation of the `IItemCache` interface and using it inside of the `Font` class.

Maintain a total item cache of 1000 items.  If 1000 items are reached, then the oldest item will get popped off the stack of cached items to make room for the new one.

### Acceptance Criteria

**This issue is finished when:**
- [x] Performance optimized.
- [x] ~Add a property to the `IItemCache` interface and other implementations to set the maximum amount of items to hold in a cache~
- [x] ~Add a property to the `IItemCache` interface and other implementations to turn the size limit enforcement on and off~
- [x] ~Create an `IItemCache` interface implementation named `MeasuredTextCache`~

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
> **Note** Added a https://github.com/KinsonDigital/Velaptor/labels/%E2%9C%A8new%20feature
> This feature is a caching feature that can be enabled or disabled for the Font class.
