### ISSUE TITLE
🚧Add unit tests to RectGPUBuffer class

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#214]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add unit tests to test out the methods below in the `RectGPUBuffer` class

1. `ProcessBorderThicknessLimit()`
2. `ProcessCornerRadiusLimits()`

### Acceptance Criteria

**This issue is finished when:**
- [ ] `ProcessBorderThicknessLimit()` unit tested
- [ ] `ProcessCornerRadiusLimits()` unit tested
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Closed

**Reason:** Completed with some other issue
