### ISSUE TITLE
🚧Make adjustment to QA testing issue template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#215]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Make various changes to improve the _**QA Testing Issue Template**_.  This improves clarity and understanding of the process.
The name of the file is `qa-testing-template.yml`

**Refer to the image below for more context:**
![image](https://user-images.githubusercontent.com/85414302/167996600-c917357b-7675-4173-9b45-df8601eb7fd7.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] Use a label link to display the qa testing label for the checkbox below
![image](https://user-images.githubusercontent.com/85414302/167890329-5d46bcbf-f71d-40dd-93b8-105613efbecc.png)
- [x] Update the version syntax explanation in the info below the _**Version Of Velaptor Being Tested**_ section to the value below:
    - `v<major.minor.patch>[-preview-<prev-num>]`
- [x] Swap the _**Relevant Information**_ and _**Issues To Test**_ sections positionaly within the form.
- [x] Add period to the end of the sentence below
![image](https://user-images.githubusercontent.com/85414302/167891757-d15acfe3-e230-4871-9621-24f6fe27c9fc.png)
- [x] Issue template file added to the solution folder _**SolutionItems/GitHub/IssueTemplates**_
     - This is for ease of access within the IDEs **Visual Studio** and **JetBrains Rider**

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Related Work

- KinsonDigital/issues-repo#9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
