### ISSUE TITLE
🚧Add new section to preview release PR template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#218]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add a new section to the PR template for preview releases.

Currently, the linked issues can only hold a max number of items.  This causes issues when a release has more issues tied to it than can be linked.

Adding the new section will make the list limitless to make sure that all issues are listed.

![image](https://user-images.githubusercontent.com/85414302/156881249-27c3e670-a158-4859-b658-f4ae52d6f13e.png)

### Acceptance Criteria

**This issue is finished when:**
- [ ] Section added to the _**preview-release-pr.md**_ PR template file

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
