### ISSUE TITLE
🚧Make adjustments to release PR templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#219]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Make various changes to the **release PR templates** to accommodate the addition of **release issues** and to improve the release process.

### **Refer to image below for more info and context:**
![image](https://user-images.githubusercontent.com/85414302/167870817-8f1a83a0-68a1-40ea-abcf-4381bb1965dd.png)

---

### Acceptance Criteria

**This issue is finished when:**
- [x] Change the top section **✅Development Checklist✅** to **✅Code Review Checklist✅**
- [x] Remove the bottom section title **✅Code Review Checklist✅**
- ~Make the following changes to the **🌲Branching🌲** section.~
  - [x] ~Create a centered heading named Branching to show off the section~
  - [x] Create 3 check boxes for each of the following:
    - Does the name of the head(source) branch for this pull request have the correct preview branch syntax?
      - [x] Add a default collapsed region with the following about the syntax
        - Syntax: preview/v\<major-number\>.\<minor-number\>.\<patch-number\>-preview.\<prev-number\>
      Example: preview/v1.2.3-preview.4
    - Does the name of the base(target) branch for this pull request have the correct release branch syntax?
      - [x] Add a default collapsed region with the following about the syntax 
        - Syntax: release/v\<major-number\>.\<minor-number\>.\<patch-number\>
    Example: release/v1.2.3
    - Is the head(source) branch for this pull request created from a branch with the correct release branch syntax?
      - [x] Add a default collapsed region with the following about the syntax 
        - Syntax: release/v\<major-number\>.\<minor-number\>.\<patch-number\>
Example: release/v1.2.3
- Remove the sections asking what kinds of changes the release contains and the adding of labels.  Refer to list below on what to remove.
  - [x] 🐛Bugs🐛 Removed
  - [x] 💣Breaking Changes💣 Removed
  - [x] ✨Enhancements✨ Removed
  - [x] ⚙️Workflow (CI/CD> Changes⚙️ Removed
  - [x] 📃Documentation Updates📃 Removed
- [x] Refactor the **🧪Manual Testing🧪** text to the value below:
  - A QA issue has been created and manual QA testing has been performed for the changes being released
- [x]  Remove the checkbox below.  This is now done in the associated **Release ToDo Issue** that is linked to the PR
![image](https://user-images.githubusercontent.com/85414302/167869668-8eca361a-0f47-424d-972d-1fe7071de05c.png)
- [x] Add an item somewhere in the **✅Code Review Checklist✅** to add the appropriate release label to the PR.
  - [x] ~Add a table inside of a default collapsed section that describes the type of release labels to add~
- [x] Remove the following check boxes and associated info below them from all of the PR templates except the `feature-pr.md` feature PR template.
![image](https://user-images.githubusercontent.com/85414302/167858928-d41170b1-e636-45ec-8ea5-22b7db10d5b0.png)
- [x] Remove the following check box and associated info below it from all of the PR templates.
![image](https://user-images.githubusercontent.com/85414302/167859479-a75651ac-43db-4ad6-8b60-41a5c3ce77a7.png)

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Related Work

- KinsonDigital/issues-repo#9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
