### ISSUE TITLE
🚧Research how GitHub pages work

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#22]
### Title Updated

- [X] I have updated the title by replacing the '\<title\>' section.

## **Documentation:**
Research GitHub pages to see how it is done for a possible holding place for library/project documentation

## **Acceptance Criteria**

**This issue is finished when:**
- [ ] Look into how GitHub pages works and come up with a plan and decide if it should be setup for a place to hold library documentation.

### ToDo Items

- [x] ~Draft pull request created and linked to this issue~
- [x] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone
- [x] ~Unit tests have been written and/or adjusted for code additions or changes~
    * No unit tests required.
- [x] ~All unit tests pass~
    * No unit tests required.

**Comment by kselena** [comment]
Groomed.  Moved to issue #100
