### ISSUE TITLE
🚧Remove Mouse Scroll Speed

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#222]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Remove mouse scroll speed text in Test Mouse Scene.  The mouse speed behavior has been changed and does not represent a velocity anymore, but only a direction.  This is why it should simply be removed.

The code related to this is all located in the **_TestMouseScene.cs_** file.

![image](https://user-images.githubusercontent.com/96791049/156934201-5dfd7f39-79b2-4362-861d-4c8ecead0e61.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [x] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quinnrdavis** [comment]
Hi! I'm a new dev looking to make my first code contributions and this looks like a very doable first task. Could I work on this?

**Comment by CalvinWilkinson** [comment]
@quinnrdavis Absolutely!! 
If you need anything at all, don't hesitate to contact me on my [discord server](https://discord.gg/qewu6fNgv7).

You can ask questions about this issue itself, but also about dotnet, programming, the industry, etc.  :)
No such thing as a stupid question!!
