### ISSUE TITLE
🚧Combine batch services in SpriteBatch

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#226]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

The total number of items being injected into the `SpriteBatch` class are starting to get out of control.  Improve and cleanup the class and its associated unit tests by creating a new class named `BatchManager`.  This will contain all of the batch services to manage batching related operations.

### Acceptance Criteria

**This issue is finished when:**
- [x] Rename `IBatchManagerService` interface to `IBatchingService`
    - Not a breaking changed because this interface is internal
- [x] Create a new interface named `IBatchManager` and class `BatchManager` to hold all of the batching services
    - [x] The interface and class will be `internal` 
- [x] Inject all of the batch service implementations into the new `BatchManager` class
    - The API of the new interface and class will expose the required functionality of the batch service implementations
- [x] Inject the new `BatchManager` implementation into the `SpirteBatch` class and refactor `SpriteBatch` class
- [x] Code documentation added if required
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
