### ISSUE TITLE
🚧Create new ShaderManager class and refactor code to use it

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#227]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Combine all of the shader implementations into a new shader manager class.  This is to simplify what is getting injected into the `Renderer` class.  NOTE: The `Renderer` class used to be named `SpriteBatch`.

### Acceptance Criteria

**This issue is finished when:**
- [x] Create a new interface named `IShaderManager` and class named `ShaderManager`
    - ☑️ ~~Inject all `IShaderProgram` implementations into the new class~~
- [x] Refactor and update `Renderer` class
    - [x] Refactor class to use new `ShaderManager` API
    - [x] Update unit tests for `Renderer` class
- [x] Code documentation added if required
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
❕Change Notice❕
Instead of injecting all 3 shaders into the `ShaderManager`, it was decided to refactor the `ShaderFactory` class with the `RendererFactory` classes to help improve things.  Now the `ShaderFactory` gets injected into the `ShaderManager` instead. 

This is a recommendation directly from the **SimpleInjector**  documentation on how to deal with injecting multiple instances to the same type.
