### ISSUE TITLE
🚧Create new buffer manager class and refactor code to use it

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#228]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Combine all of the `IGPUBuffer` interface implementations into a new `IBufferManager` implementation.  This is o simplify what is getting injected into the `SpriteBatch` class. 

### Acceptance Criteria

**This issue is finished when:**
- [x] Create a new interface named `IBufferManager` and class named `BufferManager`
    - [x] Inject all `IBufferManager` implementations into the new class
    - [x] Create `IBufferManager` API to expose required functionality for shader implementations
- [x] Refactor and update `Renderer` class
    - [x] Refactor class to use new `BufferManager` API
    - [x] Update unit tests for `Renderer` class
- [x] Refactor the `BufferFactory` class to be like the `ShaderFactory` class
    - This is to be used to be injected into the `BufferManager` class instead of all 3 buffer types.
- [x] Code documentation added if required
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kselena** [comment]
Issue complete for v1.0.0-preview.9
