### ISSUE TITLE
🚧Update Microsoft.CodeAnalysis.NetAnalyzers nuget package

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#230]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the **Microsoft.CodeAnalysis.NetAnalyzers** nuget package from version **_v5.0.3_** to **_v6.0.0_** for all solution projects

### Acceptance Criteria

**This issue is finished when:**
- Nuget package updated for following projects
    - [x] Velaptor
    - [x] VelaptorTests
    - [x] VelaptorTesting

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Issue closed.   Will be released for v1.0.0-preview.9
