### ISSUE TITLE
🚧Refactor and simplify window objects

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#235]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

The goal of this change is to simplify the `GLWindow` and `GLWindowFacade` classes by refactoring and removing code.

The windowing system has become overly complicated and harder to maintain.  The eventual addition of other platforms and the differences of how windows are managed on those other platforms will introduce more complexity.  Doing this now is ideal to not only prepare for those future changes but to simply keep the code simple.

**Notes:**
1. Remove the `GLWindowFacade` class completely.
    - 99% of the code in this class can be moved over to the `GLWindow` class for use and is all interface based from **SILK**.  This means it will be easy to test.
    - A lot of the code in this class is duplicated in `GLWindow`.
2. Create a factory class with an interface to be used to create the **SILK** window.
    - The only thing that cannot be abstracted is the single line of code tells **SILK** to create the `IWindow` object.  The idea here is to inject the factory class into the `GLWindow` class for creating the `IWindow` object.  This would make the rest of the `GlWindowFacade` code easy to migrate to `GLWindow`
3. Be careful when the `IInputContext` object is created.
    - This object needs to be created sometime in the `IWindow.Load()` method or after.  This is because that is when the **OpenGL Context** has been created and that must exist first before creating the input object.
4. It is recommended to only port over one piece of `GLWindowFacade` at a time.  Every time the code is ported over, write unit tests to make sure they behave correctly.
5. Direct interaction with the `IWindow` object created from the factory inside of the `GLWindow` class will need to be performed in each `CachedValue` property.
6. A push notification will need to be performed in the `Init()` phase in `GLWindow` to notify the rest of the system that the **OpenGL Context** has been created.
    - This needs to be done using `IReactable<GLContextData>`

### Acceptance Criteria

**This issue is finished when:**
- [x] Create new factory named `WindowFactory`
    - This will be injected into `GLWindow` for creating the **SILK** `IWindow` object
- [ ] `GLWindowFacade` removed and not used anymore
- [ ] Everything operates as it did before
- [ ] `GLWindow` contains all of the combined behavior of `GLWindow` and `GLWindowFacade`

**Port Over Events:**
- [x] Load Event
- [x] Unload Event
- [x] UpdateFrame Event
- [x] RenderFrame Event
- [x] Resize Event

**Port Over Properties:**
- [x] public Vector2 Size
- [x] public Vector2 Location
- [x] public double UpdateFrequency
- [x] public bool CursorVisible
- [x] public StateOfWindow WindowState
- [x] public VelaptorWindowBorder WindowBorder
- [x] public string Title

**Port Over Methods:**
- [x] PreInit() Method
- [x] Init() Method
- [x] Show() Method
- [x] SwapBuffers() Method
- [x] Close() Method
- [x] Dispose() Method

**Port Over Event Handlers:**
- [x] GLMouseInput_MouseScroll() Method
- [x] GLMouseMove_MouseMove() Method
- [x] GLMouseInput_MouseDown() Method
- [x] GLMouseInput_MouseUp() Method
- [x] GLKeyboardInput_KeyDown() Method
- [x] GLKeyboardInput_KeyUp() Method

**Other:**
- [x] Code documentation added if required
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Related Work

- #209 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Issue closed for preview release v1.0.0-preview.9
