### ISSUE TITLE
🚧Refactor switch statements and out of range exceptions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#237]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Replace all `EnumOutOfRangeException`'s and `ArgumentOutOfRangeException`'s with the `InvalidEnumArgumentException` exception.  This should only be done in use cases where a `switch` statement is being used against an `enum`.

**Purpose:**
This is to handle scenarios where the numerical value of an `enum` might not be one of the numerical constants in the `enum` definition.  It is common for people to handle `enums` in a numerical fashion using loops and other means to help simply code.  Sometimes people introduce problems with the numerical value of the `enum` going out of range of the definition values.  This refactoring handles those scenarios.

Also, refactor all applicable `switch` constructs related to the exception refactor to `switch` expressions.
> **Note**
> Should should only apply to the same `switch` constructs that were refactored for the exceptions stated above.

Below is a good example of an `enum` check with a `switch` statement that needs to be refactored.
**Example:**
https://github.com/KinsonDigital/Velaptor/blob/41fd7eb9e66828cf0126fa8c5042436530320f62/Velaptor/NativeInterop/OpenGL/OpenGLService.cs#L188-L205

### Acceptance Criteria

**This issue is finished when:**
- [ ] All use cases of the `EnumOutOfRangeException` refactored to `InvalidEnumArgumentException`.
- [ ] All use cases of the `ArgumentOutOfRangeException` refactored to `InvalidEnumArgumentException`.
- [ ] All XML comment references to `InvalidEnumArgumentException`'s and `ArgumentOutOfRangeException`'s refactored to `InvalidEnumArgumentException`
- [ ] The `EnumOutOfRangeException` removed entirely from the code base.
- [ ] The `EnumOutOfRangeExceptionTests` removed entirely from the code base.
- [ ] `switch` constructs refactored to `switch expressions`

### ToDo Items

- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Issue Dependencies

- #437 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sbundaz** [comment]
I'll take this.
