### ISSUE TITLE
🚧Refactor Reactable unsubscriber disposal code

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#239]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Throughout the code base, there are areas where `Reactables` are used.  These `Reactables` are being subscribed to and return an `IDisposable` object for unsubscribing from the `Reactable`.

Currently, the majority of the code base that uses `Reactable` subscriptions dispose of the subscription in the dispose call of the class instead of the `onCompleted` action implementation of the `Reactor` that is sent into the subscription.

This needs to be changed.  Refactor all of the appropriate code to call the unsubscriber `Dispose()` method in the `onCompleted` action implementation instead of the class `Dispose()` method.

**Reason:**
The requested change is the standard way to implement the Observable pattern

### Acceptance Criteria

**This issue is finished when:**
- Classes updated
    - [x] GPUBufferBase
    - [x] GLInvoker - Already done. Remove dispose() call in Dispose() method
    - [x] Renderer
    - ~~Texture~~
    - ~~Sound~~
    - ~~SoundFactory~~
    - [x] TextureCache
    - [x] SoundCache
- [x] Code documentation added if required
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
`SoundFactory` was unable to take on changes.  This is due to the issues described in issue #86

**Comment by CalvinWilkinson** [comment]
Issue closed for v1.0.0-preview.9
