### ISSUE TITLE
🚧Increase code coverage to higher levels

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#24]
### Title Updated

- [X] I have updated the title by replacing the '\<title\>' section.

### ---
Description

Increase the code coverage to higher levels.

### Acceptance Criteria

**This issue is finished when:**
1. [ ] Code documentation added if required
2. [ ] Unit tests added
3. [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [x] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by CalvinWilkinson** [comment]
Closed.  This was implemented in:
- #96
