### ISSUE TITLE
🚧Add CODEOWNERS file to the project

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#240]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add a **CODEOWNERS** file to the repository and add myself into the file.

Refer to this [link](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for more info.

### Acceptance Criteria

**This issue is finished when:**
- [x] CODEOWNERS file added to the project
  - Add this to the `.github` folder
- [x] Calvin Wilkinson added
  - This would be @CalvinWilkinson 
- [x] Kristen Wilkinson added
  - This would be @kselena 

The resulting file should be
```txt
* @CalvinWilkinson
* @kselena 
```

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
@Kshitiz-Mhto Great question.  I updated the card description.   Let me know if this is clear.

**Comment by CalvinWilkinson** [comment]
PR put on hold until branch and PR is recreated

**Comment by CalvinWilkinson** [comment]
Removed the https://github.com/KinsonDigital/Velaptor/labels/on%20hold label. New PR has been created linked with a correct associated branch.

New PR:
- #305
