### ISSUE TITLE
🚧Add name and GUID props to reactor types

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#245]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

For the `IReactor` and `Reactor` types, add 2 properties that can be used to uniquely identify the `Reactor` implementation that is being subscribed to a `Reactable`.

**Name Property:**
This property should be a `string` property named **Name**.  This property should have a getter and a setter to allow the user to give it a unique name to help identify the `Reactor` for debugging purposes.

**ID Property:**
This property should be a `GUID` property named **ID**.   This property should be readonly and the `GUID` value should be generated upon creation.  This will give a way for every single subscription to be unique.  This can also help with debugging in the future.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Add a property named **Name** of type `string` to the `IReactor` and `Reactor` types.
- [ ] Add a property named **ID** of type `GUID` to the `IReactor` and `Reactor` types.
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Closed without implementation

**Reason:**  All of the Reactable functionality has been replaced by the [Carbonate Library](https://github.com/KinsonDigital/Carbonate)
