### ISSUE TITLE
🚧Change which OpenGL errors throw exceptions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#246]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Change which **OpenGL** errors throw exceptions.

Add code to ignore the OpenGL warning about recompiling fragment shaders.
This warning should be saved as an `const int` named `API_ID_RECOMPILE_FRAGMENT_SHADER` in the `GLInvoker` class.

Add code to the `DebugCallback()` method that checks for this warning and ignores it.  
Only **OpenGL** errors should throw exceptions.

Check for errors for throwing exceptions by checking the `GLEnum.NoError` value.

If there is an error OR a warning, print the message to the console.  Print in yellow for warnings and red for errors.

### Acceptance Criteria

**This issue is finished when:**
- [x] Refactor `DebugCallback()` to only throw exceptions if the error number is not a value of `GLEnum.NoError`
- [x] Print errors(exceptions) as red to the console
- [x] Print warnings as yellow to the console
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
