### ISSUE TITLE
🚧Create system for logging errors, warnings, and events

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#247]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create a logging system for logging exceptions, errors, and events that occur throughout the system.  The system should be able to log the type of logs such as an event, exception, or warning, or info.

---

**Types of output:**
The system should also have different kinds of outputs for logging.  Such as the console, log files, etc.
The minimum should be log files in the application directory and the console.

---

**When, how, and if things are logged:**
The system should also have logging turned off by default for **release** versions but turned on by default for **debug** versions.  The various kinds of logging can be turned on and off manually by changing/adding settings and values to the settings file.

**Logging Settings:**
1. LoggingEnabled = true | false
    - This will enable or disable ALL logging with the logging system once implemented.
2. ConsoleLoggingEnabled = true | false
    - Will log errors and warnings to the console if **_true_** AND if **_LoggingEnabled = true_**
3. FileLoggingEnabled = true | false
    - Will log errors and warnings to a log file if **_true_** AND if **_LoggingEnabled = true_**
4. LogWarningsEnabled = true | false
    - Will log warnings if **_true_** AND if **_LoggingEnabled = true_**.  Will log to console and/or file if _**ConsoleLoggingEnabled**_ and/or _**FileLoggingEnabled**_ are enabled.
5. LogErrorsEnabled = true | false
    - Will log errors if **_true_** AND if **_LoggingEnabled = true_**.  Will log to console and/or file if _**ConsoleLoggingEnabled**_ and/or _**FileLoggingEnabled**_ are enabled.
6. LogEventsEnabled = true | false
    - Will log events if **_true_** AND if **_LoggingEnabled = true_**.  Will log to console and/or file if 
_**ConsoleLoggingEnabled**_ and/or _**FileLoggingEnabled**_ are enabled.
    - Events can be logged via direct logging service call or by a custom attribute on a method.
7. LogInfoEnabled = true | false
    - Will log info if **_true_** AND if **_LoggingEnabled = true_**.  Will log to console and/or file if _**ConsoleLoggingEnabled**_ and/or _**FileLoggingEnabled**_ are enabled.

### Acceptance Criteria

**This issue is finished when:**
- [x] Logging service created
  - The app settings service will be injected into the logging service
  - Checking for the app setting will be done internally with the logging methods of the logger class.  This way logic for checking log settings does not have to be written throughout the application.  The logging service will have read-only properties that hold the logging settings.
 - The logging service will be a singleton.  This means the logging settings will be loaded once and saved for the application's lifetime.
- [x] All types of logging can be turned on and off
  - [x] Logging to the console can be turned on and off
    - Logging to the console should be displayed in the console app that runs along side of the **_VelaptorTesting_** application.
  - [x] Logging to a file can be turned on and off
- Logging Of Warnings
    - [x] Will not be logged if _**LoggingEnabled**_ is off.
    - [x] Will not be logged to the console if _**ConsoleLoggingEnabled**_ is off
    - [x] Will not be logged to a file if _**FileLoggingEnabled**_ is off
    - [x] Yellow in color in the console
- Logging Of Errors
    - [x] Will not be logged if _**LoggingEnabled**_ is off.
    - [x] Will not be logged to the console if _**ConsoleLoggingEnabled**_ is off
    - [x] Will not be logged to a file if _**FileLoggingEnabled**_ is off
    - [x] Red in color in console
- Logging Of Events
    - [x] Will not be logged if _**LoggingEnabled**_ is off.
    - [x] Will not be logged to the console if _**ConsoleLoggingEnabled**_ is off
    - [x] Will not be logged to a file if _**FileLoggingEnabled**_ is off
    - [x] Cyan in color in the console
- Logging Of Info
    - [x] Can be turned on and off
    - [x] Will not be logged if _**LoggingEnabled**_ is off.
    - [x] Will not be logged to the console if _**ConsoleLoggingEnabled**_ is off
    - [x] Will not be logged to a file if _**FileLoggingEnabled**_ is off
    - [x] Gray or white in color in console
- OpenGL Logging
    - [x] Change the `GLInvoker.DebugCallback()` implementation to log warnings and errors.
- [x] Code documentation added if required
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Issue Dependencies

- #248

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
