### ISSUE TITLE
🚧Build app settings system

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#248]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Build an application settings system.  This will be used to turn on and off various application behaviors.  The system should automatically check if app settings exist.  If the application settings do not exist, the file will be auto-created and all application settings with default settings will be added to the file.

This should be set up as a service with the name `AppSettingsService` with an interface and full unit testing.

The settings will be simple key-value pairs in JSON format.
Create 2 app settings for the width and height of the application.  Refactor/add code to make use of these 2 settings.

Add a method overload to the `App` class of the method `CreateWindow()`.  This class will create an instance of the singleton app settings object and check if the settings exist. If the settings do not exist, use a default width and height of **1500 x 800**.
The default width and height should be constants in the `App` class.

Change the method used in the `Program.cs` file for the **VelaptorTesting** project to use the new `CreateWindow()` method overload.

### Acceptance Criteria

**This issue is finished when:**
- [x] The settings should be saved in JSON format
- [x] The check for file existence and creation with default settings should only be done one time upon creation of the service singleton.  This means once upon application startup.
    - If this was done every time, then that could be stress on the system by checking and loading file data.
- [x] ~The settings service should hold all of the app setting names and values as a `record` type.~
- [x] ~The settings service should have a method that returns the settings for evaluation and use by other parts of the application~
- [x] The settings service will be a singleton in the IoC container
- [x] Overload method named `CreateWindow()` added to the `App` class.
  - This method will pull the window width and height app settings for users to set the size of the application.
- [x] The app settings are set up to be used as default instead of using hard-coded values using the `CreateWindow(unit, unit)` method
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Related Work

- #247

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
The 2 items below were implemented differently.

- [x] ~The settings service should hold all of the app setting names and values as a `record` type.~
- [x] ~The settings service should have a method that returns the settings for evaluation and use by other parts of the application~

**Reason:**  It was decided to go with an array of key-value pairs using the `KeyValuePair<string, string>` struct.  This was done to keep things simple without having to create a **Model** to hold the data.  This would keep the code more flexible, increase performance, and would leave the system up for easier upgrades later if need be without as much code change.
