### ISSUE TITLE
🚧Project Item - Setup badges for README for preview and production releases

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#25]
### Title Updated

- [X] I have updated the title by replacing the '\<title\>' section.

### ---
Description

Add the badges below to the **_README.md_** file to show the status of various things.

Refer to CASL project for reference on setup

- QA Release Badge
- Preview Release Badge
- Production Release Badge
- Code Coverage Badge
- Contributor Covenant Badge
- Nuget Badge

### Acceptance Criteria

**This issue is finished when:**

- [x] QA Release badge works correctly
- [x] Preview Release badge works correctly
- [x] Production Release badge works correctly
- [x] Code Coverage badge works correctly
- [x] Contributor Covenant badge works correctly
- [x] Nuget badge works correctly

### ToDo Items

- [x] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone

### Issue Dependencies
 - #35
