### ISSUE TITLE
🚧Increase spacing between buttons on rect scene

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#250]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

For the rectangle scene in the **_VelaptorTesting_** application, the 3 buttons on the bottom of the _**Test Rectangle Scene**_ need to have their spacing increased between the buttons so the buttons do not touch.  

The existence of buttons will probably be temporary and replaced with better controls as they are developed.  If it is easy, we could just re-invoke the code in the scene that determines the spacing upon button construction.  If we invoke that code to readjust the spacing every time any of the 3 buttons are clicked, they will automatically be readjusted every time and never render on top of each other.

![image](https://user-images.githubusercontent.com/85414302/202769248-6fe5938b-609b-41e1-a4cf-7c94ed7e58e9.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] The buttons do not overlap each other when the button's width increases

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quinnrdavis** [comment]
I'd like to try to figure this one out.
