### ISSUE TITLE
🚧Add GitHub sponsor button to Velaptor

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#251]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add a github sponsor button to the main **_Velaptor_** project page.

This can be done by adding the value below.

``` yml
github: KinsonDigital
```

### Acceptance Criteria

**This issue is finished when:**
- [ ] GitHub sponsor button added

### ToDo Items

- [X] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
