### ISSUE TITLE
🚧Make adjustments to the Project Item Issue template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#253]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Make various changes to the **project item issue template.**
The name of the file for the issue template is 👉🏼 **_project-item-issue-template.yml_**

---

### Acceptance Criteria

**This issue is finished when:**
- [x] Remove the _**\<title\>**_ section from the title text box.
![image](https://user-images.githubusercontent.com/85414302/167997989-144b2fb0-f8eb-4130-b81b-3d53b229ba49.png)
- [x] Change the text of the checkbox at the top of the template to the value below.
  - I have updated the title and left the 🚧 emoji behind.
![image](https://user-images.githubusercontent.com/85414302/167998179-4b81bff7-5c8b-4998-8e78-13760824464e.png)
- [x] Change the smaller gray text below the **Description** section label to the result below
![image](https://user-images.githubusercontent.com/85414302/168318661-54cc91d7-6cfe-4b60-9876-eb696a0e4e58.png)
- [x] Make changes below to the **Acceptance Criteria** section.
![image](https://user-images.githubusercontent.com/85414302/167998705-294024d4-81e1-41bb-a3d8-c9ba1814d7c6.png)
- [x] Make the following changes to the **ToDo Items** section.
![image](https://user-images.githubusercontent.com/85414302/168001869-1749e242-560d-459c-8d99-655b9182b2a7.png)
- [x] Fix spelling error in and add text in the **Issue Dependencies** section.
![image](https://user-images.githubusercontent.com/85414302/168002391-332da52a-0c91-4086-9a58-3dde17ee543d.png)
- [x] Change the descriptive text in the **Related Work** section to the value below.
![image](https://user-images.githubusercontent.com/85414302/168004423-1620ed02-bbf4-4156-a330-0e067a0cc6f1.png)

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Related Work

- KinsonDigital/issues-repo#9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
