### ISSUE TITLE
🚧Create issue template for performing releases

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#254]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create an issue template for performing releases.

Each release will have this release issue created.  It will be used to perform todo items for the release such as running unit tests to making sure release announcements are performed.

### Acceptance Criteria

**This issue is finished when:**
- [x] Create release todo issue template
- [x] Issue template file name will be **_release-todo-issue-template.yml_**

### ToDo Items

- [X] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
PR Approved and ready for release v1.0.0-preview.9
