### ISSUE TITLE
🚀Release v1.0.0-preview.9 ToDo

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#256]
### Items Released

- #254
- #251
- #246
- #243
- #239
- #235
- #230
- #228
- #227
- #226
- #224
- #220
- #210
- #209

### Choose the type of release.

Preview Release

### Perform Release To Do List

- [x] QA Testing finished and all tests pass.
- [x] Branch used for release has been checked out locally and all unit tests have passed.
- [x] Version in project file updated.  (Update <Version/> and <FileVersion/> tags)
- [x] Release notes created and added to the correct release branch.
- [x] The release displayed in [GitHub Releases](https://github.com/KinsonDigital/Velaptor/releases) has been verified to be correct.

### Post Release To Do List

- [x] Update issue title by replacing the '**_\<release number here\>_**' with the release number.
- [x] Correct **_release_** label added to the issue.
- [x] Announcement of release on [Twitter](https://twitter.com/KDCoder) verified. (Announcement should be performed automatically with the release)
- [x] Performed announcement on [Ko-Fi](https://ko-fi.com/kinsondigital) website.
- [x] Performed announcement on [GitHub Discussions Board.](https://github.com/KinsonDigital/Velaptor/discussions/133)
- [x] Performed announcement on Discord channel.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Release Steps Complete
