### ISSUE TITLE
🚧Make changes to issue and PR Templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#257]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

## Description

Remove the release type dropdown from the release todo issue template.
The file is named **_release-todo-issue-template.yml_**

Make changes to the following release PR templates below:
Remove items in PR templates in red
- **_preview-release-pr.md_**
- **_production-release-pr.md_**

---

## **Section To Remove From Release ToDo Issue Template**
![image](https://user-images.githubusercontent.com/85414302/167510088-1bdede5e-0a16-4dae-8fad-e91304ac99b6.png)

---

## **Things To Remove From PR Templates**
![image](https://user-images.githubusercontent.com/85414302/167513155-3cbf6e8f-dc5f-4d77-a632-a9c988d19324.png)

---

## **Move checkbox**
![image](https://user-images.githubusercontent.com/85414302/167562624-8c984429-5c73-4fee-b7ff-6b315b8f65df.png)

## Acceptance Criteria

**This issue is finished when:**
- [ ] Dropdown removed
- [ ] Add **Release To Do Item** checkbox item to issue template for creating a release PR
    - Explain that one of the PR templates needs to be used.  Explain each PR template and what it is for.  Release PR templates are **_preview-release-pr.md_** and **_production-release-pr.md_**
    - Insert item at location in picture below
    ![image](https://user-images.githubusercontent.com/85414302/167511728-c2679ae1-676b-4f02-abd2-df437dc9baf6.png)
    - Add text to the checkbox items explaining the adding of release notes and updating the version number in the project file AFTER the PR has been created.  The PR should capture those changes.
    - Add todo item that this release checklist issue needs to be linked to the release PR
- [ ] Move the checkbox about checking if the release is displayed in the GitHub Releases section
- [ ] Add an item to the **Post Release ToDo List** to check if the release to GitHub release was successful
- [ ] Add an item to the **Post Release ToDo List** to check if the release to Nuget.org release was successful

## ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Closed.  Duplicate issue
