### ISSUE TITLE
🚧Change how PR status checks are ran

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#259]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Currently, the status check workflows are ran based on the `pull_request > branches` filter setup in the YAML of the workflows.

This means if the branch protection rules have no status checks added, they will run anyways as long as the branch matches the branch filter.  Basically, status check workflows can be executed via the branch filters in the **workflow itself**, or in the **branch protection rule settings**.

This needs to change.  The reason is because currently, if a status check needs to be removed or added, a change to the code has to be done.  It would be much easier and less time consuming if we utilized the **branch protection rules** to do this instead of the branch filters in the workflow running off the workflows.

Remove the branch filters for all status check workflows.  Once this is done, add the proper status checks to the proper branches in the branch protection rules system instead.

### Acceptance Criteria

**This issue is finished when:**
- Status check workflows updated.
    - [x] build-status-check.yml
    - [x] feature-pr-branches-status-check.yml
    - [x] tag-does-not-exist-status-check.yml
    - [x] unit-testing-status-check.yml
    - [x] validate-preview-release-branches-status-check.yml
    - [x] validate-prod-release-branches-status-check.yml
    - [x] version-status-check.yml

### ToDo Items

- [X] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Related Work

- KinsonDigital/issues-repo#9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
