### ISSUE TITLE
🚧Get the same nuget package to work on both windows and linux

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#26]
### Title Updated

- [X] I have updated the title by replacing the '\<title\>' section.

### ---
Description

Look into making sure that the current nuget package in nuget.org can be consumed and used properly on both windows and linux when developing with it.  The goal is to have one nuget package for all platforms.

### Acceptance Criteria

**This issue is finished when:**
1. [ ] Nuget package consumed by a project on both windows and linux works

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [x] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Groomed
