### ISSUE TITLE
🚧Make changes to Release ToDo Issue Template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#260]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description

Make various changes to the _**Release ToDo Issue Template**_.
The name of the file is `release-todo-issue-template.yml`

---

### **Refer to image below for more info:**
![image](https://user-images.githubusercontent.com/85414302/167862967-a161f88a-77e1-4618-856b-a0bc84507681.png)

### Acceptance Criteria

**This issue is finished when:**
- Release ToDo Issue Template updated
    - [x] The **_Items Released_** section title changed to **_Issues Released_**
    - [x] Add a checkbox item to the _**Perform Release To Do List**_ to add all of the appropriate labels for the issues being released.  Add the table below to make this happen.
        - [x] The text of the item should be 👉🏼 "Add the appropriate labels to this issue template based on the issues being released"
        - [x] Add a default collapsed region for the extra info below.  This is done by using the following HTML
          ``` html
            <details closed><summary>Expand for more info</summary>
            <!--Make sure to have an extra space here before the content for it to render correctly-->
            </details>
          ```
        - Use this link 👉🏼 https://github.com/KinsonDigital/issues-repo/labels/invalid for referencing the label in the second column

          | Kind of Change         | Tag Type |
          |------------------------|-----------|
          | Bug Fix                       |               |
          | Breaking Change       |                |
          | Enhancement             |               |
          | Workflow Changes     |               |
          | Code Doc Changes     |               |
          | Product Doc Changes |               |
    - [x] Add an expandable section below the checkbox shown below.  This will have more info about where to add the different kinds of release notes in the solution.
![image](https://user-images.githubusercontent.com/85414302/167862774-680264ad-f286-49d4-b732-c7baf82034d8.png)
    - [x] The **_Choose the type of release_** drop down is removed.
        - This is being removed because the release label will be used instead
    - [x] Change the text for the _**passing unit tests requirement**_ item to the follow text and add extra information.
      - Change text to 👉🏼 "All unit tests have been ran and have passed locally.  (Check out the appropriate release branch before running tests)"
      Example below:
        ```
          - [ ] All unit tests have been ran and have passed locally.  (Check out the appropriate release branch before running tests)
              - Reason for this check. 
                - This is required because unit tests might pass locally but not in the CI environment during the status check process or vise-versa.
                - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
                - This does not mean that the tests pass in both the local and CI environment.
                - Status checks run for this pull request when merging into the **_release/v\*.\*.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.
        ```

    - [x] Add the following todo item to the **_Perform Release To Do List_** list
![image](https://user-images.githubusercontent.com/85414302/167836743-244277ca-3ca3-4fed-b3f9-a15fe20e872d.png)
    - [x] Add XML code block directly below the _**Perform Release To Do List**_ item about updating the version in the project file
      ``` xml
      <!--Do this for preview releases-->
      <Version>1.2.3-preview.4</Version>
      <FileVersion>1.2.3-preview.4</FileVersion>
  
      <!--Do this for regular releases-->
      <Version>1.2.3</Version>
      <FileVersion>1.2.3</FileVersion>
      ```
    - [x] Move the item shown below from the _**Perform Release To Do List**_ to the _**Post Release To Do List**_
![image](https://user-images.githubusercontent.com/85414302/167837873-12b0f5ad-908b-43f6-8525-79498c60b9a9.png)
    - [x] Add checkbox item to the _**Post Release To Do List**_ to check for the success of the Nuget.org release.
        - Make sure to have a link to the nuget page that shows the nuget

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Related Work

- KinsonDigital/issues-repo#9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
