### ISSUE TITLE
🚧Make adjustments to Feature PR templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#261]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description

Make various adjustments to the **Feature** and **Preview Feature** PR templates to cleanup the process and the PR card itself.

**The file names are:**
1. `feature-pr.md`
2. `preview-feature-pr.md`

### Acceptance Criteria

**This issue is finished when:**
- [x] Feature PR template updated
- [x] Preview Feature PR template updated

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Issue Dependencies

- #219 

### Related Work

- KinsonDigital/issues-repo#9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
