### ISSUE TITLE
🚧Setup project Social Preview

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#262]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description

Do some research on setting up a project's **Social Preview** and set it up

**Refer to image below:**
![image](https://user-images.githubusercontent.com/85414302/167882641-750c4ce9-8ee1-410d-bbf0-d8afba31826e.png)

**Information collected**
[Rushk-TextFonts.net-53.zip](https://github.com/KinsonDigital/Velaptor/files/9505684/Rushk-TextFonts.net-53.zip)

**Use This Image:**
![project-social-preview](https://user-images.githubusercontent.com/85414302/209686576-8e93e5f0-6a0a-4eb2-bf2c-77942b25c23f.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] Social preview setup.
- [x] Once figured out, create issue for **CASL** todo the same thing

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
@kselena Need to do some research for ideas on how we want the preview image to look

**Comment by kselena** [comment]
@CalvinWilkinson I don't have access to Settings in Velaptor.  I have ideas on how we want the preview image to look.

**Comment by kselena** [comment]
Discussed with @CalvinWilkinson and issue is completed and closed with no PR required.
