### ISSUE TITLE
🚧Start process of implementing Fluent Assertions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#264]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description

Start the process of implementing the fluent assertions library.

The goal here is to at a minimum, convert at least 1 unit test file to use fluent assertions for every issue that is done.
This will push toward getting fluent assertions throughout all of the unit tests at a decent pace.

### Acceptance Criteria

**This issue is finished when:**
- [x] Add the NuGet package **FluentAssertions** to unit test project
- [x] ~Refactor the files below:~
  - [x] ~`DisposeTexturesReactableTests.cs` - 34  lines~
  - [x] ~`KeyboardStateReactableTests.cs` - 33 lines~
  - [x] ~`MouseButtonReactableTests.cs` - 36  lines~
  - [x] ~`MousePositionReactableTests.cs` - 35 lines~
  - [x] ~`MouseWheelReactableTests.cs` - 36 lines~
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
No refactoring required.  The following test files not need any use of **FluentAssertions**

  - [x] ~`DisposeTexturesReactableTests.cs` - 34  lines~
  - [x] ~`KeyboardStateReactableTests.cs` - 33 lines~
  - [x] ~`MouseButtonReactableTests.cs` - 36  lines~
  - [x] ~`MousePositionReactableTests.cs` - 35 lines~
  - [x] ~`MouseWheelReactableTests.cs` - 36 lines~
