### ISSUE TITLE
🚧Figure out how to get a custom domain name for Velaptor

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#265]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description

Do some research to figure out how to secure a domain for the doc site for **Velaptor**.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Find best place to get domain from (godaddy.com maybe?)
- [ ] Get cost based on best place to get it
- [ ] Make changes to the doc site to use the new domain and get it working

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Issue Dependencies

- #266 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
