### ISSUE TITLE
🚧Create and setup doc site for Velaptor

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#266]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description

Create and setup everything required for **Conceptual** and **API** documentation for the **Velaptor** project.
This will use the static documentation website generator tool called DocFX.

**Resources:**
- [Peaceiris GitHub Action](https://github.com/peaceiris/actions-gh-pages)
- [DocFX](https://dotnet.github.io/docfx/)
- [Sample DocFX Project](https://github.com/KinsonDigital/DocFXSample)
- Helpful Articles:
  - [Project Docs With DocFX](https://www.jamescroft.co.uk/building-net-project-docs-with-docfx-on-github-pages/)
  - [DocFX GitHub Actions](https://tehgm.net/blog/docfx-github-actions/)

### Acceptance Criteria

**This issue is finished when:**

**Doc Repo Setup:**
- [x] Need to find out how to deploy different versions of the documention
- [x] Create a public repository and name it **VelaptorDocs**
- [x] Set the repo up as a GitHub Pages repository
- [x] Set the doc production branch to **master**
- [x] Set the folder to the value **/docs**
- [x] For the **GitHub Pages** action, use the repo secret named **REPO_ACCESS** for the token to allow the action to push the docs to the doc repo.
  - This will go into the new workflow that publishes the docs in the **Velaptor** project.

**Other:**
- [x] Setup readme explaining that this is the documentation for the Velaptor project with a link to the project as well as the URL to the website to view the documentation. Goto other projects as a reference such as SimpleInjector or Six Labors to see how they do it.
- [x] Setup **npm-watch** to help automate doc site reload when content changes.
  - This will help when developing the articles section side of the documentation and speed up development.
  - Refer to the first article in the resources section above for help on setup
- [x] Use the [DocFX Template](https://github.com/steffen-wilke/darkfx) named **DarkFX** for the sites looks
- ~Setup PDF creation~
  - [x] ~Add **wkhtmltopdf** setup to the workflow for PDF documentation creation~
  - [x] ~Make sure that the **_docfx.json_** file contains the pdf creation workaround below~
    - ~This is the entire pdf object for creating pdf versions of the documentation.  This currently is not in the sample project.  Make sure that the **noStdin: true** is included in the object to avoid errors in PDF production~
      ```diff
      "pdf": {
      +    "noStdin": true,
          "content": [
            {
              "files": [
                "api/**.yml",
                "api-vb/**.yml"
              ],
              "exclude": [
                "**/toc.yml",
                "**/toc.md"
              ]
            },
            {
              "files": [
                "articles/**.md",
                "articles/**/toc.yml",
                "toc.yml",
                "*.md",
                "pdf/*"
              ],
              "exclude": [
                "**/bin/**",
                "**/obj/**",
                "_site_pdf/**",
                "**/toc.yml",
                "**/toc.md"
              ]
            },
            {
              "files": "pdf/toc.yml"
            }
          ],
          "resource": [
            {
              "files": [
                "images/**"
              ],
              "exclude": [
                "**/bin/**",
                "**/obj/**",
                "_site_pdf/**"
              ]
            }
          ],
          "overwrite": [
            {
              "files": [
                "apidoc/**.md"
              ],
              "exclude": [
                "**/bin/**",
                "**/obj/**",
                "_site_pdf/**"
              ]
            }
          ],
          "wkhtmltopdf": {
            "additionalArguments": "--enable-local-file-access"
          },
          "dest": "_site_pdf"
        }
      ```
- [x] Add link to the documentation website to the body of the release (production only)
- [x] Add PDF documentation file to assets

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Related Work

- #100 
- #265 
- KinsonDigital/issues-repo#9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Put on https://github.com/KinsonDigital/Velaptor/labels/on%20hold due to issues with [docfx](https://dotnet.github.io/docfx/).

The issue below has been opened to hopefully get a fix/info about what is going on.

- dotnet/docfx#8143

**Comment by CalvinWilkinson** [comment]
**Quick Update**

Conversation between some people on issue #8136 recommended this [workaround](https://github.com/dotnet/docfx/issues/8136#issuecomment-1219512721).

**Comment by CalvinWilkinson** [comment]
There has been an update related to issue dotnet/docfx#8135

It was recently released with [v2.59.4](https://github.com/dotnet/docfx/releases/tag/v2.59.4)

**Comment by CalvinWilkinson** [comment]
### Further investigation:

This card was picked back up to see what the status was of DocFx.  It was noticed that there was a version updated from _**v2.69.3**_ to _**v2.69.4**_.  An upgrade was made and multi-version API doc creation was attempted again.

After a full day of researching and trying different things out, we got close to a solution but the end result would require some extra tooling to deal with some of the shortcomings.  Due to the additional steps, it was decided that the work was not worth the effort as of right now.  Version _**v1.0.0**_ is not even out yet and DocFx version _**v3.0.0**_ is currently in beta which changes everything and also comes with the multi-version API documentation.  

This issue has been put off until the release of DocFx _**v3.0.0**_.

Attached below is a zip file of the simple test project that I was able to get close to working.
[docfx-playground.zip](https://github.com/KinsonDigital/Velaptor/files/9828335/docfx-playground.zip)

---

The end result of the research was able to get multiple versions on the left side with each item being alike to the specific API version documentation.  The current setup has version _**v1.0.0**_ and _**v2.0.0**_.   The problem is that the doc URLs for _**v2.0.0**_ all point to the docs for version _**v1.0.0**_.  The produced HTML for some reason contains URLs that link to the _**v1.0.0**_ documentation instead of the _**v2.0.0**_ documentation.  The C# console app added was the extra tooling that was going to search for and update the URL.

**Comment by CalvinWilkinson** [comment]
This issue will stay on hold status until DocFx version _**v3.0.0**_ production or preview is available.

**Comment by CalvinWilkinson** [comment]
> **Note** It was decided to not build a PDF file version of the documentation due to the low need.  This will be revisited later.
> Another reason is because eventually when **docfx v3.+** is released, I am sure that things will be different.
