### ISSUE TITLE
🚧Create new research issue template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#267]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_\<title\>_**' section.

### Description

Create a custom issue template that is for the purpose of doing research.

### Acceptance Criteria

**This issue is finished when:**
- [x] Research label auto added when issue is created
- [x] Text area for describing what to research
- [x] Text area to put research results
- [x] Set the checkbox at the very top the value below:
``` diff
- I have updated the title by replacing the <title> section
+ I have updated the title and left the 🔬 emoji behind.
```

- [x] The emoji used in the title should be 🔬
- [x] Set the text under the **Description** section label to the result below
``` diff
- A description of feature/change in the user's perspective
+ A description of the research to perform.
```
- [x] Checkbox in acceptance criteria that states:
  - Research complete and issues created if required
- [x] Do not need to have a checkbox in the **ToDo Items** section that asks that a draft pull request is created
  - This is because research items are not meant to make ANY changes to ANYTHING in the repo at all.  They are for research only

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
