### ISSUE TITLE
🚧Project Item - Remove deploy branches from environments

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#27]
### Title Updated

- [X] I have updated the title by replacing the '\<title\>' section.

### ---
Description

Remove the _**feature/\***_ deployment branches from the **preview** and **production** environments.

### Acceptance Criteria

**This issue is finished when:**
1. [ ] Environment branch protection rules removed.

### ToDo Items

- [ ] ~~Draft pull request created and linked to this issue~~
- [x] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone
- [ ] ~~Unit tests have been written and/or adjusted for code additions or changes~~
- [ ] ~~All unit tests pass~~
