### ISSUE TITLE
🚧Create ignore paths workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#278]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, when merging changes to files in a PR that does not require a build, the current status checks disallow the
PR from being merged.  This forces an admin to merge the changes and is not great.

Create a workflow that allows the PR to be merged by always passing the status check status.  This workflow will have a paths filter that is only for the paths that do not require build changes.

To figure out how to accomplish this, refer to the [Troubleshooting Status Checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks) documentation.
Scroll down just a little bit to see the docs on how this can be done.

It simply requires a workflow with the exact same name with a different path filter that always passes.

Use the following list of paths that do not require builds:
- ".github/**"
- 'Documentation/**'
- '.editorconfig'
- '*.runsettings'
- '.gitattributes'
- '.gitignore'
- '*.md'
- '*.yml'
- '.vscode/**'
- '*.sln'

### Acceptance Criteria

**This issue is finished when:**
- [ ] New workflows created and setup to non build checks.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed.  This was implemented in issue below
- #259
