### ISSUE TITLE
🚧Project Item - Update version of vget actions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#28]
### Title Updated

- [X] I have updated the title by replacing the '\<title\>' section.

### ---
Description

Update the version of the _**vget**_ actions in the various workflows of the project and take advantage of the new **does-not-contain** input.

### Acceptance Criteria

**This issue is finished when:**
1. [ ] **Build_And_Release_Testing_App** job for _**qa-release**_ workflow updated to new action version and new input used
2. [ ] **Library_Build_And_Test** job for _**preview-release**_ workflow updated to new action version and new input used
3. [ ] **Build_And_Release_Testing_App** job for _**preview-release**_ workflow updated to new action version and new input used
4. [ ] **Library_Build_And_Test** job for _**production-release**_ workflow updated to new action version and new input used
5. [ ] **Build_And_Release_Testing_App** job for _**production-release**_ workflow updated to new action version and new input used

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Issue Dependencies

KinsonDigital/vget#11

**Comment by CalvinWilkinson** [comment]
**Close Reason:**
The **vget** GitHub action has been replaced with a more robust a feature rich action named **VersionValidator**.  **VersionValidator** will be the GitHub action to use.
