### ISSUE TITLE
🚧Update runsettings file

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#280]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the `Velaptor.runsettings` file by fixing one of the exclude items.

Currently it is excluding an old name of a library that does not exist anymore and it should be excluding the entire _**VelapatorTesting**_ app code base.

Need to run this in _**Visual Studio**_ to make sure that the runsettings is correctly ignoring the **VelaptorTesting** code base.

**Refer to image below:**
![image](https://user-images.githubusercontent.com/85414302/169493839-111f14c7-16df-4417-9318-d2b634b05e0b.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] The value `VelaptorTesting.dll` added to exclusions
- [x] The value `VelaptorTesting.exe` added to exclusions
- [x] All unit tests pass

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
⚠️NOTE: Could not test this out.  This change is for the purpose of ignoring code coverage results.  Code coverage is only available in Visual Studio Enterprise edition which costs money.  Due to not having this edition anymore, I could not test this.  
I moved to JetBrains Rider and this is done differently in this IDE.
