### ISSUE TITLE
🚧Update status check workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#281]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the status check workflows so they do not run because of the YAML settings of the workflow itself.  They will be executed via repo branch filter settings instead.

Remove the YAML lines for all status check workflows below
- `pull_request:`
- `types:`

Update the build and unit testing status check workflows to use [workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions) instead of manually writing the build config variable to a file for the next steps to use.

**Update Workflow Event:**
``` yml
on:
  workflow_dispatch:
  pull_request: 👈🏼 Remove this
    types: [ synchronize ]👈🏼 Remove this
    paths-ignore:
      - ".github/**"
      - 'Documentation/**'
      - '.editorconfig'
      - '*.runsettings'
      - '.gitattributes'
      - '.gitignore'
      - '*.md'
      - '*.yml'
      - '.vscode/**'
      - '*.sln'
      - '*.csproj' 👈🏼 Remove this
```

**Refer To Below:**
``` yml
- name: Set Build Config Variable #👈🏼 Use the name 'Get Build Config' instead
  id: get-build-config # 👈🏼Add this id
  run: |
    # If the destination branch that the pull request is merging into is master, do a release build
    if ( "${{ github.base_ref }}" -eq "master") {
        # echo "BUILD_CONFIG=Release" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        # Don't use this anymore👆🏼

        # Use this workflow command instead
        Write-Host "::set-output name=build-config::Release" # 👈🏼Do this instead
    } else { # Any other branch than master, do a debug build
        # echo "BUILD_CONFIG=Debug" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        # Don't use this anymore👆🏼

        # Use this workflow command instead
        Write-Host "::set-output name=build-config::Debug" # 👈🏼Do this instead
    }
```

### Acceptance Criteria

**This issue is finished when:**
- Status check workflows updated
  - [ ] Build status check workflow pull request trigger lines removed
  - [ ] Build status check workflow now uses workflow commands
  - [ ] Unit testing status check workflow pull request trigger lines removed
  - [ ] Unit testing status check workflow now uses workflow commands

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without changes

**Reason:** This will be implemented by the issue below:

- #342
