### ISSUE TITLE
🚧Fix spelling error in issue template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#282]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix a spelling issue in the `bug-issue-template.yml` issue template.

**Refer to image below:**
![image](https://user-images.githubusercontent.com/85414302/170272698-63aeb93e-0293-4b99-98f9-0e52c61f2882.png)

### Acceptance Criteria

**This issue is finished when:**
- [ ] Spelling error fixed

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
I am not sure what you mean by "this will provide a space while previewing it."

This is a YAML file.  This does not get previewed.  YAML is not a markup language like HTML or Markdown.

As for the labels YAML key value, it is an array of items.
``` yml
title: "🐛"
labels: [bug, TRIAGE] 👈🏼 List of items delimited by a comma
body:
```

The item `bug` is the first item and `TRIAGE` is the second item.  You can tell it is a list of items because each item/word is separated by a comma and is wrapped in square brackets.  Similar to an array in JavaScript.

As for what the `labels` key does, it adds the list of labels to the issue upon creation automatically.
This means that when you "previewing the template", you will not see any labels added yet.  They will not be added until you "Submit new issue" button at the bottom.

Also, no spaces required.  I have never needed to use spaces but I purposely avoid them.  If you were to use spaces, you could probably just wrap the label values in single quotes.  But I am not 100% sure if that would work. Either way, no need to use spaces so don't use quotes around the label names.

I hope this clears things up.

As for the list of labels, if you don't mind, can you change the triage label from `TRIAGE` to `⚕️NEEDS TRIAGE`.

This should result in the YAML below:
``` yml
name: 🐛 Bug
description: File a bug
title: "🐛"
labels: [bug, ⚕️NEEDS TRIAGE]
body:
- type: checkboxes
```

**Comment by CalvinWilkinson** [comment]
@Kshitiz-Mhto As for the branch, please make sure to use the branch naming convention per project documentation.
You can find the documentation [here](https://github.com/KinsonDigital/Velaptor/blob/preview/v1.0.0-preview.10/Documentation/Branching.md).

If you need assistance or have any other questions, don't hesitate to ask.  😀

**Comment by CalvinWilkinson** [comment]
@Kshitiz-Mhto  Let me know if you want to pick this up.  If so I will assign it to you.

**Comment by CalvinWilkinson** [comment]
> > @Kshitiz-Mhto Let me know if you want to pick this up. If so I will assign it to you.
> 
> love it 👍

Your assigned!!

**Comment by CalvinWilkinson** [comment]
@Kshitiz-Mhto Just a quick heads up.  I am in the middle of updating the **Branching Documentation** for **Velaptor** in reguards to **preview feature branches**.  

Your branch name should follow this syntax:
preview/feature/\<id\>-\<description\>

**Comment by KinsonDigitalAdmin** [comment]
@Kshitiz-Mhto Thank you so much for your help!!

Just quick FYI, for future issues, please make sure to go back to the issue and checkoff any **Acceptance Criteria** items or to do items when you're complete.  That will help let the maintainers know that you have completed everything that is required.

Refer to image below.  I went ahead and checked them off.
![image](https://user-images.githubusercontent.com/105235056/178848262-494842fb-8f6d-4bb9-b4d4-8f4d9cf5f7ed.png)
