### ISSUE TITLE
🚧Edit badges in README

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#283]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the following badges to the README file.
- Passing tests
- Latest Releases
- Type of software license
- Open Pull Requests
- Custom badge with query to show total good first issues

Refer to [shields io](https://shields.io/category/issue-tracking) for more info.

The image below is an example of these badges.  These were found in a github action on the GitHub action marketplace.
![image](https://user-images.githubusercontent.com/85414302/170275395-84b1c6b3-dda8-49e2-ad4b-53706736bb08.png)

Refer to the [github action here](https://github.com/peaceiris/actions-gh-pages/blob/main/README.md) for more details.

Below is the markdown used in that project to get the badges above
``` md
[![license](https://img.shields.io/github/license/peaceiris/actions-gh-pages.svg)](https://github.com/peaceiris/actions-gh-pages/blob/main/LICENSE)

[![release](https://img.shields.io/github/release/peaceiris/actions-gh-pages.svg)](https://github.com/peaceiris/actions-gh-pages/releases/latest)

![Test](https://github.com/peaceiris/actions-gh-pages/workflows/Test/badge.svg?branch=main&event=push)
```

One problem is how the release one might work.  The latest might currently be preview if a preview release is currently being used.
I would rather always show the latest production release, not preview release.  Sometimes the latest release might be a qa release.
This is not ideal.

If there is no flexibility on filtering out the kind releases to show in the badge, this means something will have to be automated somehow to make this work. I do not think there is an easy way to do this.  If this is the case, then we could have a badge for every type of release.  Like the list below

---

### Release Badge Types:
1. production release
2. preview release

### Acceptance Criteria

**This issue is finished when:**
- [x] License type badge added
- [x] open PR badge added
- [x] passing unit tests
- [x] latest releases
  - This will depend.  Might have to do something custom or not do at all.
- [x] QA Release badge removed

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Put on https://github.com/KinsonDigital/Velaptor/labels/on%20hold until I can get some opinions on what badges I should add and how they should be laid out.

**Comment by CalvinWilkinson** [comment]
Taken off of https://github.com/KinsonDigital/Velaptor/labels/on%20hold.
A decision was made on how to layout the badges and which ones to keep.
