### ISSUE TITLE
🚧Make changes to bug issue template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#284]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description
Make changes to the bug issue template file.

Make these changes below:
![image](https://user-images.githubusercontent.com/85414302/171297153-7f3b0026-ab39-4ffa-9d3d-584e9145d1b6.png)

and below:
![image](https://user-images.githubusercontent.com/85414302/171297726-93a4e17f-b025-44a8-9b9d-ad4dc92a93ff.png)

### Acceptance Criteria

**This issue is finished when:**
- [ ] All issues fixed in this template
- [ ] Update OS description to value below:
     - Which operating system(s) have you encountered the issue? (Please select AT LEAST one)
- [ ] Set OS Version Label to value below:
  - Operating System Version
- [ ] Update Operating System Version description to value below:
  - If known, please enter the OS version 
- [ ] Create issue to fix template for Githubdata project
- [ ] Create issue to fix template for versionminer project
- [ ] Create issue to fix template for c#lib templaterepo project
- [ ] Create issue to fix template for SWCM project
- [ ] Create issue to fix template for KDActionUtils project
- [ ] Create issue to fix template for branchvalidator project
- [ ] Create issue to fix template for githubrelasechecker project
- [ ] Create issue to fix template for CASL (check to see if issue exists) project
- [ ] Create issue to fix template for versionvalidator project
- [ ] Create issue to fix template for issueScanner project
- [ ] Create issue to fix template for Tagverifier project

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Related Work

- KinsonDigital/issues-repo#9
- KinsonDigital/CASL#80

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Actually, I apologize but I am in the middle of doing an entire administrative cleanup project for the entire organization. This is not a good choice for one to pick up.  Let me go through the repo and label some more good first issues if you don't mind.

**Comment by kselena** [comment]
Issue closed
Reason: Implemented in issue below
- #312
