### ISSUE TITLE
🚧Refactor code docs

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#285]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Make a simple code documentation change for grammar related purposes.

Refactor the `EnsureThat` class code docs as suggested below
``` diff
/// <summary>
- /// Performs analysis on particular values to ensure that a value meets a criteria,
+ /// Performs analysis on particular values to ensure that they meet a criteria,
- /// then invokes behavior based on result.
+ /// then invokes behavior based on a result.
/// </summary>
internal static class EnsureThat
```

### Acceptance Criteria

**This issue is finished when:**
- [x] Class level code docs refactored

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by SyedMSawaid** [comment]
Can you assign me this?

**Comment by SyedMSawaid** [comment]
@CalvinWilkinson  kindly remove me from this issue.
