### ISSUE TITLE
🚧Adjust code naming style setup

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#286]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Adjust the naming style for fields to enforce that they are not aloud to start with an underscore.

This is an easy fix.  You just have to setup a JetBrains Rider code style change for the **team-shared** settings and commit to the repo and then add a **StyleCop** rule to enforce that this is not aloud to the solution level **.editorconfig** file.

**References:**
StyleCop [Rule SA1309](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1309.md)

---

**JetBrains Rider Setting:**
![Image](https://user-images.githubusercontent.com/85414302/171023149-dbc3de98-d9c2-47de-8b73-63534eb3ac44.png)

---

**Solution Level Editor Config Setting:**
Add this to the bottom of the file

``` editorconfig
# SA1309: A field name in C# begins with an underscore
dotnet_diagnostic.SA1309.severity = warning
```

### Acceptance Criteria

**This issue is finished when:**
- [x] JetBrains rider setting setup correctly for **team-shared** settings
- [x] StyleCop rule added to solution level editor config file
- [x] Update the GitHub GIST solution level editor config
- [x] Fix issue with csharp style below
  ``` diff
  - csharp_style_var_elsewhere = false:false
  + csharp_style_var_elsewhere = false:none 
  ```

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
