### ISSUE TITLE
🚧Project Item - Remove SDL2 binary being packaged with nuget and publish

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#29]
### Title Updated

- [X] I have updated the title by replacing the '\<title\>' section.

### ---
Description

When building a nuget package or with the `dotnet publish` command, the _**SDL2.dll**_ library is being included.  This library is not needed and needs to be removed.

### Acceptance Criteria

**This issue is finished when:**
1. [x] ~_**SDL2.dll**_ library removed~
2. [x] ~Unit tests added~
3. [x] ~All unit tests pass~

### ToDo Items

- [x] ~Draft pull request created and linked to this issue~
- [X] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] ~Unit tests have been written and/or adjusted for code additions or changes~
- [x] ~All unit tests pass~

**Comment by CalvinWilkinson** [comment]
Upon investigation, the SDL2 library comes from SILK.NET and was not manually added or put into use in the project.  The library is only contained in the _**runtime**_ folders and is also not even used.
