### ISSUE TITLE
🚧Fix video issue with README

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#292]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

In the README file, there is a demo video.  Currently this is a link to some github user content.  It seems to not be reliable.
There is also an **.mp4** video in the repo that was intended to be used in the README, but it does not work when using a direct repo path vs a full URL.

Fix this by converting the video to a GIF and link to the GIF using markdown.  Once this is working, remove the **.mp4** version of the video.

### Acceptance Criteria

**This issue is finished when:**
- [ ] GIF created from the **.mp4** video and added to the repository
- [ ] README uses markdown to display the GIF instead of pointing to GitHub user content.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
