### ISSUE TITLE
🚧Update nuget packages

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#293]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the following nuget packages to the latest version.  

Verify that the latest version for each package below is the latest version.  If the version is greater than the version mentioned below, contact a project maintainer to verify if the later version can be used instead of the version mentioned below.

WARNING!! Do not update any other packages then what is in the list below.

Packages:
- coverlet.msbuild
- Microsoft.NET.Test.Sdk
- Moq
- NVorbis
- SixLabors.ImageSharp
- SILK.NET

### Acceptance Criteria

**This issue is finished when:**
- [x] The packages below are updated
  - [x] coverlet.msbuild updated
  - [x] Microsoft.NET.Test.Sdk updated 
  - [x] Moq updated
  - [x] NVorbis updated
  - [x] SixLabors.ImageSharp updated
  - [x] SILK.NET updated
- [x] Unit tests added
- [x] All unit tests pass

- [x] Heavy testing must be done to verify that NOTHING is breaking.  This includes all of the unit tests which is all automatic anyways, but more important, manual testing using the **VelaptorTesting** project.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
@Kshitiz-Mhto Here is another issue you can do for me if your interested.

I don't know what your experience is with the world of dotnet and nuget packages, but no coding is required here.  It would expose you to using Visual Studio if you are not familiar with it already and updating packages.   😃

**Comment by CalvinWilkinson** [comment]
The current version for each package compared to the version I want does indeed match what I am seeing in your nuget manager.

I just [JetBrains Rider](https://www.jetbrains.com/rider/) so of course my GUI looks different than yours.  I also use Visual Studio.  To be honest I have not used the nuget manager GUI in **VSCode** before. It is nice to know that exists!!

What I am seeing is good.  As long as the version your setting them to are exactly described as above, we are fine.  😀
I will be able to see every single change no problem.  You will not break anything so no worries.  If I find any issues, we will collaborate on it to make it right.  

Yay open source!! 🥳

This is what the Nuget Package UI looks like in [Visual Studio](https://visualstudio.microsoft.com/)
![image](https://user-images.githubusercontent.com/85414302/179215227-03a23ef5-217a-4acb-a58c-ed4b3822af29.png)

This is what it looks like int Rider
![image](https://user-images.githubusercontent.com/85414302/179216640-8bcc4b6d-df0e-4638-bb16-0680bdd943c9.png)

**Comment by CalvinWilkinson** [comment]
Also, you said you were new to open source.  I am willing to spend some time with you to help you out if your interested.
You can join my discord server if you want so we can keep these kinds of conversations personal and out of the project.

If you have never used discord before, it is free.  Go [here](https://discord.com/download) to download it. 

Here is the join link 👉🏼 [Kinson Digital Discord](https://discord.gg/qewu6fNgv7)

**Comment by CalvinWilkinson** [comment]
@Kshitiz-Mhto Actually my wife and I will test it after you make the change.  Just let me know when your change is complete and we will take care of it.  😀

**Comment by CalvinWilkinson** [comment]
@Kshitiz-Mhto Could you give me a status on this one?  I don't see a pull request.  Let me know if you still want to do this one.
As for the testing, we will take care of that.
