### ISSUE TITLE
🚧Add the release notes as text to the release

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#294]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently the release notes are added to the assets as an **_.md_** file for each release.  Add the release notes as text to the release so they are immediately available.

This can be achieved by refactoring the YAML file in the release workflows.

Refer to the YAML below for an example of what is currently being done.  For the value of the ```body``` YAML key, this is where you add text.  This text is hard coded though.  We need to find out how to pull the text out of the release notes so they can be injected.

One way this can be done is by using the [Read File](https://github.com/marketplace/actions/read-file) github action on the marketplace.  This can read the contents of the file and is then used as the output.  This output can then be used to inject the content into the body of the release notes.

```yml
    - name: Release Testing Application
      uses: softprops/action-gh-release@v0.1.13
      with:
        tag_name: v${{ steps.proj-file-version.outputs.version }}
        body: |
          ${{ env.PROJECT_NAME }} - Preview Release [v${{ steps.proj-file-version.outputs.version }}](https://github.com/KinsonDigital/${{ env.PROJECT_NAME }}/tree/v${{ steps.proj-file-version.outputs.version }})
          Execute the testing application in the **_${{ env.PROJECT_NAME }}-TestingApp-v${{ steps.proj-file-version.outputs.version }}.zip_** file to perform manual testing.
        files: |
          ${{ env.PROJECT_NAME }}-TestingApp-v${{ steps.proj-file-version.outputs.version }}.zip
          ${{ github.workspace }}\Documentation\ReleaseNotes\PreviewReleases\Release-Notes-v${{ steps.proj-file-version.outputs.version }}.md
        prerelease: true
```

### Acceptance Criteria

**This issue is finished when:**
- [ ] Release notes added as text to Preview Releases
- [ ] Release notes added as text to Production Releases

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without changes

**Reason:** This will be implemented by the issue below:

- #342
