### ISSUE TITLE
🚧Fix issue template spelling issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#295]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

In the `research-issue-template.yml` issue template file, remove the spacing between the emoji and the word "research".
Also regenerate the research link for the **_Acceptance Criteria_** area

**Spelling issue:**
![image](https://user-images.githubusercontent.com/85414302/179797411-b21247aa-cfee-4dac-b80f-662c3e724656.png)

**Link to regenerate**
![image](https://user-images.githubusercontent.com/85414302/179802044-8219e671-9dc7-4a86-b8aa-873370b7d421.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] Spelling error fixed
- [x] Link regenerated

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Related Work

- KinsonDigital/CASL#84

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Thanks again @Kshitiz-Mhto!!  I will review and merge the PR when ready.
