### ISSUE TITLE
🚧Fix project item issue template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#296]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

In the project item issue template file, fix an issue with the breaking changes label in the change type labels table.
The breaking changes label used to have a bomb emoji but was changed to dynamite.  This in turn broke the reference link.

Refer to YAML below to see where fix needs to be applied:
```yml
- type: textarea
  attributes:
    label: "Additional Information:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>Change Type Labels</summary>_**
      
      | Change Type         | Label                                                                                |
      |---------------------|--------------------------------------------------------------------------------------|
      | Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
      | Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      | 👈🏼 Fix this one
      | Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
      | Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
      | Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
      | Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
      </details>

      **_<details closed><summary>Priority Type Labels</summary>_**
      
      | Priority Type       | Label                                                              |
      |---------------------|--------------------------------------------------------------------|
      | Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
      | Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
      | High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
      </details>
```

Change the title at the very top of the YAML to the result below:
```yml
title: "🚀Release To <TODO: add release type here> - <TODO: add release number here>"
```

### Acceptance Criteria

**This issue is finished when:**
- [x] Breaking changes broken label ref link fixed in change type table

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Related Work

- KinsonDigital/CASL#84

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes     |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Absolutely.  If you don't mind, just please make sure that you link the PR and Issue together.
This can be done by clicking the development link and finding the PR to link them.

Refer to below:
![image](https://user-images.githubusercontent.com/85414302/180821042-fb099db4-91be-42df-94dd-3e1774379c48.png)

**Comment by CalvinWilkinson** [comment]
> @CalvinWilkinson Does contributor has the access to link issue to PR through development option? Because i am not able to perform that linking stuff.

Actually, you are correct.  I completely forgot that you cannot do that.  Don't worry about that part.  I will take care of it.

**Comment by KinsonDigitalTest** [comment]
This is a test comment

**Comment by KinsonDigitalAdmin** [comment]
@Kshitiz-Mhto Another heads up, don't worry about checking off the check boxes in the acceptance criteria.   GitHub will not allow contributors outside of the core development team check them off and for good reason.  I just learned about this.  Just simply try to make sure that the things in the acceptance criteria are complete and I will double check them and check them off when I code review things.

I apologize.  😁   Please bear with me due to me not having outside contributors before so some of these GitHub related things is the first time I have had to personally deal with them.  If you prefer, you can just simply only copy the acceptance criteria check boxes into a comment but you don't even have to do this.  I would prefer you don't copy the entire text of the issue because it might be confusing to newcomers to see what looks like the issue being duplicated in the comment stream.

**Comment by KinsonDigitalAdmin** [comment]
Comment deleted to avoid confusion for newcomers
