### ISSUE TITLE
🚧Exchange preview label for label link

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#298]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, in the preview feature pr template, the todo checkbox that explains to add a preview label uses an image to some github user content for the project, instead of using a direct ref link to the label.

Change this to use the ref link.

**Refer To Image Below:**
![image](https://user-images.githubusercontent.com/85414302/179807171-1e2c7549-1a70-4a34-b4d0-243db9f671e0.png)

### Acceptance Criteria

**This issue is finished when:**
- [ ] Preview label link exchanged for label link

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
@Kshitiz-Mhto Yes,  that will work perfectly.

**Comment by CalvinWilkinson** [comment]
@Kshitiz-Mhto Have you already created a pull request?  I clicked the hash just above and it shows me some commits or code changes that you have made but I don't see a PR made in my project.

**Comment by CalvinWilkinson** [comment]
@Kshitiz-Mhto 
I can see your branch and code change on that branch just fine in your fork.   I do not see any open pull requests for this issue.

Here is what I am currently seeing for open pull requests for Velaptor.
![image](https://user-images.githubusercontent.com/85414302/182687011-a2a98f22-2e8c-4d2b-a341-2751d85e760f.png)

**Comment by CalvinWilkinson** [comment]
Closed without merging

**Reason:** The direction the organization has taken to deal with ISSUE and PR templates has shifted.  This is no longer needed due to the templates being managed at the organization level.
