### ISSUE TITLE
[Project Item] - Add feature to velaptor to automatically setup native libraries

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#30]
### Title Updated

- [X] I have updated the title by replacing the '\<title\>' section.

### ---
Description

Add the ability on library startup to check for native libraries that might be in the _**runtimes**_ folder and copy them to the execution path.

This might not work though due to when and how the libraries are loaded to memory.  It might be ok to copy them in during runtime and then it will be available once code execution continues and needs the libraries in place.

### Acceptance Criteria

**This issue is finished when:**
1. [ ] Before implementing anything, verify that this can be done by simply manually copying the libraries during runtime to the execution path in the `Program.cs` file just to prove that this will work.
2. [ ] Create class that takes care of this
3. [ ] The class should check and verify one library at a time and check that they all exist first before copying them.  If they all exist, then copy and continue.  If not, an custom exception should be thrown
3. [ ] Throw a meaningful custom exception with message to describe the issue
4. [ ] Create unit tests for the class
5. [ ] Unit tests added
6. [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass
