### ISSUE TITLE
🚧Improve branching documentation

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#302]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Make improvements to the `Branching.md` file.  This can include grammar, spelling, layout etc.

### Acceptance Criteria

**This issue is finished when:**
- [x] Branching documentation updated

### ToDo Items

- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Issue linked to the correct project.
- [x] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
