### ISSUE TITLE
🚧Project Item - Create workflow to check branch naming

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#31]
### Title Updated

- [X] I have updated the title by replacing the '**_<title>_**' section.

**Description:**
Create a workflow that checks to make sure that the branch names below are correct.  Use these workflows for the status checks.

1. feature/[0--9]-*
2. release/v[0-9].[0-9].[0-9]
3. develop

**Add workflows as status checks here:**
![image](https://user-images.githubusercontent.com/85414302/128105843-e0f28e43-9819-4cd8-98ed-b47ad978ebe0.png)

### Acceptance Criteria

**This issue is finished when:**
1. [ ] Code documentation added if required
2. [ ] Unit tests added
3. [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

**Comment by CalvinWilkinson** [comment]
Closed

After looking into this, the branch filters and setup throughout github already makes sure that branch names are correct using globbing patters and everything is only triggered based on correct naming as it is.  Not required.
