### ISSUE TITLE
🔬Research mermaid diagrams for PR templates

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#315]
### I have done the items below . . .

- [X] I have updated the title without removing the 🔬 emoji.

### What To Research

Research how to create a GIT graph that can be used in the top of the PR templates to explain the branch naming as well as what branches merge into other branches.

References:
- [GitHub Mermaid Diagrams](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams)
- [Mermaid](https://mermaid-js.github.io/mermaid/#/)

### Research Results
https://mermaid.js.org/intro/#git-graph

![image](https://user-images.githubusercontent.com/96791049/209326694-0f662609-ae71-4416-998e-58cf7166723a.png)

For Installation: 
https://mermaid.js.org/intro/#installation

### Acceptance Criteria

**This issue is finished when:**
- [x] https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%94%ACresearch label added to this issue.
- [ ] Research complete and issues created (if needed).
- [ ] If any issues were created, they have been added to the _**Related Work**_ section below.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by kselena** [comment]
@CalvinWilkinson I did a little bit of research on this and put it in the body of the issue.  I believe there needs to be more research done as well as a conversation to make sure we're on the same page.

**Comment by kselena** [comment]
@CalvinWilkinson let me know if this is what you're looking for or if you need more research done.

**Comment by CalvinWilkinson** [comment]
> @CalvinWilkinson let me know if this is what you're looking for or if you need more research done.

Yeah, this is basically doing research and playing around to see if the diagrams can have all of the features I want to be able to replicate the graph below.

![branch diagram](https://raw.githubusercontent.com/KinsonDigital/.github/feature/24-create-org-docs/BranchingDiagram-DarkMode-v1.1.png)

**Comment by kselena** [comment]
@CalvinWilkinson ok.  It looks like they have the capability according to the research I did.  Do you need anything else?

**Comment by CalvinWilkinson** [comment]
One thing to note is that GIT graphs do not have the capability to do different styles of lines.
