### ISSUE TITLE
🚧Rename PR template files

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#316]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Rename all of the pull request template files by post fixing the name with `-template`.  The extension will still stay the same with the value `.md`.

### Acceptance Criteria

- [x] `feature-pr` file renamed
- [x] `preview-feature-pr` file renamed
- [x] `preview-release-pr` file renamed
- [x] `production-release` file renamed
- [x] Swap the todo items in the `preview-feature-pr.md` PR template.  Refer to image below
  - Reorder the items as numbered below.
![image](https://user-images.githubusercontent.com/85414302/183250518-70b80895-54f2-417b-a48c-1dce1e40af89.png)

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [X] Issue linked to the correct milestone _(if required)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/Velaptor/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by KinsonDigitalAdmin** [comment]
Good work @kselena !!
