### ISSUE TITLE
🚧 Project Item - Add description to the readme file

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#32]
### Title Updated

- [X] I have updated the title by replacing the '**_<title>_**' section.

**Description:**
Add a dscription to the **_README.md_** file description what the project is.
For example, "This is a 2D game development framework".

### Acceptance Criteria

**This issue is finished when:**
- [x] Code documentation added if required
- [x] All unit tests pass

### ToDo Items

- [x] ~~Draft pull request created and linked to this issue~~
    * THIS IS ALL BEING DONE IN A SINGLE BRANCH NAMED _**feature/move-to-github**_
- [X] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
