### ISSUE TITLE
🚧Create issues for refactoring unit test assertions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#320]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a thorough and detailed issue for refactoring all of the unit test assertions to use the **FluentAssertions** library.

This will greatly cleanup the unit testing side of things.   First figure out how many files need to be converted and create the required number of issues that will equally divide up the work to eventually get all of the unit tests converted.  For example, if there was 100 files, you could divide the work up by having each issue convert 5 files at a time which would end up being a total number issues of 20 issues.

Each issue will be a https://github.com/KinsonDigital/Velaptor/labels/tech%20debt issue with low priority and each the issues will be brought into each release until all of the work is complete.

### Acceptance Criteria

- [ ] All issues created

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [X] Issue linked to the correct milestone _(if required)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/Velaptor/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
⚠️NOTE⚠️
NO PULL REQUEST REQUIRED

**Comment by kselena** [comment]
@CalvinWilkinson  Can I work on this or do you have to come up with the test assertions first?
