### ISSUE TITLE
🚧Fix release todo issue template

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#325]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix the `release-todo-issue-template.yml` file by replacing removing backslash in the template.  Refer to the example below:

```diff
-    - label: "Title updated by replacing the '**_\<TODO: release type here\>_**' section with the type of release."
+    - label: "Title updated by replacing the '**_<TODO: release type here>_**' section with the type of release."


-    - label: "Title updated by replacing the '**_\<TODO: release version number here\>_**' section with the version number."
+     - label: "Title updated by replacing the '**_<TODO: release version number here>_**' section with the version number."
```

### Acceptance Criteria

- [x]  Release todo issue template updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [X] Issue linked to the correct milestone _(if required)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/Velaptor/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
