### ISSUE TITLE
🚧Update release todo template 

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#327]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the `release-todo-issue-template.yml` file.

1. Add todo task to the **Perform Release ToDo List** right before the last checkbox to verify that the PR has been approved and merged BEFORE the release is performed.  (Make this the second to last checkbox)
2. Update the last label about the release to preview and production.

Use the YAML below for the update.

**Refer to example below:** 
```yml
- label: Pull request has been approved and merged into a release branch before performing the release. (Releases are performed on release branches, not preview release branches.)
- label: Release to **_preview_** or **_production_** complete.  Refer to the **_Release Execution_** section below.
```

### Acceptance Criteria

- [x] Template has been updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [X] Issue linked to the correct milestone _(if required)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/Velaptor/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/Velaptor/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/Velaptor/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/Velaptor/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
