### ISSUE TITLE
🚧 Project Item - Update all issue templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#33]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description
Update all of the issue templates to match the setup of the CASL library

### Acceptance Criteria

**This issue is finished when:**
- [x] Bug issue template updated
- [x] Feature request issue template updated
- [x] Project item issue template updated
    - [x] Remove the string "Project Item -" from the title.  Only have the construction emoji
    - [x] Create issue for CASL library to do the same thing

### ToDo Items

- [x] ~~Draft pull request created and linked to this issue~~
    * THIS IS ALL BEING DONE IN A SINGLE BRANCH NAMED _**feature/move-to-github**_
- [X] Priority label added to issue
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
