### ISSUE TITLE
🚧Change build system

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#342]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

## Description

Change the build system by moving to the CICD dotnet tool.  This will greatly simplify the build system for releases as well as how status checks work.

### Acceptance Criteria
- [x] All current workflows deleted/removed
  - All of the workflows will be replaced by the CICD dotnet tool generated workflows
- [x] CICD dotnet tool added to the solution

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Issue Dependencies

- #344 

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
