### ISSUE TITLE
🚧Setup project to only run x64

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#344]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Set up the project to only run x64.  This will contain various changes for this to occur.

**Reason:**
This is to get a speed benefit.  When running portable/AnyCPU, this will have the application run the application with JIT compilation.  The benefit here is that you do not have to worry about the CPU architecture when running your application.  It just simply works.  The downside is that there will be a performance penalty.  Read more [here](https://stackoverflow.com/questions/53860621/what-are-differences-between-portable-and-win-x64-when-deploying).

**Solution Configs:**
The 3 solution configurations need to be changed from running in **AnyCPU** to **x64**.  This can be done by using the **Visual Studio** or **JetBrains Rider** solution configuration.  This will have to be done with all 3 projects.

The end result should only be the 3 configs below:
- Debug|x64
- Debug-Console|x64
- Release|x64

**CSharp Project Files:**
Any _**Conditions**_ in the csproj files will have to be updated.  This can be done by going to the project settings.  Updating the solution configs might very well do this automatically.

**Workflow Changes:**
The workflows have various setups for the build configuration.  These will have to all be updated.  This also means that the builds will have to be specifically built for `win-x64`.  This can be passed into the reusable workflows in the **Infrastructure** repo.

**Run/Debug Configurations:**
Setup a run/debug configuration that runs the **VelaptorTesting** application.  Currently, one is set up but it is not saved to the **JetBrains Rider** IDE shared settings.  Save this config to the Rider settings to be committed to the repo.
Also, make sure that everything is set up and works for **Visual Studio**

💡The application will have to be tested to make sure that everything runs correctly with the architecture change
💡There will be https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes to anybody that is running x86(32bit) architecture machines. 

### Acceptance Criteria

- [x] Solution configurations updated
  - [x] Velaptor
  - [x] VelaptorTests
  - [x] VelaptorTesting
- [x] CSProj files updated for all projects
- [x] All workflows updated that are required to be updated
  - [x] All build configs updated
  - [x] Specific use of `win-x64` arch when building.
- [x] Run/Debug config for **VelaptorTesting** created and saved for **JetBrains Rider** users
  - [x] Config for Debug-Console
  - [x] Config for Release-Console

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
