### ISSUE TITLE
🚧Setup CLA Assistant

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#348]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Setup ([CLA Assistant](https://github.com/cla-assistant/cla-assistant) )for the project.

This will help manage the signing of the license agreements using PRs for all contributors.

### Acceptance Criteria

- [ ] CLA assistant is set up
- [ ] Create issues to set up CLA Assistant for projects below: 
  - [ ] CASL
  - [ ] VersionMiner
  - [ ] BranchValidator

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by kselena** [comment]
@CalvinWilkinson  Please research CLA Assistant to collect more info for other issues to be created

**Comment by CalvinWilkinson** [comment]
Simple simple researching revieled that having a CLA is not required.

For more info, refer to [this](https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/) from Ben Balter who is the Chief of Staff for Security at [GitHub](https://github.com/about).
