### ISSUE TITLE
🚧 Project Item - Setup CodeCov

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#35]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description
Setup CodeCov account to collect code coverage.

### Acceptance Criteria

**This issue is finished when:**
1. Code coverage setup in codecov

### ToDo Items

- ~~Draft pull request created and linked to this issue~~
    * THIS IS ALL BEING DONE IN A SINGLE BRANCH NAMED _**feature/move-to-github**_
- [X] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

### Related Work

- #25
