### ISSUE TITLE
🚧Refactor unit test assertions

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#357]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor all of the unit test assertions to use the **FluentAssertions** library.
This will greatly cleanup the unit testing side of things and make the creation of unit tests easier.

> **Note**
> 1. We have been migrating all of our assertion code for the past 6 months from standard XUnit assertions API to [FluentAssertions API](https://fluentassertions.com/introduction) API.  Most of the code base has been converted and examples can be found all of the place.  Please don't hesitate to ask questions and for help if needed.
> 2. Please follow our [Contribution Guide](https://github.com/KinsonDigital/.github/blob/main/docs/CONTRIBUTING.md)

### Acceptance Criteria

- [ ] Latest version of FluentAssertions Nuget package added to the project
- [ ] Refactor the files below: 
  - [x] ~`EnsureThatTests.cs`~ - 55 lines
  - [ ] `SystemDisplayTests.cs` - 359 lines
  - [ ] `InvalidInputExceptionTests.cs` - 50 lines
  - [ ] `NoKeyboardExceptionTests.cs` - 50 lines
  - [ ] `NoMouseExceptionTests.cs` - 50 lines

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if required)_.
- [ ] Issue linked to the correct milestone _(if required)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by ljdarj** [comment]
I wish to take up this issue if it's still current.

**Comment by CalvinWilkinson** [comment]
Do not bother with refactoring the `EnsureThatTests` file.  This file is being removed in another issue.

**Comment by CalvinWilkinson** [comment]
Hello @ljdarj!! 

I just wanted to touch base with you and see if you still plan on working with this issue.  I noticed that no pull request has been created for this and it seems like there has not been any activity for about 3 weeks.

Thanks for any updates.  😀

**Comment by CalvinWilkinson** [comment]
Just a quick side note @ljdarj.

If you do still plan on doing this, that is completely fine.  I just needed to know which release to slot this in for.  We can release it at a later time.

**Comment by ljdarj** [comment]
Sorry I wasn't here, life got in the way. I intend to do it by the first week of January at the latest.

**Comment by CalvinWilkinson** [comment]
> Sorry I wasn't here, life got in the way. I intend to do it by the first week of January at the latest.

Not a problem at all. 😀  I understand how life can get in the way.  Especially as we approach the end of the year and the holidays.
I will just move the issue to another release.

Thanks for updating me!!

**Comment by kselena** [comment]
@ljdarj Happy New Year!!  I hope you're doing well.   I am following up on this issue.  If you're not able to work on it, that's completely understandable.  Please let myself or @CalvinWilkinson know and we can take care of it.  Thanks and have a great rest of your week!
