### ISSUE TITLE
🚧Refactor unit test assertions

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#358]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor all of the unit test assertions to use the **FluentAssertions** library.
This will greatly cleanup the unit testing side of things and make the creation of unit tests easier.

> **Note**
> 1. We have been migrating all of our assertion code for the past 6 months from standard XUnit assertions API to [FluentAssertions API](https://fluentassertions.com/introduction) API.  Most of the code base has been converted and examples can be found all of the place.  Please don't hesitate to ask questions and for help if needed.
> 2. Please follow our [Contribution Guide](https://github.com/KinsonDigital/.github/blob/main/docs/CONTRIBUTING.md)

### Acceptance Criteria

- [ ] Latest version of FluentAssertions Nuget package added to the project
- [ ] Refactor the files below: 
  - [ ] `KeyboardStateTests.cs` - 659 lines
  - [ ] `KeyboardTests.cs` - 97 lines
  - [ ] `MouseStateTests.cs` - 514 lines
  - [ ] `MouseTests.cs` - 000 lines
  - [ ] `FreeTypeErrorEventArgsTests.cs` - 172 lines

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if required)_.
- [ ] Issue linked to the correct milestone _(if required)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by fkamau1** [comment]
Hey @CalvinWilkinson, I would like to work on this issue.

**Comment by CalvinWilkinson** [comment]
@fkamau1 It is ready for you to work on.  😀

**Comment by CalvinWilkinson** [comment]
`KeyboardStateTests` and `KeyboardTests` were already refactored due to previous issues being merged.
