### ISSUE TITLE
🚧Refactor unit test assertions

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#359]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor all of the unit test assertions to use the **FluentAssertions** library.
This will greatly cleanup the unit testing side of things and make the creation of unit tests easier.

> **Note**
> 1. We have been migrating all of our assertion code for the past 6 months from standard XUnit assertions API to [FluentAssertions API](https://fluentassertions.com/introduction) API.  Most of the code base has been converted and examples can be found all of the place.  Please don't hesitate to ask questions and for help if needed.
> 2. Please follow our [Contribution Guide](https://github.com/KinsonDigital/.github/blob/main/docs/CONTRIBUTING.md)
> 3. Join the [KinsonDigital Community](https://discord.gg/qewu6fNgv7)!!

### Acceptance Criteria

- [ ] Latest version of FluentAssertions Nuget package added to the project
- [ ] Refactor the files below: 
  - [ ] `GLFWErrorEventArgsTests.cs` - 37 lines
  - [ ] `GLFWDisplayChangedEventArgsTests.cs` - 22 lines
  - [ ] `GLFWDisplayTests.cs` - 211 lines
  - [ ] `OpenGLServiceTests.cs` - 439 lines
  - [x] ~`BufferManagerTests.cs`~ - 158 lines

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if required)_.
- [ ] Issue linked to the correct milestone _(if required)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by thestbar** [comment]
Hello, I would like to work on this! Please assign it to me!

**Comment by CalvinWilkinson** [comment]
Absolutley!! If you have any questions, please don't hesitate to ask.  I have a discord server as well that you can join and ask questions.

**Comment by CalvinWilkinson** [comment]
The `BufferManagerTests` class does not need to be tested.  This was removed in the release of **v1.0.0-preview.15**
