### ISSUE TITLE
🚧 Project Item - Update all pull request templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#36]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### ---
Description

Update all pull request templates to match that of the CASL library

### Acceptance Criteria

**This issue is finished when:**
- [x] Feature To Develop PR template updated
- [x] Preview Release To Release PR template updated
- [x] Release To Master PR template updated

### ToDo Items

- ~~Draft pull request created and linked to this issue~~
    * THIS IS ALL BEING DONE IN A SINGLE BRANCH NAMED _**feature/move-to-github**_
- [X] Priority label added to issue (prio-low, prio-medium, or prio-high)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
