### ISSUE TITLE
🚧Setup all workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#37]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Setup all of the workflows for the project.

### Acceptance Criteria

**This issue is finished when:**
- [x] ~~Create status check scripts~~
    - [x] ~~prev-version-status-check.js~~
    - [x] ~~prod-version-status-check.js~~
- [x] Create tag does not exist status check workflow
    - ~~This will use the new **VersionValidator** github action and will replace the **TagVerifier** actions~~
- [x] Create preview build status check workflow
    - ~~This will use the new **VersionValidator** github action and will replace the **TagVerifier** actions~~
- [x] Create release version status check workflow
    - ~~This will use the new **VersionValidator** github action and will replace the **TagVerifier** actions~~
- [x] Create unit testing status check workflow
- [x] Create preview release workflow
   - [x] Remove the **preview/\*** branch from the **preview** environment when finished with testing
   ![image](https://user-images.githubusercontent.com/85414302/132601284-eb5eba24-8f5d-4707-98e6-88e00b1cac89.png)

- [x] Create build status check workflow
- [x] Create release workflow
- [x] Setup status checks that must pass before branches can be merged into the __release/v\*.\*.\*__ branches
![image](https://user-images.githubusercontent.com/85414302/132495218-8759eb40-29e1-45aa-b9bc-fee5c8186f38.png)

### ToDo Items

- [x] ~~Draft pull request created and linked to this issue~~
- [x] Priority label added to issue (low priority, medium priority, or high priority)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone
- ~~Unit tests have been written and/or adjusted for code additions or changes~~
- ~~All unit tests pass~~

**Comment by CalvinWilkinson** [comment]
Creating status check scripts will not be implemented with this.  This functionality is now performed by the new **VersionValidator** GitHub action

**Comment by CalvinWilkinson** [comment]
After further investigation, the **Tag Does Not Exist Status Check** workflow did not need to be replaced by the **VersionValidator** GitHub action.

**Comment by CalvinWilkinson** [comment]
After further investigation, the **Preview Build Status Check** workflow did not need to be replaced by the **VersionValidator** GithHub action.

**Comment by CalvinWilkinson** [comment]
After further investigation, the **Production Build Status Check** workflow did not need to be replaced by the **VersionValidator** GithHub action.

**Comment by CalvinWilkinson** [comment]
Originally there was different YAML workflow files for each environment for each type of status check as well as version check and build and unit testing.

This has all be improved and consolidated into single workflows that work for all of the required branches/environments.
