### ISSUE TITLE
🚧Refactor unit test assertions

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#371]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor all of the unit test assertions to use the **FluentAssertions** library.

This will greatly cleanup the unit testing side of things and make the creation of unit tests easier.

### Acceptance Criteria

- [ ] Latest version of FluentAssertions Nuget package added to the project
- [ ] Refactor the files below: 
  - [ ] `WindowTests.cs` - 273 lines
  - [ ] `CachedValueTests.cs` - 196 lines
  - [ ] `FrameTimeTests.cs` - 160 lines
  - [ ] `InternalExtensionMethodsTests.cs` - 1051 lines
  - [ ] `PublicExtensionMethodsTests.cs` - 612 lines
  - [ ] `SizeUTests.cs` - 163 lines
  - [ ] `LoadContentExceptionTests.cs` - 50 lines

### ToDo Items

- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct project _(if required)_.
- [ ] Issue linked to the correct milestone _(if required)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed with no changes or PR. 

**Reason:** None of the code required any refactoring.
