### ISSUE TITLE
🚧Refactor classes to sealed

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#373]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Go through the entire code base and find classes that can be sealed.  These of course will include all classes that are not being inherited.  The reason for this change is for performance benefits.  All kinds of operations such as instantiation, arrays of classes, type checking, and more have substantial performance benefits by using `sealed` classes.

Refer to [this](https://www.youtube.com/watch?v=d76WWAD99Yo&list=WL&index=33) youtube video by **_Nick Chapsas_** for more information on the perf gains and details about the subject.

If the code for the class can easily be changed not to be inherited by choosing composition over inheritance, create issues for each case to refactor this so it can be altered to sealed.

Add a compiler warning to the `.editorconfig` file.  It has been confirmed that this warning will be implemented in NET **_v7.0_**.  The rule is `dotnet_diagnostic.CA1852.severity = warning`.

**_v1.0.0_** is not out yet.  This is considered best practice in the industry now and it is much better to do this in preview than it is after **_v1.0.0_** has been released.

All unit test classes should be converted to `sealed`.  This is easy due to the fact that nothing inherits the unit test classes.  This will give a performance benefit when running tests.

⚠️WARNING⚠️
This issue in its entirety will be a breaking change.   Changing a class from non-sealed to sealed is always a breaking change.
This issue **MUST** be implemented **BEFORE** version **_v1.0.0_**!!

### Acceptance Criteria

- [x] All classes that can easily be converted to `internal` is converted.
- [x] All classes that can easily be converted to `sealed` is converted.
- [x] All classes that cannot be converted to `sealed` but the code base can be refactored for composition, should have a new issue created.
- [x] Warning `dotnet_diagnostic.CA1852.severity = warning` added to the solution level `.editorconfig` file

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
