### ISSUE TITLE
🚧Refactor unit test assertions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#375]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor all of the unit test assertions to use the **_FluentAssertions_** library.

This will greatly clean up the unit testing side of things and make the creation of unit tests easier.
First, check to see if the latest version of the **_FluentAssertions_** NuGet package is installed in the unit test project named **_VelaptorTests_**.  If not, add the NuGet package to the project.

Refactor the assertion sections of all the unit tests in the **_WindowSizeEventArgsTests.cs_** file.

For information on how to use fluent assertions, refer to this link here 👉🏼 [Fluent Assertions Documentation](https://fluentassertions.com/introduction).

### Acceptance Criteria

- [x] The _**FluentAssertions**_ NuGet package has been added if it does not already exist.
- [x] All of the assertion code in the **_WindowSizeEventArgsTests.cs_** file converted to use the **_FluentAssertions_** library.

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by SyedMSawaid** [comment]
Hey! I would like to start working on it. Can you kindly assign it to me?

**Comment by CalvinWilkinson** [comment]
@SyedMSawaid Issue has been assigned.  Let me know if you need anything.

**Comment by CalvinWilkinson** [comment]
Great job @SyedMSawaid!!  Thanks for the contribution!!
