### ISSUE TITLE
🚧Update to new logo

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#376]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the project README to the new logo.

Also, create a new application icon from the new logo and set up the csproj file to use it.
Se tup and pack the logo into the NuGet package.

### Acceptance Criteria

- [x] Project logo updated
- [x] Project `README.md` file updated
- [x] App icon recreated with the new logo
- [x] App icon set to the new icon
- [x] NuGet package setup to pack and use the new logo _**.png**_ image as the icon

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
