### ISSUE TITLE
🚧Move internal visible setup

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#377]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Move all `[assembly: InternalsVisibleTo()]` attributes to the csproj file.

**Add this to the Velaptor.csproj file @ line 47:**
```xml
<ItemGroup>
  <InternalsVisibleTo Include="$(AssemblyName)Tests" />
  <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
</ItemGroup>
```

It will go in between . . 
```xml
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
    <OutputPath>bin\x64\Release\</OutputPath>
  </PropertyGroup>
```
and
```xml
  <ItemGroup>
    <None Include="velaptor-logo.ico" Pack="true" PackagePath="\" />
    <None Include="..\Documentation\Images\velaptor-logo.png" Pack="true" PackagePath="\" />
    <None Include="..\LICENSE.md" Pack="true" PackagePath="\" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
```

For more info on this if required, refer to this [video](https://www.youtube.com/watch?v=6WeT-JQBI98)

### Acceptance Criteria

- [x] `InternalsVisibleTo` attributes moved.
- [x] _**ExposedInternals.cs**_ file deleted from the Velaptor project

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
