### ISSUE TITLE
🚧Fix pathing issues

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#382]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, the tests for the `ContentPathResolver` class are failing when it runs on the _**Ubuntu**_ image for GitHub actions.
These pathing issues need to be addressed and refactored to be cross platform.

Refactor the code the make sure that all `\` characters will be converted to `/` characters.

Go to [here](https://github.com/KinsonDigital/Velaptor/actions/runs/3255409021/jobs/5344697242) to view the failing tests.

### Acceptance Criteria

- [x] Pathing issues fixed
- [x] All failing unit tests passing

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
