### ISSUE TITLE
🚧Fix bug with path resolvers

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#385]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

During the implementation of issue #382, unit tests passed by proper QA testing were skipped and a bug with the pathing changes was introduced into all of the path resolver types.

In #382, the pathing was changed to be cross-platform capable.  During this implementation, the resolvers types were not finding and filtering files to match the content they are looking for due to the mix of '\' and '/' characters being missed in the paths.

Refactor the code in all of the path resolver classes to make sure that all '\' characters are replaced with '/' characters before comparison.  Refer to the example below to see an example of how it should be done.  This is simular to how they can be fixed but not every single resolver fix might be the exact same.

**Example:**
This fix example is located in the `ContentFontPathResolver` class in the `ResolveFilePath()` method.
```cs
var possibleFiles = this.directory.GetFiles(contentDirPath, $"*{FileExtension}")
                .Select(f => f.Replace('\\', '/')).ToArray();

            // Check if there are any files that match the name
            var files = (from f in possibleFiles
                         where string.Compare(
                             f,
                             $"{contentDirPath}{CrossPlatDirSeparatorChar}{contentName}{FileExtension}",
                             StringComparison.OrdinalIgnoreCase) == 0
                         select f).ToArray();
```

### Acceptance Criteria

- [x] `TexturePathResolver` class updated
- [x] `AtlasJSONDataPathResolver` class updated
- [x] ~`AtlasTexturePathResolver` class updated~
- [x] ~`ContentPathResolver` class updated~
- [x] `ContentFontPathResolver` class updated
- [x] ~`FontPathResolver` class updated~
- [x] `WindowsFontPathResolver` class updated
- [x] `SoundPathResolver` class updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Related Work

- #382 

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
The classes below did not require any change.

- `AtlasTexturePathResolver`
- `ContentPathResolver`
