### ISSUE TITLE
🚧Update NVorbis NuGet package

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#389]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the **NVorbis** NuGet package from version _**v0.10.3**_ to **_v0.10.5+_**.

If the version of the package is greater than _**v0.10.5**_, only update the package if it is a minor or path update.

**History:**
This update was intended in issue #293, but somehow it got downgraded from version _**v0.10.4**_ to version _**v0.10.3**_.  The intention was researched but no answer could be found and the intention or reasoning for the downgrade is unclear.

You can view the downgrade change [here](https://github.com/KinsonDigital/Velaptor/pull/337/files).  Look at the _**Velaptor.csproj**_ file for the change.  

If there is a major update available when this issue is being worked on, please notify @CalvinWilkinson about the higher package update available before updating the package.

### Acceptance Criteria

- [x] ~**NVorbis** NuGet package updated from version _**v0.10.3**_ to version _**v0.10.5+**_~
- [x] Remove the commented package reference for **NVorbis** that is set for version _**v0.10.5**_

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by x0rld** [comment]
do you want an update of all dependencies ?

**Comment by CalvinWilkinson** [comment]
@x0rld Hello!!
I actually have already updated all the dependencies just recently.

NVorbis is all I need right now.  But if you want to check for other updates and let me know whats up, that would be awesome.!!

**Comment by CalvinWilkinson** [comment]
> do you want an update of all dependencies ?

I also apologize about the late response.  I work on this full time and yesterday it did not show me a notification.  But this morning it did.  I don't know what is up with that.  I am usually quite responsive.

If you are interested, I have a [discord channel](https://discord.gg/qewu6fNgv7) as well if you want to chat or have questions or anything. :)

**Comment by CalvinWilkinson** [comment]
Reassigned issue to @CalvinWilkinson.  Original assignee did not respond to the the linked pr #397

**Comment by CalvinWilkinson** [comment]
No nuget package to update.  The only thing to do is remove the comment from the csproj file.

The commented NVorbis nuget package reference was before all the sound functionality was converted into the CASL project.
