### ISSUE TITLE
🚧Remove library copy in csproj

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#393]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

In the _**VelaptorTesting**_ project, a library named _**soft_oal.dll**_ is being copied from the build output _**runtimes**_ directory to the executable directory.

This is not required anymore and has been like this for a long time due to some previous setup.  Remove this from the _**VelaptorTesting.csproj**_ file.

**Remove Below:**
```diff
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

-  <Target Name="CopyOpenALLibrary" AfterTargets="Build">
-    <Copy 
-      SourceFiles="$(TargetDir)runtimes\win-x64\native\soft_oal.dll"
-      DestinationFolder="$(TargetDir)"
-      SkipUnchangedFiles="false"/>
-  </Target>
</Project>
```

### Acceptance Criteria

- [x] XML removed from csproj file related to the library copy operation

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Re-assigned issue to @CalvinWilkinson.

Original contributor decided not to move forward and GitHub auto closed the pull request due to the deletion of the fork repo.
