### ISSUE TITLE
🚧Add tweet template to project

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#395]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a tweet template file named _**ReleaseTweetTemplate.txt**_ to the _**.github**_ folder.

The name of the file must be exactly what is stated above due to the build system requiring it.

**Tweet Template Example:**
```txt
{PROJECT_NAME} v{VERSION} just dropped!! 🚀
Check it out & take it for a spin & help support development. 🤘🏼
Release: https://github.com/KinsonDigital/{PROJECT_NAME}/releases/tag/v{VERSION}
NuGet Package: https://www.nuget.org/packages/KinsonDigital.{PROJECT_NAME}/{VERSION}
Discord: https://discord.gg/qewu6fNgv7
Project: https://github.com/KinsonDigital/{PROJECT_NAME}
```

This can be tweaked a little bit to meet the changes to the tweet improvements for the issue below: 
- KinsonDigital/CICD#118

This issue cannot be completed until the tweet improvements have been completed.

### Acceptance Criteria

- [x] Release tweet template added to the project.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Issue Dependencies

- KinsonDigital/CICD#118

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Removed from release for version _**v1.0.0-preview.11**_.

**Reason:**  It was realized that this issue had a dependency on the issue below.  This cannot be done right now.

- KinsonDIgital/CICD#118
