### ISSUE TITLE
🚧Setup stale bot

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#404]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Set up the stale bot in the organization and enable it for _**Velaptor**_ as the first project to start using it.

Refer to the `🔬research` issue below for more info:
- #398 

### Acceptance Criteria

- [x] Stale bot app installed into the organization
- [x] Stale bot YAML file created and setup
  - [x] Set `daysUntilStale` to 60
  - [x] Set `daysUntilClose` to 7
  - [x] Set `exceptLabels` to the labels below
    - [x] `🚀Preview Release`
    - [x] `🚀Production Release`
    - [x] `🚀QA Preview Release`
    - [x] `🚀Hot Fix Release`
    - [x] `🚀QA Production Release`
    - [x] `⚕️NEEDS TRIAGE`
    - [x] `🔬research`
  - [x] Set `exemptMilestones` to `true`
  - [x] Set `staleLabel` to the label `stale`
    - Set this to a brownish green color
  - [x] Set the `markComment` to
    - Use the example comment in the template on the main README page
  - [x] Set the `unmarkComment` to
    ```txt
    This issue's stale status has been removed due to activity.
    ```
  - [x] Set the `closeComment` to
    ```txt
    This issue has been closed due to the issue being stale due to a lack of activity.
    ```
  - [x] Set the `limitPerRun` to the max value of 30

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
