### ISSUE TITLE
🚧Create outside contributor docs

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#408]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create some documentation for outside contributors.  This is documentation that only pertains to what is minimally necessary for outside contributors and involves fewer steps and confusion compared to the project maintainers and their responsibilities.

### **Things To Explain:**

1. Add the contribution steps from the README file
2. Add only the _**Feature Branch**_ and _**Preview Feature Branch**_ documentation from the branch docs
3. Explain that the PR title must match the issue.
4. Provide links to the organization PR templates for both branch types

Update the project's readme file for links to more detailed information for project maintainers and people who are simply more interested and a section that links to the outside contributor's docs.

### Acceptance Criteria

- [x] Outside contributor documentation
- [x] Project README updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
