### ISSUE TITLE
🚧Throw exception for zero pointers

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#420]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Throw an exception for any method in the `FreeTypeInvoker` class that takes a parameter type of `IntPtr` that is a value of zero.

Do this in the form of a guard.   Create a new guard method named `PointerParamIsNotZero` in the `EnsureThat` class.

Do the following:
- The method should take a parameter of type `IntPtr` as its first parameter with the name `value`.
- Make sure that the method API docs follow the same structure and idea as the other 2 methods.
- For the exception method use the text below:
  - `The pointer must not be a value of zero.`
- The exception to throw should be `ArgumentException`

### Acceptance Criteria

- [ ] New guard method created
- [ ] All methods in the `FreeTypeInvoker` class should use the new guard for the `IntPtr` parameter

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
