### ISSUE TITLE
🚧Add README to NuGet package

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#423]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a README.md to the NuGet package.  This can be done in the csproj file.
This can be done by making some changes to the _**.csproj**_ file.

This will also include setup to tell the CICD system of the organization to pre-process the README file.  This preprocessing will be special manipulation of the README file to prepare the markdown for the NuGet package.

The reason for this is that there are various kinds of markdown syntax that is not supported on nuget.org.
Things like images or kinds of HTML.  The idea here is that the README file will contain block commented areas of content that should be shown in nuget.org which are areas that will not be shown anywhere else.

### **Resources:**
- [Add README to your package blog](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/)
- [Package ReadMe File (MsDocs)](https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile)
- [Package readme on NuGet.org](https://learn.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org)

Refer to the issue in the dependencies section below for more info.

**Here are the things to add:**
```xml
<PackageReadmeFile>README.md</PackageReadmeFile>
```

```xml
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
```

**Project File Changes:**
```diff
    <PackageTags>velaptor raptor 2D game games framework</PackageTags>
    <Configurations>Debug;Release</Configurations>
    <PackageIcon>velaptor-logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Platforms>x64</Platforms>
+  <PackageReadmeFile>README.md</PackageReadmeFile>
```

```diff
  <ItemGroup>
    <None Include="velaptor-logo.ico">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\Documentation\Images\velaptor-logo.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\LICENSE.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
+   <None Include="..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>
```

### Acceptance Criteria

**This issue is finished when:**
- [x] CICD dotnet tool updated to version _**v1.0.0-preview.14**_
- [x] **README** file setup with pre-processing syntax
    - [x] Comment section setup
    - [x] Uncomment section setup
    - [x] All HTML replaced with standard markdown
    - [x] All image references are set up as raw GitHub user content.
      - This is a URL to raw image content on a particular branch.
      - Example URL: https://raw.githubusercontent.com/dotnet/Silk.NET/main/documentation/readme/silkdotnet_v3_horizontal_96.svg
    - [x] Any other areas that do not render correctly, comment them out.
- [x] **README** added to package.

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Issue Dependencies

- KinsonDigital/CICD#121

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>
