### ISSUE TITLE
🚧Improve ReadMe

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#426]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix indenting issues with any of the bullet items.
Fix broken link.

Find any areas were text content can be improved by converting to a **Note** or **Warning** block

Should look like this: 
> **Note**

### Acceptance Criteria

- [x] README improved with Notes and/or Warnings
- [x] Bullet indentation fixed
- [x] Broken link fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by kselena** [comment]
PR #427  merged.  This issued is closed.
