### ISSUE TITLE
🚧Fix broken logo link in README

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#433]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

In the README file, the markdown logo link is broken in the NuGet version of the README file.  This is due to the domain requirements for image references in markdown for markdown that is rendered in nuget.org for nuget packages.

Change the link to the NuGet package version of the README file to use a GitHub specific content link instead of a relative link to a local file within the repository.

The link below should be what is used:
https://github.com/KinsonDigital/Velaptor/blob/release/v1.0.0/Documentation/Images/velaptor-logo.png

### Acceptance Criteria

- [ ] Link updated for the NuGet package version of the README file content.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
