### ISSUE TITLE
🚧Add layered rendering

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#434]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

This feature will add layered rendering to the framework.  The purpose of this is to give the user the ability to control in which order textures are rendered.  A good example of this is a platform game.

In this kind of game, it is common to have different backgrounds rendered in layers on top of each other to compose a parallax scrolling of the different backgrounds as the character moves.  These different background textures are rendered in a particular order in comparison with each other as well as other parts of the game such as the character.  If the character was rendered first and then the background afterward, you would not be able to see the character.

---

There are various changes that need to be performed to set this up.  Refer to the list below for the list of things that need to occur.

1. Clean up the `Reactable` implementations by moving them into the abstract base class named `Reactable<T>`.
    - This involves calling `base.PushNotification(data)` in each implementation.
2. Setting batch sizes.
    - **Current Setup:** Currently, the batch size is set by calling the `SetBatchSize()` method in the `BatchServiceManager` class.  This in turn routes the batch size to the correct batching service.
    - **Changes:** This needs to be changed by creating a new custom `Reactable` to send a push notification to the batching services to set the batch size.
      - The reachable should be unsubscribed in the `onComplete`.
      - The push notification will come from the `Renderer` class ctor.
      - The `IRenderer.BatchSize` should be removed.  This value will become a constant in the `Renderer` class.
        - This is a `🧨breaking change` due to the interface and interface `const` being public.
      - All 3 batching service types need to be set up with the reactable.
3. `TextureBatchingService` changes
    - Refactor the class field `batchItems` from a `SortedDictionary<T, T>` into a standard array of type `TextureBatchItem[]`.
    - Constructor setup with new `Reactable` that is set up to receive the batch size as well as the unsubscription
    - Refactor `Add()` method to determine that the batch is full by checking if ALL of the batch items are not empty.
    - Refactor `Add()` method to "add" a new method by finding an item that returns as empty.  This item will get "over written" with the new incoming item.  After this is done, use `Array.Sort()` with a custom comparer to reorder the items from smallest layer to the largest.
    - Remove the class field `currentBatchIndex`.  This is not required anymore because every method invoke will be searching for the index of the array item data to replace instead of sequentially moving through the items.  Reordering the array every time removes the ability to rely on ordered position.
    - Look into optimizing by not sorting the array if the item being set in the same spot as the first empty item already puts the new item in the correct layer order
4. `FontGlyphBatchingService` class refactored for new batch size reactable
5. `RectBatchingService` class refactored for new batch size reactable
6. The `SetBatchSize()` method is removed from the `BatchServiceManager` class.
7. Refactor `TextureBatchItems` struct
    - Convert the struct into a readonly struct.  This will prevent defensive copies from being made and improve performance.
    - Set the parameter of the `Add()` method for the batching service classes to an `in` parameter.
    - Set all fields to `auto` props
    - Change ctor to take in all values via parameters.
8. Refactor the `Renderer` class to create a new `TextureBatchItem` using ctor parameters instead of using field assignment.
9. Testing Application Setup
    > **Note**
    > This will require an entirely new scene for testing out layered rendering.
    - Create a new layered rendering scene
    - Create a new texture atlas with different solid colored squares with numbers in each corner that can be used to render on top of each other to visualize if the layers are correct.
    - Add buttons on the scene to choose different layer types
    - Add text to the scene of the layer setup type.  Example: Layer Type 1, Layer Type 2, etc. . .
    - Add a description of what is expected of the current layering setup.

### Acceptance Criteria

- [x] `Reactable` cleanup performed
- [x] New `Reactable` created with the name `BatchSizeReactable`
- [x] `TextureBatchingService` class refactored to use new reactable
- [x] `FontGlyphBatchingService` class refactored to use new reactable
- [x] `RectBatchingService` class refactored to use new reactable
- [x] `SetBatchSize()` method removed from the `BatchServiceManager` class.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
