### ISSUE TITLE
🚧Update project to dotnet 7 & latest C# version

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#437]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the project to dotnet 7 as well as to C# language version _**v11**_.

If upgrading to C# 11 causes compile issues, revert back to C# 10 and create a separate issue for upgrading the code base to C# 11.

> **Warning**
> Full testing should be performed with the _**VelaptorTesting**_ application to verify that nothing has been broken.

### Acceptance Criteria

- [x] All projects updated to dotnet _**v7.0**_
- [x] Project language version upgraded to C# _**v11**_
- [x] Observe any coding pattern improvements or refactorings suggested by _**Rider**_.  If any exist, verify if they change should be implemented and create an issue to make the changes.
    > **Note**
    > If it is decided to not take on a change, update the _**.editorconfig**_ file to ignore the suggestion.
- [x] Search the code base (mostly docs) to check if anything is mentioned about the version of dotnet used and update appropriately or remove the content.
- [x] Update the _**Microsoft.CodeAnalysis.NetAnalyzers**_ NuGet package to the latest version

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
