### ISSUE TITLE
🚧Unload font in text rendering scene

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#443]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

In the text rendering scene for the _**Velaptor Testing**_ application, there is a class field of type `IFont` that is used for rendering the text.  This is not being unloaded in the `UnloadContent()` method in the scene.

This ends up causing the font to not be unloaded when moving to other scenes.  This causes the scene not to be reset/reloaded when going back to the text rendering scene.  This "reset" of the scene is ideal for testing purposes.

### Acceptance Criteria

- [ ] Scene font unloaded

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without any changes.

**Reason:** Work has already been done in issue #434
