### ISSUE TITLE
🚧Create window testing scene

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#444]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a new scene in the _**Velaptor Testing**_ application where testing can be done for the window.

These will include things like window size and position changes.

Add buttons that can be clicked to do testing using the mouse as well as keyboard keys to perform the same thing.

Moving the window with the keyboard, use the _**Left**_, **_Right_**, **_Up_**, & **_Down_**.
Changing the size of the window with the keyboard, use the _**Ctrl+Left**_, **_Ctrl+Right_**, **_Ctrl+Up_**, & **_Ctrl+Down_**.

Also, add instructions to the top of the window.

### Acceptance Criteria

- [ ] New scene added to the application for testing the window
  - [ ] Instructional text added
  - [ ] Moving window performed with buttons and keyboard
  - [ ] Changing window size performed with buttons and keyboard
- [ ] New video of scene created for the demo video

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without implementation

**Reason:**
It was decided that implementing this was not worth the time and effort due to all of the use of the window during the rest of the testing.
