### ISSUE TITLE
🚧Fix mouse bug with buttons

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#445]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix a bug with the mouse and buttons.

This bug occurs when a full mouse click is not registered due to the mouse not being over the top of the button control when the mouse is released.

### **Steps To Reproduce:**
1. Mouse the mouse over the CW button in the text rendering scene.
2. Press the left mouse button in the down position and hold.
3. Move the mouse away from the button so it is not over the face of the button anymore.
    - Keep the mouse button in the down position when while doing this.
5. With the mouse NOT over the button, let go of the mouse button.
6. Observe that the text is still rotating even though the left mouse button was let go.

This occurs because the internal state of the button is still in the down position.  The reason for this is that the button implementation currently requires the mouse to be over the face of the control, (inside of the control bounds), for the button state to be changed back to a state of release.   This is why the text keeps rotating.

The button state should be set back to the up position whether the mouse is inside of the button control bounds or not.

### Acceptance Criteria

- [ ] Bug fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Issue closed without changes.

**Reason:**  After further investigation, it was discovered that the `Button` is behaving correctly.  The only way to fix this would be to make sure that the `MouseUp` and/or `Click` events are invoked when the button is lifted into the up position even with the mouse _**NOT**_ being above the control.  

The problem with doing this is it goes outside of normal button behavior just to satisfy that the button rotation should be turned off.  The issue is that the button is being used more like a _**switch**_ / **_check box**_ and this desired behavior is outside of the purpose and design of a button.

The buttons used for this will have to be changed to check boxes once the checkbox control is implemented.
