### ISSUE TITLE
🚧Reduce font allocations and improve perf

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#447]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the `Font` class by improving performance and reducing memory allocations.

### **Use the attached file code below:**

---

The file is the `Font` class code with the improvements.  Simply paste over top the entire code base, run the test and do some simple testing to verify everything is working fine.

Also, run the **DPA (Dynamic Program Analysis)** tool in **_JetBrains Rider_** and verify that no closures or bad memory allocations are occuring.

### Acceptance Criteria

- [ ] `Font` class updated
- [ ] Manual testing proves no issues
- [ ] DPA results are good

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
