### ISSUE TITLE
🚧Create status check workflow to validate branch names

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#45]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

## Description

Create a status check workflow that utilizes the private **KinsonDigital** organization [BranchValidator](https://github.com/KinsonDigital/BranchValidator) GitHub action to validate various branches.

## Acceptance Criteria

**This issue is finished when:**

### **Workflows**
- [ ] Create workflow file named `validate-feature-branch-status-check.yml` to validate **feature** branch names.
    - Branch Name Example: feature/123-my-feature
    - [ ] The name of the workflow at the top should be _**✔️Validate Feature Branch Name Status Check**_
- [ ] Create workflow file named `validate-preview-feature-branch-status-check.yml` to validate **preview feature** branch names
    - Branch Name Example: preview/feature/123-my-feature
    - [ ] The name of the workflow at the top should be _**✔️Validate Preview Feature Branch Name Status Check**_
- [ ] Create workflow file named `validate-release-branch-status-check.yml` to validate **release** branch names
    - Branch Name Example: release/v1.2.3
    - [ ] The name of the workflow at the top should be _**✔️Validate Release Branch Name Status Check**_
- [ ] Create workflow file named `validate-preview-branch-status-check.yml` to validate **preview** branch names
    - Branch Name Example: preview/v1.2.3-preview.4
    - [ ] The name of the workflow at the top should be _**✔️Validate Preview Branch Name Status Check**_

### **Branch Protection Rules**
 - [ ] Status checks added for `master` branch
 - [ ] Status checks added for `develop` branch
 - [ ] Status checks added for `release` branches
 - [ ] Status checks added for `preview` branches
 - [ ] Status checks added for `preview feature` branches

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [ ] Issue linked to the proper project
- [ ] Issue linked to proper milestone

## Issue Dependencies

- KinsonDigital/BranchValidator#1

**Comment by CalvinWilkinson** [comment]
Closed without changes

**Reason:** This will be implemented by the issue below:

- #342
