### ISSUE TITLE
🚧Improve render system

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#451]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, **_Velaptor_** has a class named `RendererFactory`.  The idea of this factory was to make it easy to create a renderer for the use of rendering whatever it is that you want to render.   It also currently only has a single method named `CreateRenderer()`.  This single method creates an `IRenderer` object.   The purpose of this is to allow a user to create the renderer (which is a singleton) and then use it to render whatever they want.

The problem is that the current implementation of `IRenderer` which is an `internal` class is getting too large and difficult to maintain, manage, and test.  This can be greatly improved upon.
The idea is to create different `IRender` types.  Each one will be specialized for rendering different kinds of things.  For example, one could be for rendering textures, one for line primitives, and another for text, etc.

**Things To Do:**

1. Create a new render texture overload to make it easier to render atlas sub textures
    - Create window size reactable event
    - Update window size throughout the codebase where it is required
    - Convert AtlasSubTextureData to struct
    - Inside atlas data, organize the sub-texture data into groups by sub texture id
      This is going to be called inside of the texture renderer, so it needs to be performant for `IAtlasData.GetFrames()`
    - Create a new render texture overload that takes an IAtlasData for rendering

2. Create 5 different types of render interfaces and associated implementations. 
The idea is that the `RendererFactory` class can be used by a user to easily generate any of these renderer types as needed.

All of the current unit tests of course will need to be migrated to the correct implementations.  

**Benefits:**
- More control is given to the user.
- Ability to only use what is required.
- Greatly cleans up the code base
- Greatly improves testability
- Reduces changes for bugs.  There are more rendering capabilities coming in the future and this will help create a better path to do so.

**Things To Consider:**
> **Note**
> All of the renderer implementations need to be `internal sealed` so the users do not have access.

> **Note**
> All of the renderer implementations need to go into the `Velaptor.Graphics` namespace

> **Note**
> The `IBatchServiceManager` and `BatchServiceManager` types might not be needed anymore.  This is because
> they will not all be required in a single place like it is currently set up in the `Renderer` class.  Each renderer can simply pull in
> the required batch manager that is required via DI.

> **Note**
> The _**Velaptor Testing**_ application scene management system needs to be updated.  This is going to eventually become a major feature in **_Velaptor_** itself instead of a **_Velaptor Testing_** only feature.  The `IRenderer` needs to be removed
from the scene management system by removing the `IRenderer` parameter from the `Render()` method and replaced with a `FrameTime` parameter.

**List Of Render Types:**
- `ITextureRenderer`
- `IFontRenderer`
- `IRectangleRenderer`
- `ILineRenderer`

> **https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes**
- `IRenderer` removed
- `RenderFactory.CreateRenderer()` has been removed
- `RenderFactory` has been changed to sealed

### Acceptance Criteria

- [x] Create window size reactable event
    - This means a new subscription in the IRenderer implementation to receive the size of the window
- [x] Remove the `IAtlasData.GetFrame()` method - https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes
- [x] Refactor code that uses the term _**Atlas**_ - https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes
- [x] Improve the `IAtlasData.GetFrames` method
    - This involves grouping the data in the beginning in the `ctor`
- [x] Refactor code everywhere where the window size is required.
- [x] `ITextureRenderer`
    - [x] Create implementation
    - [x] Create unit tests
    - [x] Class is `internal sealed`
    - [x] Create new overloads for easy sprite sheet rendering using the signature below:
      - This will be base call that all other texture atlas calls will end up invoking
      ```cs
        private void RenderSubTexture(
            ITexture texture,
            IAtlasData atlasData,
            string subTextureId,
            uint frame,
            int x,
            int y,
            float size,
            float angle,
            Color color,
            RenderEffects effects,
            int layer = 0)
        {
        }
      ```
- [x] `IFontRenderer`
    - [x] Create implementation
    - [x] Create unit tests
    - [x] Class is `internal sealed`
- [x] `IRectangleRenderer`
    - [x] Create implementation
    - [x] Create unit tests
    - [x] Class is `internal sealed`
- [x] `ILineRenderer`
    - [x] Create implementation
    - [x] Create unit tests
    - [x] Class is `internal sealed`
- [x] `RendererFactory` changes
    - [x] Create a new method named `CreateTextureRenderer()`
    - [x] Create a new method named `CreateFontRenderer()`
    - [x] Create a new method named `CreateRectangleRenderer()`
    - [x] Create a new method named `CreateLineRenderer()`
- [x] `IRenderer` interface deleted and cleaned up
- [x] `Renderer` class deleted and cleaned up

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
