### ISSUE TITLE
🚧Update System.IO.Abstractions nuget package

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#455]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the NuGet package _**System.IO.Abstractions**_ from version _**v17.1.1**_ to the latest version as of the when this issue is picked up.

This is a major version update and comes with some API deprecations.  The warning _**CS0618**_ is displayed in the IDE when the NuGet package is updated.

**This warning states:**
Method `System.IO.Abstractions.IFileStreamFactory.Create(string, FileMode, FileAccess)` is obsolete: Use `IFileStreamFactory.New(string, FileMode, FileAccess)` instead.

**Files Affected:**
- `FontLoaderTests`
- `FontLoader`
- `AtlasLoader`
- `FontStatsService`

Update all of the uses of the deprecated method to use the new method instead.  All unit tests and the code need to be updated and passing.

**Additional Info:**
<img width="709" alt="image" src="https://user-images.githubusercontent.com/85414302/205878363-168c85c4-bed3-4132-a66a-dc1190d9454f.png">

### Acceptance Criteria

- [x] NuGet package _**System.IO.Abstractions**_ updated to latest version.
- [x] All code affected by the deprecated method updated.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Issue Dependencies

- KinsonDigital/CASL#115

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Issue put on hold.

**Reason:**
During testing, it was discovered that the **System.IO.Abstractions** library used for **_CASL_** has a dependency on version _**v13.2.33**_.  Since _**CASL**_ uses an older version of the library and this issue is to upgrade to the latest, running _**Velaptor**_ and up using the newest version of _**System.IO.Abstractions**_ instead of the version required by _**CASL**_.  This causes an error with the abstractions library when loading sound and crashes the application.

The _**CASL**_ library needs to be updated to the latest version of dotnet as well as _**System.IO.Abstractions**_ before this issue can be completed.

**Comment by CalvinWilkinson** [comment]
> Issue put on hold.
> 
> **Reason:** During testing, it was discovered that the **System.IO.Abstractions** library used for **_CASL_** has a dependency on version _**v13.2.33**_. Since _**CASL**_ uses an older version of the library and this issue is to upgrade to the latest, running _**Velaptor**_ and up using the newest version of _**System.IO.Abstractions**_ instead of the version required by _**CASL**_. This causes an error with the abstractions library when loading sound and crashes the application.
> 
> The _**CASL**_ library needs to be updated to the latest version of dotnet as well as _**System.IO.Abstractions**_ before this issue can be completed.

Hold status lifted. This was accomplished by doing various changes to **CASL** as well as various changes to the **CICD** system for **CASL**
