### ISSUE TITLE
🚧Make preview releases manual

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#46]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Currently, when changes are pushed to a _**release/v\*.\*.\***_ branch, it is deployed as a preview release.  
Refactor the _**release.yml**_ workflow file to make these type of releases manual.

The reason for this is because most of the time, preview releases will not be occurring.  A preview release is a decision made based on the changes to be released and is usually only done when there are a large amount of things to release.  Such as a major release going from _**v1.2.3**_ to _**v2.0.0**_.

Since preview releases are done inside the same workflow as the other type of releases, this might prove to be difficult.  Research how to have workflow inputs that can be chosen during a manual run.  This way the project maintainer can manually invoke the workflow and CHOOSE if they want it to be a preview release.

If this cannot be done, simply make preview releases a separate workflow.

### Acceptance Criteria

**This issue is finished when:**
- [x] Preview releases are done manually
- [x] Change _**release.yml**_ workflow to not enforce version types on release branches.
    - This is because release branches do not have to entail a preview release, which means the project file version does not have to be a preview version such as _**1.2.3-preview.4**_.  Currently it forces the version to be a preview version.  This means probably removing the **Validate Version Type** step.

### ToDo Items

- [x] ~~Draft pull request created and linked to this issue~~
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] ~~Unit tests have been written and/or adjusted for code additions or changes~~
- [x] ~~All unit tests pass~~
