### ISSUE TITLE
🚧Fix README broken logo link

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#461]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix the broken link to the logo in the main _**README**_ file for the project.  This link is only used when it is uncommented for preprocessing for nuget.org before a release.

**README Issue Location:**
``` diff
<!--PRE-PROCESSING-UNCOMMENT-START-->
<!--
- ![velaptor-logo](https://github.com/KinsonDigital/Velaptor/blob/release/v1.0.0/Documentation/Images/velaptor-logo.png)
+ ![velaptor-logo](https://raw.githubusercontent.com/KinsonDigital/Velaptor/release/v1.0.0/Documentation/Images/velaptor-logo.png)
-->
<!--PRE-PROCESSING-UNCOMMENT-STOP-->
```

The reason for the issue is that on nuget.org, images are only trusted under certain domains.

### Acceptance Criteria

- [x] README file updated
- [x] Last time the "fix" did not work.  This time, build the nuget package, manually setup the URL correctly, and manually upload it to NuGet to verify that it is working.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
