### ISSUE TITLE
🚧Cleanup mouse reactable code

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#469]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Clean up the mouse retractable code by combining all 3 mouse retractable types.

The mouse button, position, and wheel state are all separated into 3 reactable implementations.  This is not necessary.  Combining all of these into a single mouse state struct would be less code, easier to maintain, and reduce possible bugs in the future.

**Reactables To Combine Below:**
- `MousePositionReactable`
- `MouseButtonReactable`
- `MouseWheelReactable`

Combine all of these into a single reactable implementation named `MouseReactable`
Create a new readonly struct named `MouseData` that will be sent with the reactable push notifications.

For the GLWindow, the mouse data should be cached as a private field and used in each of the mouse events to update.  This will be the field data that you push as a notification to the `Mouse` object.

### Acceptance Criteria

- [ ] New `readonly` struct named `MouseData` created in the _**ReactableData**_ folder
- [ ] New reachable created with the name `MouseReactable`
- [ ] IoC updated
- [ ] `GLWindow` mouse events updated to use the new `MouseData` struct and to push notifications.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed with the decision not to implement.

**Reason:**
This is due to the change in direction with the current **_Reactable_** code. All of the _**Reactable**_ code will be getting replaced with the _**Carbonate**_ library with the issue below.

- #473
