### ISSUE TITLE
🚧 Add tweet action to prod and prev releases

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#47]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Try this out with the first release of **_v1.0.0-preview.1_**

This should be the last thing that is done to prepare for **_v1.0.0_**

The workflows and applications are still under construction
Add the ability for production and preview releases to automatically send a tweet about the release.
This will use the [Send Tween Action](https://github.com/marketplace/actions/send-tweet-action) GitHub action to do this.

Setup the production and preview releases to not send a tweet.  This is for the ability to turn off the tween during workflow testing.

### Acceptance Criteria

**This issue is finished when:**
- [x] Sends a tweet for production releases
- [x] Sends a tweet for preview releases
- [x] Preview releases should have an input with a 'true' or 'false' value that does or does not send a tweet upon release.
- [x] Create a repository secret that is used to turn on and off the tweeting step for production releases
    - This will be done by check the value using an `if` expression for the step

### ToDo Items

- [X] ~Draft pull request created and linked to this issue~
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] ~Unit tests have been written and/or adjusted for code additions or changes~
- [X] ~All unit tests pass~
