### ISSUE TITLE
🚧Fix small grammar issue in contributing document

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#470]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Make a small change in the _**CONTRIBUTING.md**_ document.

The change will involve making the sentence more specific as to prevent confusion or misinterpretation in the future.  

In addition, changes will need to be made so that the document is general and can be used in any repo without calling out the name of the repo.  

**Change To Implement:**

```diff
**Considerations:**

-The **Velaptor** team will merge changes that improve the library significantly. We will not merge changes that have narrowly-defined benefits or are breaking in some way. All contributions must also follow all other guidelines outlined in this document.

**Considerations:**

+ Only the **KinsonDigital** team will merge changes that improve the library significantly. We will not merge changes that have narrowly-defined benefits or are breaking in some way. All contributions must also follow all other guidelines outlined in this document.

```

### Acceptance Criteria

- [ ]  Contribution document updated.
- [ ]  Velaptor has been removed and replaced with KinsonDigital throughout the entire document.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without changes

**Reason:**
This is because the team has decided to make the contributing document project agnostic and create an organization-level document that all projects will use.
