### ISSUE TITLE
🚧Update checkout actions

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#479]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update all of the workflow checkout actions to the latest version which is _**v3**_.

**Reason:**
GitHub is moving away from **Node v12** to **Node v16**.  Due to this change, GitHub is updating all of its actions to support **Node v16** which is part of the process of moving away from _**Node v12**_.  

More info [here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

**What To Do:**

Update all of the **checkout** actions from _**v2**_ to _**v3**_.  These changes exist in all of the workflows. (yml files) in the project and can be located in the _**./.github/workflows**_ folder.

The update can be performed by updating these workflows.   Go into each workflow and look for `actions/checkout@v2` and change it to `actions/checkout@v3`. Please take a look at the example below for the **build-pr-status-check.yml** file.

**The Change:**
```diff
- actions/checkout@v2
+ actions/checkout@v3
```

### Acceptance Criteria

- [x] All workflows updated to use latest version of **checkout** action

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
