### ISSUE TITLE
🚧Minimize unsafe code

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#482]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Go through the entire code base and reduce the unsafe code as much as possible.

To also help make things more testable, create a new `internal` service to help abstract away the unsafe operations and provide all of the unsafe code work.  This service can then be used throughout the code base to replace unsafe code with the service code.

**Files with unsafe code:**
- GLFWInvoker
- FontService
- GLInvoker

### Acceptance Criteria

- [ ] New service created
    > **Note**  This class will not be tested.  Use the `[ExcludeFromCodeCoverage]` attribute on this class
- [ ] All areas converted from unsafe code as much as possible.
- [ ] Create unit tests to cover the `FontService` class

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
