### ISSUE TITLE
🚧Improve layered rendering

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#485]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

This will improve the layered rendering by introducing a final step to the layering process.  These changes will add the ability to make sure that rendering is done in a layered fashion between different _**render types**_.

**_Render types_** refers to the 4 different kinds of rendering below:
    - Textures
    - Fonts/text
    - Rectangles
    - Lines
    - and others added in the future . . .

### **Changes:**
The explanation below gives information related to what needs to change to improve the rendering system to enable more thorough layered rendering.

> **Note** More information can be found with the https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%94%ACresearch issue #452.
> Attached will also be a prototype used to research the concepts that will be added here.

1. Remove the `BatchServiceManager` interface and class
2. Rename all of the batching services to batching managers
    - This is replacing the word _**Service**_ with _**Manager**_ 
3. Create a new `internal readonly struct` named `ItemToRender`.
    - This struct will hold data used by renderers to figure out what needs to be rendered.  This will hold data such as the type of batch, layer to be rendered on, and the date/time when it was added to the batch.
4. Create a new `internal readonly struct<T>` named `RenderItem`.
    - This struct will hold a batch item of a particular type with extra metadata about the item.  The metadata is the date/time of when the item was updated, the layer to render on, and the batch item itself.
    - This will be used in the new `BatchManager` class as an array of a particular batch type.
5. Create a new `IMessage<T>` implementation named `BatchItemsMessage`
    - This will contain a pointer to the batch items to be rendered.
6. The layer property will be removed from the batch item structs.  This is not needed anymore due to the new `RenderItem` struct containing the layer values.

### Acceptance Criteria

- [x] Batching services refactored
    > **Warning** Do this before updating the batch manager implementations
    - [x] The `IBatchingService` interface renamed to `IBatchManager`
    - [x] The `TextureBatchingService` class renamed to `TextureBatchManager`
    - [x] The `FontBatchingService` class renamed to `FontBatchManager`
    - [x] The `RectBatchingService` class renamed to `RectBatchManager`
    - [x] The `LineBatchingService` class renamed to `LineBatchManager`
- [x] Create a new `internal enum` with the name `BatchType`
- [x] A new `internal readonly struct<T>` named `RenderItem` has been created.
- [x] ~~Each batch manager implementation refactored for new layered rendering~~
    > **Note** ~~Refer to the prototype attached in issue #452 as a guide~~

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Issue Dependencies

- #451

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Moved the batch managers (used to be batching services), to a new namespace
