### ISSUE TITLE
🚧Create more overloads for rendering rectangles

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#487]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add additional overloads for rendering rectangles.

### **Reason:**
This is to give people more options.

This will create a more thorough `private` base method in the `RectangleRenderer` class for all of the `public` facing overloads to utilize.

### Acceptance Criteria

- [ ] Create new readonly `struct` named `Gradient` that can hold the type of gradient as well as the start and stop colors.
- [ ] Render overloads for filled rectangles
    - [ ] `RenderFilled(int x, int y, int width, int height)`
      > **Note** Default fill color of white, no gradient, and no radius
    - [ ] `RenderFilled(Vector2 position, float width, float height)`
      > - Default fill color of white, no gradient, and no radius
    - [ ] `RenderFilled(Vector2 position, SizeF size)`
	  > **Note** Default fill color of white, no gradient, and no radius
    - [ ] `RenderFilled(Vector2 position, float width, float height, Color fillClr)`
	  > **Note** No gradient, and no radius
    - [ ] `RenderFilled(Vector2 position, SizeF size, Color fillClr)`
	  > **Note** No gradient, and no radius
    - [ ] `RenderFilled(Vector2 position, float width, float height, Color fillClr, CornerRadius cornerRadius)`
	  > **Note** No gradient
    - [ ] `RenderFilled(Vector2 position, SizeF size, Color fillClr, CornerRadius cornerRadius)`
	  > **Note** No gradient
    - [ ] `RenderFilled(Vector2 position, SizeF size, Gradient gradient)`
	  > **Note** Default color of white, no radius
    - [ ] `RenderFilled(Vector2 position, SizeF size, Gradient gradient, CornerRadius cornerRadius)`
	  > **Note** Default color of white,
    - [ ] `RenderFilled(Vector2 position, SizeF size, Color fillClr, Gradient gradient)`
	  > **Note** No radius
    - [ ] `RenderFilled(Vector2 position, SizeF size, Color fillClr, Gradient gradient, CornerRadius cornerRadius)`

- [ ] Render overloads for empty rectangles
    - [ ] `RenderFilled(int x, int y, int width, int height)`
	  > **Note** Default fill color of white, no gradient, no radius, and default thickness of 1
    - [ ] `RenderFilled(Vector2 position, float width, float height)`
	  > **Note** Default fill color of white, no gradient, no radius, and default thickness of 1
    - [ ] `RenderFilled(Vector2 position, SizeF size)`
	  > **Note** Default fill color of white, no gradient, no radius, and default thickness of 1
    - [ ] `RenderFilled(Vector2 position, SizeF size, int borderThickness)`
	  > **Note** Default fill color of white, no gradient
    - [ ] `RenderFilled(Vector2 position, float width, float height, Color fillClr)`
	  > **Note** No gradient, no radius, and default thickness of 1
    - [ ] `RenderFilled(Vector2 position, SizeF size, Color fillClr)`
	  > **Note** No gradient, no radius, and default thickness of 1
    - [ ] `RenderFilled(Vector2 position, SizeF size, Color fillClr, int borderThickness)`
	  > **Note** No gradient, and no radius 
    - [ ] `RenderFilled(Vector2 position, float width, float height, Color fillClr, CornerRadius cornerRadius)`
	  > **Note** No gradient, and default thickness of 1
    - [ ] `RenderFilled(Vector2 position, SizeF size, Color fillClr, CornerRadius cornerRadius)`
	  > **Note** No gradient, and default thickness of 1
    - [ ] `RenderFilled(Vector2 position, SizeF size, Color fillClr, CornerRadius cornerRadius, int borderThickness)`
	  > **Note** No gradient.
    - [ ] `RenderFilled(Vector2 position, SizeF size, Gradient gradient)`
	  > **Note** Default color of white, no radius, and default thickness of 1
    - [ ] `RenderFilled(Vector2 position, SizeF size, Gradient gradient, int borderThickness)`
	  > **Note** Default color of white, no radius 
    - [ ] `RenderFilled(Vector2 position, SizeF size, Gradient gradient, CornerRadius cornerRadius)`
	  > **Note** Default color of white, Default thickness of 1
    - [ ] `RenderFilled(Vector2 position, SizeF size, Gradient gradient, CornerRadius cornerRadius, int borderThickness)`
	  > **Note** Default color of white, 
    - [ ] `RenderFilled(Vector2 position, SizeF size, Color fillClr, Gradient gradient)`
	  > **Note** No radius, and default thickness of 1
    - [ ] `RenderFilled(Vector2 position, SizeF size, Color fillClr, Gradient gradient, int borderThickness)`
	  > **Note** No radius 
    - [ ] `RenderFilled(Vector2 position, SizeF size, Color fillClr, Gradient gradient, CornerRadius cornerRadius)`
      > **Note** Default thickness of 1
    - [ ] `RenderFilled(Vector2 position, SizeF size, Color fillClr, Gradient gradient, CornerRadius cornerRadius, int borderThickness)`

- [ ] Create `private` base method that can be used by all of the overloads.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
