### ISSUE TITLE
🚧Update font service

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#489]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the font service in the various ways below:

1. Create a new service called `FreeTypeService`.
    > **Note** This service will be used to hold helper methods related to _**FreeType**_ library operations. 
    > This is similar to the `OpenGLService` and the function that it provides.
2. Add a method to the `FreeTypeService` named `CreateGlyphMetric(nint facePtr)` that will get the metrics for a single glyph.
    > **Note** The contents of this method will wrap all of the functionality in the `unsafe` block in the `FontService.CreateGlyphMetrics()` method.
3. Add a method to the `FreeTypeService` named `HasKerning(nint facePtr)` that will get the metrics for a single glyph.
    > **Note** The contents of this method will wrap all of the functionality in the `unsafe` block in the `FontService.HasKerning()` method.
4. Add a method to the `FreeTypeService` named `GetFamilyName(nint facePtr)` that will get the name of the font family.
    > **Note** The contents of this method will wrap all of the functionality in the `unsafe` block in the `FontService.GetFamilyName()` method.
5. Add a method to the `FreeTypeService` named `GetFontStyle(nint facePtr)` that will return the font style.
    > **Note** The contents of this method will wrap all of the functionality in the `unsafe` block in the `FontService.GetFontStyle()` method.
6. Add a method to the `FreeTypeService` named `GetMetricHeight(nint facePtr)` that will return the face metric height.
    > **Note** The contents of this method will wrap all of the functionality in the `unsafe` block in the `FontService.GetFontScaledLineSpacing()` method.
7. Add an implementation to the `FreeTypeInvoker_OnError()` method.
8. Make use of the `FreeTypeInvoker_OnError()` method in the `HasKerning()` method with the exception.
9. Add a new method to the unsafe service that allows the copy of array data via a pointer.
    > **Note** The code that this will replace is the `Marshal.Copy()` method call in the `CreateGlyphImage()` method.
10. Inject the new unsafe service
11. Remove the `Dispose()` and `DisposeFace()` methods.
    > **Note** They are not used.

### Acceptance Criteria

- [ ] Added new method to the unsafe service.
- [ ] New service with the name `FreeTypeService` created with the following:
    - [ ] `CreateGlyphMetric(nint facePtr)` created
    - [ ] `HasKerning(nint facePtr)` created
    - [ ] `GetFamilyName(nint facePtr)` created
    - [ ] `GetFontStyle(nint facePtr)`  created
    - [ ] `GetMetricHeight(nint facePtr)` created
- [ ] Added following `FontService` improvements:
    - [ ] Added an implementation to the `FreeTypeInvoker_OnError()` method
    - [ ] Make use of the `FreeTypeInvoker_OnError()` method
    - [ ] `Dispose()` and `DisposeFace()` methods removed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
