### ISSUE TITLE
🚧Batch item perf improvements

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#494]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the performance of the `IsEmpty()` methods for all of the batch item types.

This improvement is using short circuit logical processing in the method.  What this means is instead of `&&` operators on all of the struct values to check if they are empty, use a not operation on the result of **_ALL_** of the of the struct values using `||` logic operators.

Using `||` allows the capability of being able to avoid the rest of the `bool` checks in the rest of the expression due to a `bool` check in the beginning of the expression returning `true`.  This capability comes with most programming languages.

To benefit from this, all that has to be done is to swap all of the `&&` operators with `||` operators, wrap the entire expression in parenthesis and then return the `NOT` result of the entire expression.

The order of the `||` checks need to be rearranged as well from most likely to be empty to least likely to be empty.  The order matters to increase the chances that an early short circuit logic check occurs which will improve the performance.

Also, change the `None` value to 0 for the `RenderEffects` enum.  This will reduce the logic requirements in the `IsEmpty()` methods and also improve perf slightly.  Refer to the setup below for the enum:

> **Note** This will require some changes to the values of the batch items structs and also what is _**considered**_ empty.
> A struct can always be created by the user using the `default` keyboard.  This will set all of the property values to the language defaults.  These defaults might not match the default values coming into the constructors or the logic inside of the constructors.  A good example of this is the `RectBatchitem`.  This struct considers the `width` to be a value of `1` to be considered empty.  But if the user choose to use the `default` keyword, this will use the value of `0`.  All of these default values that matter for the shaders need to be moved to the GPU buffer classes instead.

```diff
[Flags]
public enum RenderEffectsNew
{
-    None = 1,
+    None = 0,
-    FlipHorizontally = 2,
+    FlipHorizontally = 1,
-    FlipVertically = 4,
+    FlipVertically = 2,
    FlipBothDirections = FlipHorizontally | FlipVertically,
}
```

### **Perf Info:**
These `IsEmpty()` methods are highly used in the hot path of the rendering process within the game loop.  Performance benefits on 1000 items alone shows up to _**14.89%**_ performance increase.  1000 items is the current number used for the batch size.

![image](https://user-images.githubusercontent.com/85414302/213454066-d5846866-32f6-4a1d-85a2-f506ace22b98.png)

The performance project is attached below:
[PerfBenchmarkingProject.zip](https://github.com/KinsonDigital/Velaptor/files/10457090/PerfBenchmarkingProject.zip)

**Example:**
>**Note** This is the `IsEmpty()` method converted for the performance benefit.

```cs
// BEFORE PERF IMPROVEMENTS (ORIGINAL CODE)
public bool IsEmpty() =>
    TextureId == 0 &&
    Size == 0f &&
    Angle == 0f &&
    Effects is 0 or RenderEffects.None &&
    SrcRect.IsEmpty &&
    DestRect.IsEmpty &&
    TintColor.IsEmpty;

// AFTER PERF IMPROVEMENTS (NEW CODE)
public bool IsEmpty()
{
    // NOTE: This is probably the best order for early short circuit resolution
    return !(Angle != 0f ||
             Size != 0f ||
             Effects != RenderEffects.None ||
             TintColor.IsEmpty != true ||
             SrcRect.IsEmpty != true ||
             DestRect.IsEmpty != true ||
             TextureId != 0);
}
```

### Acceptance Criteria

- [ ] Improvements added to the `TextureBatchItem` struct.
    - [ ] Unit tests created to better test the `IsEmpty()` method in the `TextureBatchItem` struct.
        >**Note:** The tests are already written in the attached project.
    - [ ] `IsEmpty()` method improved
    - [ ] `ToString()` method removed
        > **Note** This is not required anymore due to the struct being a record struct
- [ ] `CornerRadius.IsEmpty()` method improved
- [ ] `RenderEffects` enum refactored
    - [ ] `IsEmpty()` method improved
- [ ] `FontGlyphBatchItem`
    - [ ] `IsEmpty()` method improved
        - [ ] Change the `Effects is 0 or RenderEffects.None` expression to `Effects == RenderEffects.None`
    - [ ] `ToString()` method removed
        > **Note** This is not required anymore due to the struct being a record struct
- [ ] `RectBatchItem`
    - [ ] Move the defaults to the associated GPU buffer class if applicable.
    - [ ] `IsEmpty()` method improved
- [ ] `LineBatchItem`
    - [ ] `IsEmpty()` method improved

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without implementation

**Reason:**
This was already implemented in release for version v1.0.0-preview.16
