### ISSUE TITLE
🚧Improve GPU buffering

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#497]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve GPU buffering by automatically resizing the buffer when it gets full.

**Benefits:**
This will change how batch management works.  Before, when the _**batch**_ was full, the data items needed to be used before anymore could be used again.  To be able to do this, they had to be rendered and put to _**use**_ before freeing them up for the new items being added.  Basically, the system acted like an object pool.  This worked well but down side was that the code became more complicated.  This caused issues with having to maintain the state of the entire batch of items and it would cause additional renders to occur just to free up the data items for new renders.

This also has a down side because there is know way to know the libraries users implementation.  There is the chance that they could max out the batch very quickly and those extra renders could cause performance issues.  These new changes will simplify code, testing, and also reduce renders.

**What to implement:**
The size of the batch can start out at 1000, but as an item is added to the batch manager, the batch type will be checked to see if it is full.  If it is full, the batch will be increased by 50% while preserving the data that is already still ready for rendering.  After the resize, the new item being added can be added to the newly added free space.

### Acceptance Criteria

- [ ] Each batch type can be independently resized once the batch is full.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
