### ISSUE TITLE
🚧Improve various types

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#504]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Change the class below to `internal`:
    - `PullResponses`

Convert the following types to `readonly` structs:
    - `DisposeSoundData`
    - `DisposeTextureData`
    - `KeyboardKeyStateData`
    - `MouseStateData`
    - `ViewPortSizeData`
    - `WindowSizeData`

This class was not meant to be part of the public API.

### Acceptance Criteria

- [x] `PullResponses` converted to `internal`
- [x] Following types converted into structs
    - [x] `DisposeSoundData`
    - [x] `DisposeTextureData`
    - [x] `KeyboardKeyStateData`
    - [x] `MouseStateData`
    - [x] `ViewPortSizeData`
    - [x] `WindowSizeData`

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
