### ISSUE TITLE
🚧Move and improve scene system to Velaptor

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#506]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Take all of the code from the **VelaptorTesting** related to scenes and move it to the **Velaptor** project.

**Reason:**
This will give users the ability to help manage scenes in the game and help with making games easier.

This will also require changes to the testing application due to the code migrating to **Velaptor**.

### Acceptance Criteria

- [x] Scene code migrated to Velaptor
- [x] VelaptorTesting refactored for changes

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
