### ISSUE TITLE
🚧Update workflows to use env files

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#511]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update all workflows to use env files instead of the `set-output` command.

This is getting deprecated by GitHub and will be disabled soon.  This will end up breaking the CI/CD pipeline and needs to be addressed.

Info on how to use env files can be found [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

[This is the warning](https://github.com/KinsonDigital/Velaptor/actions/runs/4105239512) displayed in one of the status check logs

### Acceptance Criteria

- [x] Workflows all updated to use env file

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
