### ISSUE TITLE
🚧Refactor collection

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#515]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Go through the entire code base and refactor all of the uses of `ToReadOnlyCollection()` to `AsReadOnly()`
Anything that does go convert to `ReadOnlyCollection`, use the interface `IReadOnlyCollection` instead.

Go through all of the lists in the code base and refactor to `IReadOnlyCollection` or of the other `IReadOnly` interfaces if the data should not be mutated.

**Reason:**
Using the `AsReadOnly()` is much more performant and is more aligned to true immutable collections.

### Acceptance Criteria

- [x] All collections that use the type `ReadOnlyCollection<T>` are converted to `IReadOnlyCollection<T>`
    > **Note** Apply this to any of the `IReadOnly` type arrays
- [x] Remove all `ToReadOnlyCollection()` extension methods and replace uses with `AsReadOnly()`

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
