### ISSUE TITLE
🚧Add codecov YAML file

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#526]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a codecov YAML file to the root of the repo.

**Reason:**
This is to get the code coverage to be used as a status check before PRs can be merged as well as results in the PR comments.

You can refer to the [codecov docs](https://docs.codecov.com/docs/commit-status) related to status checks for more info.

### Acceptance Criteria

- [x] A `codecov.yml` file has been added to the project
- [x] The `codecov.yml` file added to the **Solution Items** folder

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
