### ISSUE TITLE
🚧Fix issues and improve PR template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#53]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Fix the issues highlighted in the screen shot below for the **preview to release** PR template.

![image](https://user-images.githubusercontent.com/85414302/133184632-c0cc78fe-6143-4359-b2dc-a63f51e2cc64.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] PR template issues fixed

### ToDo Items

- [x] ~Draft pull request created and linked to this issue~
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] ~Unit tests have been written and/or adjusted for code additions or changes~
- [X] ~All unit tests pass~

**Comment by CalvinWilkinson** [comment]
Re-opened due to premature closing of the PR.  This should only be closed once the PR has been code reviewed and approved.
