### ISSUE TITLE
🚧Remove repo related documents

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#530]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Remove repo specific docs that exist at the org level. 

Update link in READme to point to the org level contribution document.

### Acceptance Criteria

- [x] Contributing
- [x] Code_of_Conduct
- [x] ./documentation/branching.md
- [x] Table of Contents folder
- [x] EnvironmentSetup folder

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
