### ISSUE TITLE
🚧Update twitter link

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#535]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update URL section of the markdown links in the _**README.md**_ file to point to the twitter logo located in the **_.github_** org repo.

[Here](https://github.com/KinsonDigital/.github/tree/master/Images) is the location of the logo. 

The link URL section below is what you should update the URLs to _**https://raw.githubusercontent.com/KinsonDigital/.github/master/Images/twitter-logo-16x16.svg**_.

### Acceptance Criteria

- [x] twitter logo removed from the repo (if it exists)
    > **Note** Usually it exists in the _**./Documentation/Images/**_ folder
- [x] twitter link updated
    > **Note** There should be 2 twitter logos to update.  One for _**Calvin**_ and one for **Kristen** and is located in the _**README.md**_ file.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
