### ISSUE TITLE
🚧Remove documentation docs from repo

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#538]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Delete various files form the _**Documentation**_ folder.

Delete the following:
- EnvironmentSetup folder
- Branching.md
- TableOfContents.md
- Images folder:
    - Both branching diagrams

Also, update the documentation section of the README file to:
🚧 Documentation website currently under construction 🚧

### Acceptance Criteria

-[ ] files have been deleted
-[ ] documentation has been updated 

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
