### ISSUE TITLE
🚧 Project Item - Add ability to check and automove required binaries from runtimes folder

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#54]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Currently, the testing application and anything consuming the Velaptor library, requires that various libraries are either in the executable location of the library, or in the system as a whole.

Change this for each required library so the application can run independent on what is installed in the system, and can automatically pull the required libraries from the nuget package _**runtimes**_ folder and place them in the same location as the executing **Velaptor** library location.

Currently, the **_soft_oal.dll_** library is in the runtimes folder but is required to be in the same location as the executable.  This will also guarantee the exact library needed instead of loading the system wide version of OpenAL

**NOTE:**
Currently the **CASL** project is doing this.  Reference this project to help implement this ability.

**Related Classes:**
These should probably all go in the **NativeInterop** namespace
- [x] NativeLibPathResolver
- [x] IFilePathResolver
- [x] IPlatform
    - Exists in Velaptor but needs to be updated with the CASL version
- [x] Platform
- [x] NativeMethods
- [x] IPath
- [x] IFile
- [x] IApplication
- [x] IDependencyManager
- [x] NativeDependencyManager
- [x] OpenALDependencyManager
- [x] ~ILibrary (This is a maybe)~
    - This actually does not need to move over.  This is for loading actual libraries into memory

- [x] Add all associated tests for new file implementations

### Acceptance Criteria

**This issue is finished when:**
- [x] ~Velaptor auto checks and copies file from **_runtimes_** folder upon execution every time it is ran~
- [x] Application does not crash and runs properly when library is properly placed

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] ~Unit tests have been written and/or adjusted for code additions or changes~
- [x] All unit tests pass

**Comment by CalvinWilkinson** [comment]
The `ILibrary` and `ILibraryLoader` interfaces and associated implementations are not needed in **Velaptor** right now

**Comment by CalvinWilkinson** [comment]
After implementing the majority of the code from CASL to be able to load the OpenAL library pointer from the correct location, it was discovered that this did not need to be done because CASL did this itself. 

What was discovered is that CASL did not start doing this until sometime between the preview 4 and preview 10 release.  A simple update in Velaptor to preview 10 simply fixed the issue.
