### ISSUE TITLE
🚧Fix issue with default font setup

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#541]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue where an access permissions exception to load windows fonts for times new roman is thrown.  This occurs when trying to load creating a new `Window` implementation object.  During the creation of the `Window` object, the content loader object is created which eventually checks for default fonts being setup.  Since the content folder does not exist, it attempts to load the equivalent font from the _**Windows**_ OS fonts instead.

The problem is when the **Content** directory does not exist, the content loader checks this and sees that no default fonts exist so it then attempts to load the OS fonts.  This is always the case when creating a new **Velaptor** project because the **Content** directory does not exist.  This is not a good user experience.

**Suggested Fix:**
Change the behavior of the `SetupDefaultFonts()` method to check if the `rootDirPath` is an OS path. If it is an OS path, do not attempt to save the embedded font resources into the directory path because it tries to save over the OS fonts.  This is where the permission issue comes in.  Instead just exit the method.

### Acceptance Criteria

- [x] The `FontLoader` is refactored to prevent saving over the OS fonts.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
