### ISSUE TITLE
🚧Abstract assembly code

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#544]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Abstract away the dotnet `Assembly` class related code in the application by creating a new service named `AssemblyService`.

**Purpose:**
This will give the ability to make the `EmbeddedFontResourceService` and `AppService` testable.

**Service Creation:**
1. Add a method named `GetExecutingAssemblyLocation()` which will return the location of the executing assembly.
2. Add a method named `GetManifestResourceNames()` which will return a `string[]` which is a list of the embedded resources.
3. Add a method named `GetManifestResourceStream()` which will return a `Stream` object to an embedded resource.

**Once the service is created:**
- Inject service into the `EmbeddedFontResourceService` class and refactor the code to use the service instead.
- Inject service into the `TextResourceLoaderService` class and refactor the code to use the service instead.
- Inject service into the `AppService` class and refactor the code to use the service instead.

Make sure to write tests for the services mentioned above.

### Acceptance Criteria

- [ ] New service `AssemblyService` created
  > **Note** This will have code coverage excluded
- [ ] `EmbeddedFontResourceService` service refactored for new `AssemblyService`
	- [ ] Unit tests created
- [ ] `TextResourceLoaderService` service refactored for new `AssemblyService`
	- [ ] Unit tests created
- [ ] `AppService` service refactored for new `AssemblyService`
	- [ ] Unit tests created

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
