### ISSUE TITLE
🚧Update codecov YML file

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#549]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Make changes to the `codecov.yml` file as shown below:

```diff
coverage:
  status:
    project:
      default:
        # basic
-       target: auto
+       target: 85%
        threshold: 0%
```

### Acceptance Criteria

- [x] `codecov.yml` file updated
- [x] Issues created to get the `codecov.yml` files in the organization updated the same way
  > **Note** You can easily find all of the `codecov.yml` files across the organization using GitHub search.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
