### ISSUE TITLE
🚧Improve PR Templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#55]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Make improvements to the PR templates to make them more clear and to better align with all of the new changes to the workflow and development process of the project.

### Acceptance Criteria

**This issue is finished when:**
Make the following changes below for the **_preview-release-to-release.md_** PR template
- [ ] Update the following section below
- [ ] Rename the _**preview-release-to-release.md**_ file to _**preview-to-release.md**_
Before:
``` md
<!--
    !! NOTE !! - ONLY PROJECT OWNERS AND MAINTAINERS MANAGE PRODUCTION PREVIEW RELEASE PULL REQUESTS
    If you have contributions to make, use the "feature-to-develop" pull request template.
-->
```
After:
``` md
<!--
    !! NOTE !! - ONLY PROJECT OWNERS AND MAINTAINERS MANAGE PULL REQUESTS FOR PRODUCTION AND PREVIEW RELEASES
    If you have contributions to make, use the "feature-to-develop" pull request template.
-->
```
### **Update the optional checklist:**

Before:
``` md
- [ ] My change requires a change to the documentation.
- [ ] I have added tests to cover my changes.
  - [ ] I have updated the documentation accordingly.
  - [ ] If changes to documentation have been made, the PR contains the **documentation** label.
```
After:
``` md
**Kind of Change(s):**
- [ ] Bug Fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Workflows (CI/CD)

**Documentation:**
- [ ] My changes require a change to the documentation.
- [ ] If changes to documentation are required, the PR contains the **documentation** label.

**Testing:**
- [ ] My changes require changes to unit tests
  - [ ] I have added tests to cover my changes.
```
Update items in the **Required Checklist** section
- [ ] Fix the version syntax for the first item
- [ ] Change the 3rd item
    - Change the word 'exists' to 'exists'
- [ ] Remove item 4
    - This is not needed anymore because the workflows enforce this
- [ ] Change the line below

Before:
``` md
- 💡 Every change to a PR will run a status check to confirm that the version has the correct syntax and does not already exist in the repository.
```
After:
``` md
- 💡 Every change to a PR will run a status check to confirm that the version has the correct syntax, a tag does not exist, and that it has not already been published to nuget.org
```
- [ ]  Fix the version example as well as the project file XML example in item 7

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (low priority, medium priority, or high priority)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] ~Unit tests have been written and/or adjusted for code additions or changes~
- [X] ~All unit tests pass~

**Comment by CalvinWilkinson** [comment]
This was done with issue #53
