### ISSUE TITLE
🚧Add auto content folder creation

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#550]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the ability to automatically create the content folders in the same directory as the application.

**The folders to auto create:**
- Atlas
- Graphics
- Sounds

> **Note** The _**Fonts**_ folder is already created when creating the default fonts.

**Purpose:**
This improves the user experience by not requiring that the user go manually create the folders before adding content to them.  This is mostly a benefit for users who are new to Velaptor and just getting started.  This also improves the tutorials on the website by minimizing steps.

### Acceptance Criteria

- [x] The _**Atlas**_ folder is auto created on app startup
- [x] The _**Graphics**_ folder is auto created on app startup
- [x] The _**Sounds**_ folder is auto created on app startup
- [x] Issue created to update the Velaptor website tutorials

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
