### ISSUE TITLE
🚧Create image loader

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#551]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create an image loader class.  

**Purpose:**
To give the users the ability to load images manually during runtime. 

**Use Case:**
The loader will return a struct of type `ImageData`.  This will give the users the ability to manually manipulate the image during runtime.  They can then use this `ImageData` to create a new `Texture` object used for rendering.  This will basically give the user the ability to manipulate the image before rendering it.

**`ImageLoader` Features:**
- Loads images by pointing to any file on disk.
- Loads images using content relative paths
  > **Note** This means if a full path is not used, then it is assumed that it is a path to the _**Content/Graphics**_ content directory.  If the path is _**NOT**_ a fully qualified path then an extension is not required due to the path representing a path to the content directory.

**`ImageData` Features:**
Add the following features to the `ImageData` struct
- Add a method to the struct to flip the image horizontally
- Add a method to the struct to flip the image vertically
- Add `bool` property to the struct named `IsFlippedHorizontally`
- Add `bool` property to the struct named `IsFlippedVertically`

### Acceptance Criteria
- [x] `ImageLoader` class created.
  - [x] Loads images by pointing to any file on disk.
  - [x] Loads images using relative content paths
- [x] Features added to the `ImageData` struct
  - [x] Method added to the struct to flip the image horizontally
  - [x] Method added to the struct to flip the image vertically
  - [x] `bool` property added to the struct named `IsFlippedHorizontally`
  - [x] `bool` property added to the struct named `IsFlippedVertically`
- [x] Create an issue to create documentation for the website

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
