### ISSUE TITLE
🚧Fix workflow step name

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#553]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix the name of the _**Run PR Status Check**_ step in the **_prev-feature-pr-status-check.yml_** file.

```diff
-    - name: Run Feature PR Status Check
+    - name: Run Preview Feature PR Status Check
      run: dotnet cicd PreviewFeaturePRStatusCheck --pull-request-number ${{ steps.get-pr-number.outputs.pr-number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Acceptance Criteria

- [x] Step name fixed for preview feature pr status check workflow

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
