### ISSUE TITLE
🚧Update Readme

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#555]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description
We are in the process of rationalizing ReadMe across all GitHub Actions (GHA). This includes:

Making sure all sections are in this order:
  - Logo
  - Repo Name
  - Badges
  - Notice
  - About
  - Features
  - Documentation and Resources
  - Contrib/Funding
  - Maintainers
  - License

### **Details of the changes to the sections are below:**

**Documentation**
- Change wording to:
  - Full API documentation and tutorials can be found at [docs.velaptor.io](https://docs.velaptor.io)

**Further Resources**
- Remove first bullet point 
- Keep CASL and Silk bulletpoints
- Remove Discord bullet point
- Combine with Documentation to look like this: Full API documentation and tutorials can be found at [docs.velaptor.io](https://docs.velaptor.io). Velaptor powered by [CASL](https://github.com/KinsonDigital/CASL) and [Silk.NET](https://github.com/dotnet/Silk.NET).

**Contribution**
- Change title to Contributing
- Click [here](https://github.com/KinsonDigital/.github/blob/master/docs/CONTRIBUTING.md) to learn how to contribute your time.
- Click [here](https://github.com/sponsors/KinsonDigital) if you are interested in contributing your funds via one-time or recurring donations.

**Maintainers**
- Move section below Contributing and above License
  
**Other**
 - Double checking spelling/grammar
 - Making wording the same in similar sections
 - Make sure "Back to the Top" link is on the right
 - Remove any TODO comments
 - Verify all links work and point correctly

### Acceptance Criteria

- [x] Make sure all sections are in this order:
    - [x] Logo
    - [x] Repo Name
    - [x] Badges
    - [x] Notice
    - [x] About
    - [x] Features
    - [x] Documentation and Further(other) Resources are combined
    - [x] Contrib/Funding (after combined like in lib section)
    - [x] Maintainers
    - [x] License
  - [x] Update **Documentation Section**
    - [x]  Wording changed
  - [x] Update the **Contribution Section**
    - [x] Title changed
    - [x] Link to contributing doc added
    - [x] Link to Github sponsors added
 - [x] Spelling/grammar checked
 - [x] "Back to the Top" link is on the right
 - [x] TODO comments removed
 - [x] All links work and point correctly

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
