### ISSUE TITLE
🚧Create new texture renderer overload

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#559]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a new overload method for the `ITextureRenderer` interface and `TextureRenderer` class.

**Overload Method Signature:**
```cs
ITextureRenderer.Render(ITexture texture, int x, int y, float angle, int layer = 0);
```
> **Note** The additional parameter is the angle.

**Reason:**
This was done because there is currently only one method overload that contains an angle parameter and that is the largest signature.  This is not ideal when the user only wants to  rotate and position and object without all of the other kinds of functionality that the largest signature provides.

### Acceptance Criteria

- [x] New overload method added

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
