### ISSUE TITLE
🚧Remove nuget package metadata

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#567]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

In NuGet metadata data properties in the project properties, remove the _**Release Notes:**_ field data.

![image](https://user-images.githubusercontent.com/85414302/226349799-a2b2df5a-1a1d-428d-b798-14eab2295ce6.png)

### Acceptance Criteria

- [x] NuGet metadata removed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
