### ISSUE TITLE
🚧Improve object heap allocations for content loading

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#57]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

It has been discovered that there is some large heap allocations occurring due to the way fonts and sounds are loaded.  This is due to closures that are currently implemented.  Improve these large heap allocations.

**Allocations Detected In Rider:**
![image](https://user-images.githubusercontent.com/85414302/133780749-412e53c9-a427-4d1c-87d1-6c994cdbdb14.png)

Refer to [this article](https://www.jetbrains.com/help/rider/2021.2/Fixing_Issues_Found_by_DPA.html#method-group-instead-of-lambda) to help resolve the issue.

### Acceptance Criteria

**This issue is finished when:**
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [x] Priority label added to issue (low priority, medium priority, or high priority)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass
