### ISSUE TITLE
🚧Fix grammar issue in bug issue template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#59]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

In the _**Operating System**_ section of the _**Bug Issue Template**_, fix the grammar issue for the field title about the OS that the bug occurred on.

**It should be the value below:**
If you now what OS version the bug occurred on, enter the OS version here

**Incorrect Grammar Screenshot:**
![image](https://user-images.githubusercontent.com/85414302/133952843-129c4f3a-8cb2-46f8-a60a-487ffe595ea9.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] Grammar issue fixed

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] ~Unit tests have been written and/or adjusted for code additions or changes~
- [X] ~All unit tests pass~
