### ISSUE TITLE
🚧Create new texture render overloads

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#594]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create new texture render overloads that take a `System.Numerics.Vector2` instead of `int x` and `int y` for the position data.

Currently, there are several overloads that only take 2 `int` params for position data.  Make copies of all of those method signatures and use the `Vector2` type instead.

### Acceptance Criteria

- [x] Method created with `Vector2` with the method signature below
    `void Render(ITexture texture, Vector2 pos, int layer = 0)`
- [x] Method created with `Vector2` with the method signature below
    `void Render(ITexture texture, Vector2 pos, float angle, int layer = 0)`
- [x] Method created with `Vector2` with the method signature below
    `void Render(ITexture texture, Vector2 pos, RenderEffects effects, int layer = 0)`
- [x] Method created with `Vector2` with the method signature below
    `void Render(ITexture texture, Vector2 pos, Color color, int layer = 0)`
- [x] Method created with `Vector2` with the method signature below
    `void Render(ITexture texture, Vector2 pos, Color color, RenderEffects effects, int layer = 0)`

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
