### ISSUE TITLE
🚧Fix security issue with exception serialization

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#598]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix a security issue with deserialization of the `BufferNotInitializedException`.  More info on this can be found with the sonar cloud scan in the link below.

[Sonar Scan Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=KinsonDigital_Velaptor&file=Velaptor%2FOpenGL%2FExceptions%2FBufferNotInitializedException.cs&fileUuid=AYdXFisIPXfnl2l3dV5f&tab=code)

### Acceptance Criteria

- [ ] Security issue fixed with `BufferNotInitializedException` class.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Issue Closed without changes.

**Reason:** After further investigation, it was decided that this is not a security risk.  This is due to the fact that the exception does not contain any additional properties outside of the usual `Exception` properties.  Due to this, no security risk is imposed on the consumer side due to properties available to build custom logic around to give the attacker an advantage.
