### ISSUE TITLE
🚧Remove release notes solution item

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#60]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

In the **SolutionItems** folder, remove the **RELEASENOTES.md** file.

![image](https://user-images.githubusercontent.com/85414302/133983153-84aa56ef-54be-4748-b549-02acd0441719.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] Solution item removed

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] ~Unit tests have been written and/or adjusted for code additions or changes~
- [X] ~All unit tests pass~
