### ISSUE TITLE
🚧Fix logo in readme

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#603]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix the issue with the logo not showing for the NuGet package when viewing the readme in nuget.org.

This is due to the face of the URL of the image being a local relative path to the image in the repository instead of a fully qualified URL to the image as raw GitHub data from GitHub.

Change the URL to be a fully qualified URL to the image on the _**release/v1.0.0**_ branch as raw image data from GitHub.

Refer to change below:
```diff

<div align="center">
-    <a href="#"><img align="center" src="./Documentation/Images/velaptor-logo.png" height="96"></a>
+    <a href="#"><img align="center" src="https://raw.githubusercontent.com/KinsonDigital/Velaptor/release/v1.0.0/Documentation/Images/velaptor-logo.png" height="96"></a>
    <br />
  
</div>
```

### Acceptance Criteria

- [x] URL in readme file fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
