### ISSUE TITLE
🚧Update branch validation workflows to work with double digits

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#61]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Currently, the preview and production release branch validation status check workflows do not work with major, minor, patch, or preview numbers that are 2 digits in size or larger.

Refer to the CASL project to see the fix that has been put into place.

### Acceptance Criteria

**This issue is finished when:**
- [x] The _**validate-preview-release-branches-status-check.yml**_ workflow has been updated
- [x] The _**validate-prod-release-branches-status-check.yml**_ workflow has been updated

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] ~Unit tests have been written and/or adjusted for code additions or changes~
- [X] ~All unit tests pass~

### Related Work

- KinsonDigital/CASL#53
