### ISSUE TITLE
🚧Setup renovate to use org level preset

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#617]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Set up the _**renovate**_ configuration to use the **_renovate_** organizational level preset.  This can be done by updating the **_renovate.json_** file to the setup below.

Go [here](https://docs.renovatebot.com/config-presets/#github) for the renovate docs on the _**extends**_ syntax required to **point** this config to the org level config.

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": ["github>KinsonDigital/.github//config/renovate-config.json"],
  "baseBranches": ["release/v1.0.0"]
}
```

> **Note** We need to remember that once we change to the new branching model, the **baseBranches** value will have to change to _**master**_.

### Acceptance Criteria

- [x] _**renovate.json**_ config updated to use the org-level preset.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
