### ISSUE TITLE
🚧Add texture packer support

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#619]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add [Texture Packer](https://www.codeandweb.com/texturepacker) support.

This is adding the ability to process JSON (Array) texture packer data.  There are many types of data that can be output by texture packer, but this will only support JSON data output.  The data format will have to be analyzed to understand what can and cannot be supported.  The hope is that no matter what settings or image formats the user chooses, the data output will be the same.

Currently, there is a very simple JSON format that is supported by Velaptor and is only for Velaptor.  We want to keep this intact just in case somebody wants to take advantage of it or simply does not want to use TexturePacker.

The hope is that we can support the JSON (Array) data output format without worrying about what kinds of sheet settings the user uses.

> **Note** Another option is to a custom exporter for texture atlas that would conform the data to exactly what we need but this is only if we have to.
> Go to [Custom Exporter Docs](https://www.codeandweb.com/texturepacker/documentation/custom-exporter) fore more info.

### **How to implement:**
One idea is to possibly make another implementation of the `IAtlasLoader<T>` interface.  The new interface implementation could be a class named `TexturePackerLoader`.  This new implementation would use a different interface besides `IAtlasData` which would be data returned from **TexturePacker**.

This will require adding a new method to the `IContentLoader` interface and `ContentLoader` class with the name `LoadTexturePackerAtlas()`.  This method is what the user would use to load texture packer atlas data instead of Velaptor atlas data.  This will also require adding an equivalent method for unloading texture packer atlas data.

### Acceptance Criteria

- [ ] A new interface created for holding texture packer atlas data
- [ ] A new `ILoader<T>` implementation created to load texture packer atlas data
- [ ] A new method named `LoadTexturePackerAtlas` added to the `ContentLoader` class and `IContentLoader` interface
- [ ] A new method named `UnLoadTexturePackerAtlas` added to the `ContentLoader` class and `IContentLoader` interface

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
