### ISSUE TITLE
🚧Update feature PR status check workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#62]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the _**feature-pr-branches-status-check.yml**_ workflow to match changes made in the **CASL** project.

### Acceptance Criteria

**This issue is finished when:**
- [x] The _**feature-pr-branches-status-check.yml**_ workflow updated

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] ~Unit tests have been written and/or adjusted for code additions or changes~
- [X] ~All unit tests pass~

### Related Work

- KinsonDigital/CASL#53
