### ISSUE TITLE
🚧Improve font rendering and text measuring performance

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#626]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the performance and reduce the memory allocations of the font rendering and text measuring process.

The font rendering process currently generates a decent amount of allocations due to the manipulation of text and its measuring in the text rendering process.  These allocations can be reduced by simply converting the incoming text characters to a `Span<char>` type and using the span instead of the `string` directly. 

> **Warning**  This needs to be dealt with with great care.  The font/text rendering system is complicated and brittle due to the nature of how the rendering works.  Rendering font glyphs has a lot of moving parts and can easily be affected when changing code.  Make sure to perform lots of manual testing and rely on unit tests to help with this.

The areas of interest will be the `private` method named `RenderBase()` in the `FontRenderer` class and the `Measure()` method in the `Font` class.  Anywhere in the `Font.Measure()` call stack needs to be analyzed and improved.  Most likely, introducing the `Span<char>` type will have a snowball effect throughout the system.

> **Note** Pay attention to how line endings will be processed.  Look into normalizing the endings when converting from a `string` to a `Span<char>` by simply filtering out the '\r' and '\r\n' line endings.
> Unfortunately, our JetBrains account does not come with _**dotMemory**_ as a tool to use to measure allocations. Use Visual Studio instead.  Make sure to profile only a single piece of text in a single scene as a baseline first.  

### Acceptance Criteria

- [ ] Base-line measurements collected
    - [ ] Base-line and new collection results attached to this issue
- [ ] `FontRenderer` class improved
- [ ] `Font` class improved

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Issue Dependencies

- #615 

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
