### ISSUE TITLE
🚧Create unit tests for extension methods

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#627]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create unit tests for all of the extension methods in the `TextBoxExtensions` file.  

Use existing code for a guide on the style, layout, and practices used for unit tests. 
If you have any questions, please reach out!!  😀

> **Note**
> 1. Please follow the pattern of how to creating unit tests.  Refer to other tests as a guide.
> 2. When it comes to writing assertion code, please use the [FluentAssertions API](https://fluentassertions.com/introduction)
> 3. We are in the middle of migrating from [Moq](https://www.devlooped.com/moq/) to [NSubstitute](https://nsubstitute.github.io/) for our mocking code.  Please write your mock code using NSubstitute if mocking is required.
> 4. Please follow our [Contribution Guide](https://github.com/KinsonDigital/.github/blob/main/docs/CONTRIBUTING.md)
> 5. Join our [discord community](https://discord.gg/qewu6fNgv7) to ask questions and hang out!!

### Acceptance Criteria

- [x] Extension methods created for methods in the `TextBoxExtensions` class.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by map-b** [comment]
Hello, I would like to take this. Thanks!

**Comment by CalvinWilkinson** [comment]
@map-b It has been assigned.  If you have any questions, please don't hesitate to ask.
