### ISSUE TITLE
🚧Update tweet message for preview and prod releases

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#63]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the message for the tweet broadcast for the preview and production release workflows

### Acceptance Criteria

**This issue is finished when:**
- [x] preview workflow updated
- [x] production workflow udpated

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] ~Unit tests have been written and/or adjusted for code additions or changes~
- [X] ~All unit tests pass~

### Related Work

- KinsonDigital/CASL#53
