### ISSUE TITLE
🚧Remove interface

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#633]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Remove the interface `IContentUnloadable` from the code base.  This is an old file that somehow got left behind but is unused. 

> **Note**
> This is not a breaking change.
> This is because it is not used anywhere in the project, if somebody is using it it will not
> do anything.  If somebody is using it for their own thing, they can easily recreate the interface in their own code.

### Acceptance Criteria

- [x] The `IContentUnloadable` interface/file is removed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
