### ISSUE TITLE
🚧Update workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#642]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update all of the workflows that use reusable workflows to the latest version of the _**Infrastructure**_ repository.

1. Also, update the name of the `run-release` job in the _**release.yml**_ workflow.

Update the name as below:
```diff
- name: Performing ${{ inputs.release_type }} Release of ${{ vars.PROJECT_NAME }} ${{ inputs.dry-run == true && '(Dry Run)' || '' }}
+ name: Performing ${{ inputs.release_type }} Release of ${{ vars.PROJECT_NAME }} (${{ needs.determine_build_config.outputs.build-config }})
```

2. Remove the `determine_build_config` job and hard code the `build-config` arg value to _**Debug**_ for the _**build-csharp-project**_ reusable workflow reference.
> **Note** Do this for both the build and test status check workflows

> **Warning** Pay attention to the VSCode tooling (extension) to see if it lints
> anything that is not working.  New workflow inputs and breaking changes exist.

### Acceptance Criteria

- [x] All reusable workflow references updated to latest **Infrastructure** version
- [x] Job name updated in the _**release.yml**_ workflow
- [x] Update the build status check workflow
    - [x] The `determine_build_config` job removed
    - [x] The `build-config` reusable workflow input value hard code to **Debug**
- [x] Update the unit test status check workflow
    - [x] The `determine_build_config` job removed
    - [x] The `build-config` reusable workflow input value hard code to **Debug**
- [x] Prepare release workflow created
- [x] Update all references of `CICD_REST_API` to `CICD_TOKEN`
- [x] All pwsh `echo` commands are converted to `Write-Host`.
- [x] All workflows with console writes use a GitHub workflow command

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
