### ISSUE TITLE
🚧Create add to proj workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#643]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a workflow that will automatically add a newly created issue to the _**KD-Team**_ org project.

If you go to the _**Infrastructure**_ repo, you will find a workflow named _**add-new-issue-to-project.yml**_.  You should be able to just copy and paste it in with no changes.

The name of the workflow should be: _**add-new-issue-to-project.yml**_.

### Acceptance Criteria

- [x] New workflow created

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
