### ISSUE TITLE
🚧Fix logic in 'Check For Release Notes' step

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#65]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the _**Check For Release Notes**_ step in the _**Validate_Release_Notes_Exist**_ job for the qa-prod workflows to only perform the check and fail if the branch is the master branch.

**Change To Below:**
``` yaml
    - name: Check For Release Notes
      run: |
        [string]$version = "${{ steps.proj-file-version.outputs.version }}";
        [string]$filePath = "${{ github.workspace }}\Documentation\ReleaseNotes\ProductionReleases\Release-Notes-v$version.md";
        
        # If the branch is master (prod) and the release notes don't exist, fail the job
        if ("${{ github.ref }}" -eq "master" -and -not([System.IO.File]::Exists($filePath))) {
          Write-Host "A production release notes file '$filePath' does not exist.";
          Write-Host "You must add release notes for production releases.";
        
          exit 1 # Fail
        }
```

Refer to the extra check for the master branch in the if logic

### Acceptance Criteria

**This issue is finished when:**
- [x] Job step updated

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] ~Unit tests have been written and/or adjusted for code additions or changes~
- [X] ~All unit tests pass~

### Related Work

- KinsonDigital/CASL#53
