### ISSUE TITLE
🚧Refactor preview workflow steps for library job

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#66]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Reorder steps and add an additional step to the _**Build_And_Test_Library**_ job.

This is to display information in the job for trouble shooting purposes and the reorder is to help support this additional step.

### Acceptance Criteria

**This issue is finished when:**
- [x] Move the _**Get Version From Project File**_ step directly below the _**Setup .NET SDK**_ step.
- [x] Add an additional step named _**Display Workflow Info**_ to print out workflow information
    - Refer to the YAML below

``` yaml
    - name: Display Workflow Info
      run: |
        echo "Current Branch: ${{ github.ref }}"
        echo "Project File Version: ${{ steps.proj-file-version.outputs.version }}"
```

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] ~Unit tests have been written and/or adjusted for code additions or changes~
- [X] ~All unit tests pass~

### Related Work

- KinsonDigital/CASL#53
