### ISSUE TITLE
🚧Improve release workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#665]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the release workflow by adding a job to determine the dir path to the release notes based on the type of release being performed.

Add the following job:
```yml
  determine_release_notes_path:
    name: Determin Release Notes Dir Path
    runs-on: ubuntu-latest
    outputs:
      release-notes-dir-path: ${{ steps.get-dir-path.outputs.release-notes-dir-path }}
    steps:
      - name: Get Dir Path
        id: get-dir-path
        run: |
          $dirPath = "${{ inputs.release-type }}" -eq "Production" ? "${{ vars.PROD_RELATIVE_RELEASE_NOTES_DIR_PATH }}" : "${{ vars.PREV_RELATIVE_RELEASE_NOTES_DIR_PATH }}";
          Write-Host "release-notes-dir-path=$dirPath" >> $eng:GITHUB_OUTPUT;
```

Once the job is created, update the `relative-release-notes-dir-path` reusable workflow input as shown below:

```diff
- relative-release-notes-dir-path: "${{ vars.RELATIVE_RELEASE_NOTES_DIR_PATH }}"
+ relative-release-notes-dir-path: "${{ needs.determine_release_notes_path.outputs.release-notes-dir-path }}"
```

Fix the logic in the _**prepare-release.yml**_ workflow
```diff
- if ($releaseType -ne 'preview' -and $releaseType -ne 'roduction') {
+ if ($releaseType -ne 'preview' -and $releaseType -ne 'Production') {
  Write-Host "::error::The release type input must be either 'Preview' or 'Production'.";
  exit 1;
}
```

### Acceptance Criteria

- [ ] New job created to be able to determine release notes dir path
- [ ] The workflow input in the `run_release` job updated
- [ ] Release type logic fixed in the `print_validate_workflow` job

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
