### ISSUE TITLE
🚧 Refactor name of the preview release PR template file

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#67]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Refactor the file name of the preview release PR template file.  This is to have the file name make more sense.  The current name is more indicative of the previous development process. 

### Acceptance Criteria

**This issue is finished when:**
- [x] The PR template file renamed from _**preview-release-to-release.md**_ to _**preview-to-release.md**_

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] Unit tests have been written and/or adjusted for code additions or changes
- [X] All unit tests pass
