### ISSUE TITLE
🚧Adjust release workflow input

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#670]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Adjust the text of the _**dry run**_ workflow input so that it has a title included in the text.  This should be done with the _**release.yml**_ workflow file.

```yml
      dry-run:
        description: Dry Run - Check to run the workflow without creating a release.
        required: false
        default: false
        type: boolean
```

This is how it currently looks.
<img width="247" alt="image" src="https://github.com/KinsonDigital/CASL/assets/85414302/a153a23c-6a63-41f1-b73b-b7619b6c5ef0">

### Acceptance Criteria

- [x] The `dry-run` workflow input description adjusted for the release workflow

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
