### ISSUE TITLE
🚧Fix workflows

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#676]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update prepare release workflows (production misspelling and prepare_release; add needs)
Update reusable workflows to latest version of Infrastructure

### Acceptance Criteria

- [x] Prepare release workflows (production misspelling and prepare_release; add needs) added
- [x] Reusable workflows to latest version of Infrastructure updated.  Newest version is _**v12.0.0**_
- [x] Update repo variable `CICD_SCRIPTS_VERSION` value to latest version
- [x] Update the _**add-new-issue-to-project.yml**_ workflow content to the same workflow content [here](https://github.com/KinsonDigital/Infrastructure/blob/main/.github/workflows/add-item-to-project.yml)
- [x] Rename the _**add-new-issue-to-project.yml**_ to _**add-new-item-to-project.yml**_

@kselena Quick Note
These changes need to be performed for all of the other projects. But instead of creating an issue to update all of them, let's leverage the fact that renovate is going to create all of the PRs anyways due to the update of the Infrastructure version from _**v11.0.0**_ to _**v12.0.0**_. This work can be performed in those version update PRs.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
