### ISSUE TITLE
🚧Lock version of MOQ

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#677]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Lock the version of mock to anything below version _**v4.20.0**_.  This will prevent any incoming update prs from renovate until we can find the time to possibly move away from MOQ

This is due to the reason for preventing the practice of harvesting PII.  This is a recent change that the MOQ project has added to _**v4.20.+**_.

For more information go to:
- moq/moq#1372

To do this, update the csproj file for the **Moq** nuget package reference to the value below.

```diff
- <PackageReference Include="Moq" Version="4.18.4" />
+ <PackageReference Include="Moq" Version="[4.18.4,4.19]" />
```

### Acceptance Criteria

- [x] The version of Moq NuGet package locked
- [x] Issues to perform the same work for the projects below are created:
    - [x] Carbonate
    - [x] PackageMonster
    - [x] BranchValidator
    - [x] VersionMiner
    - [x] Plazma
        > **Note** For this project, add an issue to replace moq code with NSubstitute instead of locking the version of moq

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
