### ISSUE TITLE
🚧Update README file

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#68]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the contributing section of the readme file to reflect the screen shot below

![image](https://user-images.githubusercontent.com/85414302/134150273-25391699-30c9-43a9-b163-788933e93945.png)

### Acceptance Criteria

**This issue is finished when:**
- [x] README file updated

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] ~Unit tests have been written and/or adjusted for code additions or changes~
- [X] ~All unit tests pass~
