### ISSUE TITLE
🚧Add automatic scene updates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#685]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a feature to load all scenes in the `Window.SceneManager automatically`.  This should have the ability to auto load enabled by default, but give the user the ability to turn it off to give them control over when and how the scenes are loaded.

Add this same concept to updating, rendering, and unloading

**Do the following:**
1. Auto scene loading:
    - Add a new `bool` property to the `Window` class that can be used to either load or not load the scenes
    - In the `Window.OnLoad()` method, add logic to load all of the scenes if auto-load is turned on
2. Auto scene unloading:
    - Add a new `bool` property to the `Window` class that can be used to either unload or not unload the scenes
    - In the `Window.OnUnload()` method, add logic to load all of the scenes if auto-unload is turned on
3. Auto scene updating
    - Add a new `bool` property to the `Window` class that can be used to either update or not update the scenes
    - In the `Window.OnUpdate()` method, add logic to update all of the scenes if auto-update is turned on
4. Auto scene rendering
    - Add a new `bool` property to the `Window` class that can be used to either draw or not draw the scenes
    - In the `Window.OnDraw()` method, add logic to update all of the scenes if auto-draw is turned on

### Acceptance Criteria

- [x] Auto scene loading added:
    - [x] A new `bool` property has been added to the `Window` class
    - [x] Logic has been added to the `Window.OnLoad()` method
- [x] Auto scene unloading added:
    - [x] A new `bool` property has been added to the `Window` class
    - [x] Logic has been added to the `Window.OnUnload()` method
- [x] Auto scene updating added:
    - [x] A new `bool` property has been added to the `Window` class
    - [x] Logic has been added to the `Window.OnUpdate()` method
- [x] Auto scene rendering added:
    - [x] A new `bool` property has been added to the `Window` class
    - [x] Logic has been added to the `Window.OnDraw()` method
- [x] Create an issue to update the velaptor docs regarding the new auto functionality added to `Window`
    > **Note**
    > This needs to have updates to the guides.  When creating the issue, go through the doc site to find all the guide areas that need updating.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
> **Note**
> Added https://github.com/KinsonDigital/Velaptor/labels/%E2%9C%A8new%20feature s 
> 1. Added a new property named `IsLoaded` to the `SceneManager` and `ISceneManager` types
> 2. Added a new property to `IRenderer` that indicates if a batch has been started
> 3. Added 4 new properties to automatically load, unload, update, and render the scenes to the `IWindow` interface.  This change to the interface affects the `Window` class.
>     Added the following props:
>     - `AutoSceneLoading`
>     - `AutoSceneUnloading`
>     - `AutoSceneUpdating`
>     - `AutoSceneRendering`
>     > **Note**
        This added behavior is technically a https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes due to the new property named `AutoSceneRendering` that was added with the default value being set to `true`

**Comment by CalvinWilkinson** [comment]
> **Warning**
> Added https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes
> 1. Replaced the `IRenderer` static interface with the `IBatcher` instance for starting and stopping a batch as well as clearing the render buffer.
> 2. Adding the new property `AutoSceneRendering` with a default value of `true` is a breaking change due to the behavior that it introduces.  When the property is set to `true`, this tells _**Velaptor**_ to automatically render the scenes.  This means that you do not need to use the `Clear()`, `Begin()`, and `End()` methods for rendering in your implementation of the `Window` class anymore.  The problem comes when you already have an app that has the `base.OnDraw()` method called after the drawing code that is currently implemented.  This would cause possible textures to be rendered out of order and hidden by other textures being rendered.

**Comment by CalvinWilkinson** [comment]
Added new https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%A6dependency%20update for **NSubstitute**
