### ISSUE TITLE
🚧Replace custom gaurds with dotnet ones

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#691]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Coming in **_dotnet 8_**, there are 2 new suggestions/warnings coming to the dotnet analyzers that suggest the following change.
2 approaches to this will satisfy the end means.  One is a suggestion from **_Microsoft_** and the other is from **_JetBrains Rider_** themselves.

First, before we choose which one is the better approach, we need to find out which one is more performant.

> **Note**
> More info can be found [here](https://www.youtube.com/watch?v=v7GAQfWnco0)(7m09s)

### **New approaches**

1. **_Microsoft_** Approach
    - Use the new dotnet guards `ArgumentNullException.ThrowIfNull` and `ArgumentNullException.ThrowIfNullOrEmpty`.
    - This uses the new warning coming in **_dotnet 8_** 👉🏻 `CA1510: Use `ArgumentNullException.ThrowIfNull` instead of explicitly thrown a new exception instance`
2. **_JetBrains_** Approach
    - Use  `this.myParam = myParam ?? throw new ArgumentNullException("null param")`
    - This does not use a warning, but uses a suggestion to refactor with this suggestion description 👉🏻 Join null check with assignment refactoring

- [x] Create a prototyping project to test both of these to see which one is more performant.  Whatever one is more performant, this will be the approach to take for refactoring across the code base.  Once an approach is taken, disable one warning and keep the other.  Remember, one warning is a _**JetBrains**_ analyzer warning so that will probably be a team-shared setting and the other is a built-in dotnet analyzer warning.

### **Work to be done:**
Replace the dotnet guards `EnsureThat.ParamIsNotNull<T>` and `EnsureThat.StringParamIsNotNullOrEmpty` with the chosen approach.

This is also going to require updating all of the tests in the code base that use the old text to the new text.  The text chosen will depend on which approach is chosen.  If the _**JetBrains Rider**_ approach is chosen, then no changes to the tests will be required.

### Acceptance Criteria

- [ ] All occurrences of the `EnsureThat.ParamIsNotNull<T>` replaced with chosen approach
- [ ] All occurrences of the `EnsureThat.StringParamIsNotNullOrEmpty` replaced with chosen approach
- [ ] `EnsureThat.ParamIsNotNull<T>` method removed
- [ ] `EnsureThat.StringParamIsNotNullOrEmpty` method removed
- [ ] All unit tests updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
@AndreBonda This issue can be picked up, but I need to do some perf testing first to figure out if I want to go with the _**MS**_ or _**JetBrains**_ approach.  😀

**Comment by sbundaz** [comment]
I can take this.

**Comment by CalvinWilkinson** [comment]
Closed without implementation

**Reason:**
After some discussion on the discord server, it was discovered that it would be best to split this work up into several issues.

The issues are:
- #782
- #783
- #784
- #785
- #786
