### ISSUE TITLE
🚧Prevent auto rendering with no scenes

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#695]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Prevent automatic rendering when there are no scenes that exist in the manager.

This can be easily fixed by adding a scene count to the `ISceneManger` and its implementation.  This can then be used in the `Window` abstract class `OnDraw()` method.

This will prevent any extra `IBatcher.Clear()`, `IBatcher.Begin()`, and `IBatcher.End()` method invokes from occurring when automatic scene rendering is enabled.

### Acceptance Criteria

- [x] New property added to `ISceneManager` to represent the total number of scenes.
- [x] Logic changed in the `Window` class.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
