### ISSUE TITLE
🚧Setup auto release of vel docs

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#698]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the _**release.yml**_ workflow to auto-trigger a Velaptor Docs API release.

This will execute the API release workflow in the **_Velaptor Docs_** project.
The benefit is that we will no longer be required to update the doc site with the latest release regarding API changes.

The way to do this is to create a GitHub REST API request to trigger the API docs release workflow. This can be done by creating a deno script inside of the Velaptor project itself. This script will use the `WorkflowClient` class from **Infrastructure** to make the request.

### Acceptance Criteria

- [x] Release workflow updated
- [x] deno.json config file added to solution folder

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
