### ISSUE TITLE
🚧Improve testing application

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#70]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Improve the testing application in the following ways:
- Simple scene management system to allow for each scene being able to manage an area of the library
    - Example: One scene could be to test rendering, another for sound, and another for font rendering only
- As development of the testing application moves forward and issues or improvements are discovered, created more issues to get these into the library at a later time.

### Acceptance Criteria

**This issue is finished when:**

**Scene Manager:**
- [x] Scene manager has the features below
    - [x] Update scene
    - [x] Render scene
    - [x] Move to next scene
        - Will use a UI control
    - [x] Move to previous scene
        - Will use a UI control
    - [x] Only one scene is active at a time and the active scene is what gets update and render events
    - [x] The title of the window will be the name of the scene
    - [x] Scenes will have a name that is unique
    - [x] More then one scene cannot have the same name
    - [x] A scene class will have a separate controls container/array to hold controls of a particular type to render to screen

**UI Controls:**
NOTE: Do this first!!  That way other tests have some controls to use to help with testing
- All controls will inherit from base control to contain shared properties and behavior that all controls can have
    - [x] Visible
    - [x] Enabled
    - [x] Width
    - [x] Height
    - [x] Position
    - [x] Left
    - [x] Top
    - [x] Right
    - [x] Bottom

- [x] Create simple UI controls
    - [x] Create Button Control
        - Add following events
            - [x] Click
            - [x] Mouse Down
            - [x] Mouse Up
            - [x] Mouse Move
    - [x] ~Create Checkbox Control~
        - Add the following props

        - ~Add the following events~
            - [x] ~Value Up~
            - [x] ~Value Down~
    - [x] Create Label Control
        - Add the following props
            - [x] Text
            - [x] Add click, mouse up and mouse down events
    - [x] ~Create TextBox Control~
        - Add the following props
            - [x] ~Text~
    - [x] ~Create UpDown Control~
    - This will be a combination of the text box control and the button control
        - Add the following props
            - [x] ~Value (current value of control)~
            - [x] ~Increment Amount~
            - [x] ~Decrement Amount~
            - [x] ~Min~
            - [x] ~Max~

**Graphics:**
- [x] Add a scene to test mouse functionality
    - This will show the location of the mouse, if the buttons are down or up and the scroll wheel value
- [x] Add a scene to test keyboard input
    - This will print the keyboard input to the window title bar
- [x] Add a scene to test rendering of a simple ~square~ circle
- [x] Add a scene to test animation of a ~square~ circle                
    - This is done using a texture atlas
- [x] Add a scene to test rendering of text
    - Add this scene to the order of scenes right before the keyboard scene
    - Add controls to change font size on the fly.  NOTE: This would require rebuilding and reload the font.  This might not be feasible and will have to be a feature request to allow this

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

**Comment by CalvinWilkinson** [comment]
Discovered that the mouse wheel value is always 0 and is not working.
Created an issue for this: #71

**Comment by CalvinWilkinson** [comment]
It was decided not to implement the _**Checkbox**_, _**TextBox**_, and _**UpDown**_ controls with this issue.  There is some other work that needs to be done first before the controls can be implemented the correct way.

Project item issues have been created for these controls as well as the other pre-requisites.

**Required Work For Controls:** 
- #75 
- #76
