### ISSUE TITLE
🚧Fix shutting down issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#708]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue where the system shutdown notification is not being sent to the rest of the systems to properly shut down.

These other systems are the GPU buffers, the shaders, etc.

This can be done by pushing a notification with the `PushNotifications.SystemShuttingDownId` ID and using the `this.pushReactable` class field in the `GLWindow` class.

`GLWindow Class`
```diff
    private void GLWindow_Closing()
    {
        this.isShuttingDown = true;

        SceneManager.UnloadContent();
        Uninitialize?.Invoke();

+        this.pushReactable.Push(PushNotifications.SystemShuttingDownId);

        this.afterUnloadAction?.Invoke();
    }
```

### Acceptance Criteria

- [x] Shutdown notification properly being sent
- [x] Unit test setup to check for this notification being fired

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by sbundaz** [comment]
I'll take this 🚀
