### ISSUE TITLE
🚧Add ability to get monitor info

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#709]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the ability for the library user to get information about the monitors in the system.  This can be done using a factory.

The best factory to use is probably the `InputFactory`.  This currently returns the keyboard and mouse.  Even though these are indeed input, they are also hardware and we need the ability for the user to get information about the monitors.  It makes sense to rename the `InputFactory` to `HardwareFactory` and then add a new method to the class that returns a list of monitors.

Also, rename the current methods in the `HardwareFactory`.   We are not actually creating new hardware, we are getting information **ABOUT** the hardware.  Rename the methods from `Create*` to `Get*`

### Acceptance Criteria

- [ ] `InputFactory` refactored
    - [ ] The `InputFactory` class re-named to `HardwareFactory`
    - [ ] The `CreateKeyboard()` method renamed to `GetKeyboard()`
    - [ ] The `CreateMouse()` method renamed to `GetMouse()`
- [ ] A new method with the name `GetMonitors()` added to the `HardwareFactory`
- [ ] A new method with the name `GetMainMonitor()` added to the `HardwareFactory`
- [ ] All tests updated due to method name refactoring
- [ ] **_VelaptorTesting_** updated for new changes
- [ ] **_Velaptor Docs_** issue created to update the guides

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
