### ISSUE TITLE
🚧Add ability to get monitor info

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#710]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the ability for the library user to get information about the displays in the system.  This can be done using a factory.

The best factory to use is probably the `InputFactory`.  This currently returns the keyboard and mouse.  Even though these are indeed input, they are also hardware and we need the ability for the user to get information about the displays.  It makes sense to rename the `InputFactory` to `HardwareFactory` and then add a new method to the class that returns a list of displays.

Also, rename the current methods in the `HardwareFactory`.   We are not actually creating new hardware, we are getting information **ABOUT** the hardware.  Rename the methods from `Create*` to `Get*`

### Acceptance Criteria

- [x] `InputFactory` refactored
    - [x] The `InputFactory` class was re-named to `HardwareFactory`
    - [x] The `CreateKeyboard()` method renamed to `GetKeyboard()`
    - [x] The `CreateMouse()` method renamed to `GetMouse()`
- [x] A new method with the name `GetDisplays()` added to the `HardwareFactory`
- [x] A new method with the name `GetMainDisplay()` added to the `HardwareFactory`
- [x] All tests updated due to method name refactoring
- [x] **_VelaptorTesting_** updated for new changes
- [x] **_Velaptor Docs_** issue created to update the guides
    - [x] Issue created and changes implemented and ready for release
        > **Note**
        > Make sure that this issue is not merged until the docs issue is _**READY**_ to be merged.  This will ensure that the docs release can be ready to go out quickly after the Velaptor release goes out.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
> **Warning**
> Implemented https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes s
> 1. Refactored the `InputFactory` class to `HardwareFactory`
> 2. Refactored the `HardwareFactory.CreateKeyboard()` method to `HardwareFactory.GetKeyboard()`
> 3. Refactored the `HardwareFactory.CreateMouse()` method to `HardwareFactory.GetMouse()`
> 4. Refactored the `SystemMonitor` class to a `readonly record struct`
> 5. Refactored the `SystemMonitorException` class to `SystemDisplayException`

**Comment by CalvinWilkinson** [comment]
> **Note**
> https://github.com/KinsonDigital/Velaptor/labels/%E2%9C%A8new%20feature s added
> 1. Added a new method named `GetDisplays()` to the `HardwareFactory` to get a list of all the displays in the system.
> 2. Added a new method named `GetMainDisplay()` to the `HardwareFactory` to the primary display in the system.
