### ISSUE TITLE
🚧Add ability to turn gl debugging on and off

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#721]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the ability to turn OpenGL debugging on and off.  This is mainly for performance reasons for release builds. When OpenGL debug output is turned on, marshaling the 'nint message' parameter in the debug callback and other string-related code will cause a performance hit and an increase in GC collections.  

This is currently turned on at the OpenGL level in the `GLWindow.GLWindow_Load()` method using the code below:
```cs
this.gl.SetupErrorCallback();
this.gl.Enable(GLEnableCap.DebugOutput);
this.gl.Enable(GLEnableCap.DebugOutputSynchronous);
```

Things To Do:
1. The OpenGL debug setup should be moved
    - This needs to be abstracted away into the `OpenGLService` implementation of the `IOpenGLService` interface.  The `IOpenGLService` is not currently being injected into the `GLWindow` class, so this will have to be done.
2. Move the viewport and buffer clear calls into the OpenGL service
    - There are other direct uses of the `IGInvoker` class field in the `GLWindow` class that can be replaced by `IOpenGLService` method calls.  These calls are:
    - `this.gl.Viewport(0, 0, width, height);` in the `GLWindow.GLWindow_Resize()` method
    - `this.gl.Clear(GLClearBufferMask.ColorBufferBit);` in the `GLWindow.GLWindow_Render()` method
        > **Note**
        > This will be called by a new method added to the `IOpenGLService` interface and `OpenGLService` class implementation
3. Move OpenGL error callback subscription and handler
    - Also, the GL invoker subscription of the `IGLInvoker.GLError` in the `GLWindow` class should be moved into the `IOpenGLService` implementation, as well as the error handler.  This will simplify the `GLWindow` class and centralize OpenGL-related handling into the OpenGL service.
4. Add a new app setting
   - Add a new app setting named `OpenGLDebuggingEnabled` to the app setting system.  The default value should be set to `true` for `DEBUG` and `DEBUG_CONSOLE` builds, and the default of `false` for `RELEASE` builds.  This setting will be used inside of the OpenGL service.
5. Remove unused interface and class
    - Remove the `IAppService` interface and `AppService` class
    - Remove the **_IoC_** registration and references in the `GLWindow` class
6. Setup app settings in the OpenGL service
    - Set up the app setting service in the OpenGL service to use the new app setting for enabling and disabling OpenGL debugging setup.  This will require a subscription to the `GLInitializedId` push notification reactable so that way it can enable or disable the OpenGL callback after GL has been initialized

### Acceptance Criteria

- [ ] Changes made to the `IOpenGLService` interface and its implementations
    - [ ] A new method with the name `ClearBuffer()` is added to the `IOpenGLService` interface and implementations
    - [ ] OpenGL debug callback subscription and handler setup
    - [ ] Inject system shutdown for proper debug callback subscription cleanup
    - [ ] Setup GL init subscription for enabling and disabling OpenGL debugging
    - [ ] `ViewPortSizeChangedId` push notification sent when setting view-port size
        > **Note**
        > Only call send the notification if the with OR height has actually changed
- [ ] Changes made to the `GLWindow` class
    - [ ] References and uses of `IAppService` removed
    - [ ] `IOpenGLService` setup
        - [ ] GL debug callback setup removed
        - [ ] Update viewport in resize method replaced
        - [ ] Clear buffer call replaced
- [ ] All unit tests updated for changes

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
