### ISSUE TITLE
🚧Add avalonia rendering

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#722]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the ability to set Velaptor to render to [Avalonia](https://github.com/AvaloniaUI/Avalonia/releases/tag/11.0.4) controls.

This can be done by creating an `App` class that contains a method to set the rendering context to Avalonia.  This method will take in a SILK.NET `GL object` as well as a viewport width and height.  The method will return an interface type of `IRenderContext` which can then be used by an Avalonia application to update thew viewport as well as other features added at a later time.

### Acceptance Criteria

- [x] Setup ability to render in Avalonia controls

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] After PR is merged, update the required status check for testing

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
