### ISSUE TITLE
🚧Update triggers for workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#726]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the following workflows to use the `pull_request` trigger instead of the `pull_request_target`.

1. _**build-status-check.yml**_
2. _**sonar-scan-pr-status-check.yml**_
3. _**unit-test-status-check.yml**_

This was a mistake on my part.  Come to find out, if you use the 'pull_request_target' workflow trigger, it will only run the workflow against the base branch of a pull request.  This is not good because we need to run the build, sonar, and unit test status checks against the result of the base AND head branches of a pull request merged together. If this doesn't happen, we are not testing how things are when merged and we won't catch anything.

Also, create issues to update the rest of the projects.

### Acceptance Criteria

- [ ] Workflow triggers updated
- [ ] Issues created for the rest of the org projects

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
