### ISSUE TITLE
🚧Setup rendering of graphics to take monitor scale into account

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#73]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

When changing the scale setting for a monitor, the graphics rendering does not change to take the new scale setting into account.  This does not matter if you restart the application after the scale setting.  Rendering is always done at a 100% scale setting.

The various monitor and scale settings are already in place which taps into GLFW.  Utilize this implementation to take scale into account before sending the transforms to the GPU.  This is all done in the `SpriteBatch` class.

This is the ideal way/theory on how to accomplish this but it might end up being much more involved.  If this works correctly, then all rendering of textures as well as fonts should be adapted.

An example of how this should work.  When the monitor scale setting is set to 100%, then the rendering will be performed as usual.  if the monitor setting is changed to 150%, then the rendering should be adjusted to render 50% larger then normal.

So a square rendered to the screen at a width and height of **_100, 150_** would end up with a render size on the screen at **_150, 225_**.  You should be able to screen capture both scenarios and compare the size and manually calculate the size difference to verify that the scale change been applied is correct.

**Monitor Change Detection:**
**NOTE:** This might not be necessary.
Also, look into seeing if a monitor settings change event can be tapped into at the GLFW level.  If not, then other measures will have to be taken into account.  Such as monitoring each monitors settings separately to detect change, and when change occurs, fire off an event.

This event can then be used to possibly update other state.

### Acceptance Criteria

**This issue is finished when:**
- [ ] When changing the size of the screen, the size or scale should not change for rendered content
- [ ] When changing the size scale setting of the monitor, pick up this change and adjust rendering accordingly
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Groomed
