### ISSUE TITLE
🚧Add ability to keep track of fps

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#734]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a feature to keep track of frames per second.

Look into adding FPS for just the update loop, one for the render loop, and one that is for the entire game loop.

Also, render the FPS to the testing application using labels. This should be implemented in the `MainWindow` so that way all the scenes do not need to construct UI for the fps rendering process.

### Acceptance Criteria

- [x] Entire loop FPS tracking added
- [x] Testing application renders all FPS status

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Set the frames per second to 60. For some reason it was set to default value of 120
