### ISSUE TITLE
🚧Update testing app obj movement

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#738]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the object movement in all applicable scenes to remove the illusion that the app is performing badly.

### Acceptance Criteria

- [ ] Various scene object movement updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without changes

**Reason:** After researching, it was discovered that all obj movement in the testing app scenes took time into account.  it was also discovered that the game is performing very well and is solid.  Lowering the update iterations discovered that the movement was a little bit jerky and was the cause of any jittery movement behavior.
