### ISSUE TITLE
🚧Add a relative and full dir path processing to content system

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#74]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

When loading content with the resolver types, add the ability to pass in a relative path that can be processed to load up content.

**Purpose:**
This will give the user the ability to have sub folders in each base content type directory so they can organize the content to suit their needs.

Each type of content has its own absolute directory path to the type of content.

**Examples:**
So if the base absolute directory path for graphics was C:\my-content\graphics, then the path examples below could be used.

- Graphics:
Based on the absolute base path for graphics above, and the content name being character\link, then the full path would resolve to C:\my-content\graphics\characters\link.
The last piece at the end is always a file. It is optional to use the file extension, but if you use it, it will always be replaced with the extension .png and the file must be of the correct type. So in the case of graphic content, it has to be a png format. This means the actual fully resolved file path to the link png file would be C:\my-content\graphics\characters\link.png.

Currently only file names with or without an extension are excepted.
What is needed is to basically be able to send in relative paths and they will be auto detected and resolved properly.

Apply the concept to each of the resolvers below.
- AtlasJSONDataPathResolver
- AtlasTexturePathResolver
- ContentPathResolver
- FontPathResolver
- SoundPathResolver
- TexturePathResolver

Each of these classes have a method named `ResolveFilePath()`.  The parameter needs to be able to except 3 different types of paths.

1. A full absolute file path directly to the content file
    - This simply just ignores the absolute base path for the current content type, and is just a full regular file path to the content file
2. A relative file path to the content file
    - This means that this path will be "added" to the end of the absolute base path for the current content type
3. A single file name to the content
    - This means that it is looking directly in the absolute base path for the current content type

### Acceptance Criteria

**This issue is finished when:**

```[tasklist]
### Tasks
- [ ] AtlasJSONDataPathResolver changes implemented
- [ ] AtlasTexturePathResolver changes implemented
- [ ] ContentPathResolver changes implemented
- [ ] FontPathResolver changes implemented
- [ ] SoundPathResolver changes implemented
- [ ] TexturePathResolver changes implemented
- [ ] Unit tests added
- [ ] All unit tests pass
``` 

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Reviewed
