### ISSUE TITLE
🚧Display funding options

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#748]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Display all funding options by adding a `FUNDING.yml` file to the project.

The funding options to add should be:
1. GitHub Sponsors
2. OpenCollective

### Acceptance Criteria

- [x] Funding config file added to the project
- [x] GitHub sponsors funding option setup
- [x] Open Collective funding option setup

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
