### ISSUE TITLE
🚧Add ability to render rectangle primitives

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#75]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add the ability to give the users to render primitive rectangles.  The rectangles should have the following features.
- Filled rectangles
- Empty rectangles
- Empty rectangle border thickness
- Solid colors for both filled and empty
- Horizontal color gradients
- Vertical color gradients
- Control of a corner radius for each corner independently

NOTE: Refer to the private repo called **_RenderLines_** for a basic demo application that can be used to build upon to figure out how to do this.

---

## Acceptance Criteria

- [x] Create readonly struct named `RectGPUData` for sending data to the GPU
    - make `internal`
- [x] Create readonly struct named `CornerRadius` for holding corner radius data for rect rendering
    - make `public`
- [x]  Create struct named `RectVertexData` to hold the vertex data in the `RectGPUData` struct to send to the GPU
    - make `internal`
- [x]  Create rectangle vertex and fragment shader code files
    - These need to be embedded resources
- [x] Create a new GPU buffer class named `RectGPUBuffer` for sending rectangle data to the GPU

Construct the following `SpriteBatch.Render()` method

- [x] `Render(RectShape rectangle)`

---

Empty Rectangle Details:
- [x] Ability to control the border color of the rectangle
- [x] Ability to set each corner radius to a custom value independently
- [x] Ability to render horizontal color gradients
- [x] Ability to render vertical color gradients
- [x] Ability to control the empty rectangle border thickness

Filled Rectangle Details:
- [x]  Ability to control the fill color of the rectangle
- [x] Ability to set each corner radius to a custom value independently
- [x] Ability to render horizontal color gradients
- [x] Ability to render vertical color gradients

**Other:**
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

### Issue Dependencies

- #76

**Comment by CalvinWilkinson** [comment]
During implementation, it was realized that it would be much easier to simply send in the `RectShape` struct into a single method instead of having so many method overloads.  The `RectShape` struct had all the information needed for rendering.

Updated card.
