### ISSUE TITLE
🚧Remove font load syntax requirements

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#755]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When loading a font while using the `FontLoader.Load()` method, it is required to add special syntax to the end of the content name as shown below:
- `FontLoader.Load("TimesNewRoman-Regular.ttf|size:12")`

Change how the method behaves by not throwing an exception if the syntax is invalid or does not exist.  Instead, just manually add the syntax with a default value of 12 to the value.  This value ends up eventually being the unique key for caching different loaded fonts of different sizes.

Make sure to update the API docs to explain that the syntax is not required and that if not used, a default value of 12 will be used.  Also, direct the users in the API docs to use the extension methods instead of setting a specific size.

> **Warning**
> This is a breaking change!  This is due to an exception NOT being thrown anymore.
> Some users might have the code written a certain way to handle the exception.

### Acceptance Criteria

- [x] Remove exception thrown when not using font size syntax

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
