### ISSUE TITLE
🚧Improve shader system 

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#76]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Improve the shader program system by making various changes to make the system more re-usable and to increase its capabilities.

**Shader Source Code Loading:**
A `ShaderProgram` should be able to easily load shader source code from multiple sources.  To make this easier, refactor how the shader source code system works so different sources can be used.

1. Create an `IShaderSourceLoaderService` interface and implementation that can be used to load shader source code from multiple locations.  For example, you could load source from a file on disk, an HTTP endpoint, a database or like it is currently done, from an embedded resource.
    - The `IEmbeddedResourceLoaderService` interface and implementation is currently used.  This should be a dependency injected into the new `IShaderSourceLoaderService`.
2. Eventually, we will create another `IShaderSourceLoaderService` implementation for different shaders to be loaded.  These other shader loaders might not need to perform templating or anything below and might load the shader source from something else other then the embedded resource.  This gives maximum flexibility.

**Shader Source Templating Service:**
1. Create a service that will do the job of processing templating in shader source code.  This is the concept of finding variables inside of template syntax like this -->_**${{ MY_VARIABLE }}**_ and replacing it with a value.  This system will make the shader source code dynamic which is currently how it works for the texture render shaders.   This simply needs to be improved.
2. This service will also get injected into the `IShaderSourceLoaderService` service implementation to perform template processing of the shader source code for texture rendering.

### Acceptance Criteria

**This issue is finished when:**
- [x] Create a templating service to process template variables in shader source code
- [x] Create new `IShaderSourceLoaderService` interface and implementation
    - Inject the `IEmbeddedResourceLoaderService` interface for loading the source code from the embedded resource

**ShaderProgram Changes:**
- [x] Once the **_shader loader service_** is created, working, and tested, remove the `IEmbeddedResourceLoaderService` being injected into the `ShaderProgram` and replace it with the new `IShaderSourceLoaderService` service.
- [x] The methods `LoadShaderSourceCode()` and `ProcessLine()` are not needed anymore.  The template service replaces this work.
- [x] Update **_vertex_** and **_fragment_** shader files
    - [x] **_shader.vert_** renamed to _**texture-shader.vert**_
    - [x] _**shader.frag**_ renamed to _**texture-shader.frag**_
    - [x] Vertex shader source code updated with template variable syntax

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass
