### ISSUE TITLE
🚧Refactor KeyCodeExtension tests

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#764]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor how the test data is set up in the `KeyCodeExtensionsTests.cs` test file.

Currently, every test method requires its own status test data property for testing in the XUnit test theories.

This is getting out of control in regards to repeated code and the size of the file.  To fix this issue, instead of using the 
`[Theory]` attribute with `static` properties for the theory data, convert the test methods to standard tests instead of parameterized tests.

### **What to do:**
1. Create a method in the test class that auto-generates all of the available enum values with a result of `false`. 
> **Note**
> The method will take in an array of `KeyCode`'s that will be used to set the equivalent key codes that are generated by the method to true.  The end result will be a small subset of true keys and the rest false.
> This method will be used to create the test data which will replace all of the `public static IEnumerable<object[]> TestData` members.
3. Remove all of the test data static properties.
4. Update all of the test methods that use the `[MemberData]` to use the new auto-generated data method in the `// Arrange` section of each test.
5. Update all of the test methods that use the `[MemberData]` by converting them to standard tests.
6. The data from that method will then be used in the test.
7. Test validation will be done using `Should().AllSatisfy()` instead.
```cs
        data.Should().AllSatisfy(testData =>
        {
            var actual = testData.Item1.IsLetterKey();
            actual.Should().Be(testData.Item2);
        });
```

### Acceptance Criteria

- [x] All test data replaced with a method to create test data
- [x] All tests updated to use the new data creation test method
- [x] Tests created for the other extension methods that have no tests.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
