### ISSUE TITLE
🚧Create checkbox control

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#77]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create a new _**checkbox**_ user control.

This will be a standard checkbox with the box being filled with an **X** for checked and empty for unchecked.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Check box should flip back and forth as the user clicks the control with the mouse
- [ ] The square section will be filled with an **X** graphic to represent that it is checked
- [ ] Clicking anywhere on the check box graphic or the label will check the check box
- [ ] When mouse hovers over label or check box graphic, highlight label text and check box graphics with a lighter color. 
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Issue Dependencies

- #75
- #76

**Comment by kselena** [comment]
Groomed
