### ISSUE TITLE
🚧Update sync workflow

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#776]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update ``sync-pr-to-issue.yml`` to match the [blog](https://github.com/KinsonDigital/blog/blob/main/.github/workflows/sync-pr-to-issue.yml) repo.

If needbe, add the workflow inputs below to build-status-check.yml and unit-test-status-check. yml

```yml
      checkout-ref: ${{ github.event.pull_request.head.ref }}
      checkout-repository: ${{ github.event.pull_request.head.repo.full_name }} 
```

### Acceptance Criteria

- [x] ``sync-pr-to-issue.yml`` updated
- [x] Workflow inputs added

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
