### ISSUE TITLE
🚧Create text box control

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#78]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create a text box control that gives the user the ability to render text in a rectangular space.

This control will be complicated to make.  The idea here is to utilize the `Label` control for the text.  The control will need to detect keyboard input so it can change the text of the label control to be displayed to the user.  Deletion capability will also be required using the _**Delete**_ and _**Backspace**_ keys.

For text selection, a solid rectangle should be rendered behind the text. The color of the text should be set to the inverse color of the selection rectangle.  The inverse color will need to be calculated somehow.

### Acceptance Criteria

```[tasklist]
### Tasks
- [x] Text rendered in a rectangular area
- [x] Hitting _**Delete**_ key will delete characters that are to the right of the blinking cursor
- [x] Hitting _**Backspace**_ key will delete characters that are to the left of the blinking cursor
- [x] Hitting the _**Home**_ key by itself will move the cursor to the beginning
- [x] Hitting the _**End**_ key by itself will move the cursor to the end
- [x] Ability to set the text color
- [x] Ability to set the color of the selection
- [x] Ability to set the color of the cursor
- [x] Add a new method overload for the `IFont.GetCharacterBounds()` method to take a `StringBuilder` param
```

```[tasklist]
### Text Selection
- [x] Holding shift while using the **_Right Arrow_** key will select text one character at a time to the right of where the cursor started during the selection process
- [x] Holding shift while using the **_Left Arrow_** key will select text one character at a time to the left of where the cursor started during the selection process
- [x] Holding shift while using the **_End_** key will select all of the text to the right of where the cursor started during the selection process
- [x] Holding shift while using the **_Home_** key will select all of the text to the left of where the cursor started during the selection process
- [x] When text is selected, a filled rectangle will be rendered with the text on top.  This shows the text as selected.
```

### ToDo Items

```[tasklist]
### Tasks
- [x] Draft pull request created and linked to this issue
- [x] Issue linked to the proper project
- [x] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass
```

### Issue Dependencies

- #75
- #76

**Comment by kselena** [comment]
Reviewed

**Comment by CalvinWilkinson** [comment]
> **Warning** Added https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes
> - Change the ControlBase.`OnMouseDown()` and ControlBase.`OnMouseUp()` methods to internal.  This is only meant for internal Velaptor use.  Use the `ControlBase` events instead.
