### ISSUE TITLE
🚧Replace custom guards

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#782]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Replace the custom guards with built-in dotnet guards.  The custom guards to be replaced are the `EnsureThat.ParamIsNotNull()` and `EnsureThat.StringParamIsNotNullOrEmpty()` guards. 

1. The custom guard `EnsureThat.ParamIsNotNull()` should be replaced by the dotnet guard `ArgumentNullException.ThrowIfNull()`
2. The custom guard `EnsureThat.StringParamIsNotNullOrEmpty()` should be replaced by the dotnet guard `ArgumentException.ThrowIfNullOrEmpty()`
3. The following files should be refactored:
    - Testing/VelaptorTests/Guards/EnsureThatTests.cs
    - Velaptor/Content/Sound.cs
    - Velaptor/Content/TextureLoader.cs
    - Velaptor/Content/AtlasLoader.cs
    - Velaptor/Content/AtlasData.cs
    - Velaptor/Content/Fonts/Font.cs
    - Velaptor/Content/SoundLoader.cs
    - Velaptor/Content/Texture.cs
    - Velaptor/NativeInterop/FreeType/FreeTypeErrorEventArgs.cs
    - Velaptor/NativeInterop/GLFW/GlfwErrorEventArgs.cs
    - Velaptor/NativeInterop/OpenGL/GLInvoker.cs
    - Velaptor/OpenGL/GpuBufferNameAttribute.cs
    - Velaptor/OpenGL/ShaderNameAttribute.cs
    - Velaptor/OpenGL/GLErrorEventArgs.cs

> **Note**
> 1. The exception messages that are generated by the new dotnet guards are different than the custom guard.  This means the unit tests will all need to be updated as well.
> 2. There are many files to be refactored, but we are completing the work in chunks that are dispersed among additional issues.
> 3. If there are any test methods that are parameterized for testing an empty or null `string`, split the unit tests out into 2 tests.  One test will be for the null check and the other will be for the empty check.  Make sure to rename/name the unit tests names appropriately. 
> **Example:** If the name of the parameterized unit test method is `Load_WithNullOrEmptyParam_ThrowsException`, this unit test could check the null value of the `string` and be named `Load_WithNullParam_ThrowsException`.  The new unit test method to check the empty `string` would then be named `Load_WithEmptyParam_ThrowsException`.

### Acceptance Criteria

```[tasklist]
### ToDo
- [x] All instances in the files listed below with the custom guard `EnsureThat.ParamIsNotNull()` replaced by the dotnet guard `ArgumentNullException.ThrowIfNull()`
- [x] All instances in the files listed below with the custom guard `EnsureThat.StringParamIsNotNullOrEmpty()` replaced by the dotnet guard `ArgumentException.ThrowIfNullOrEmpty()`
```

```[tasklist]
### The following files are refactored:
- [x] `Velaptor/Content/Sound.cs`
- [x] `Velaptor/Content/TextureLoader.cs`
- [x] `Velaptor/Content/AtlasLoader.cs`
- [x] `Velaptor/Content/AtlasData.cs`
- [x] `Velaptor/Content/Fonts/Font.cs`
- [x] `Velaptor/Content/SoundLoader.cs`
- [x] `Velaptor/Content/Texture.cs`
- [x] `Velaptor/NativeInterop/FreeType/FreeTypeErrorEventArgs.cs`
- [x] `Velaptor/NativeInterop/GLFW/GlfwErrorEventArgs.cs`
- [x] `Velaptor/NativeInterop/OpenGL/GLInvoker.cs`
- [x] `Velaptor/OpenGL/GpuBufferNameAttribute.cs`
- [x] `Velaptor/OpenGL/ShaderNameAttribute.cs`
- [x] `Velaptor/OpenGL/GLErrorEventArgs.cs`
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by sbundaz** [comment]
I'll take this.
