### ISSUE TITLE
🚧Replace custom guards

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#783]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Replace the custom guards with built-in dotnet guards.  The custom guards to be replaced are the `EnsureThat.ParamIsNotNull()` and `EnsureThat.StringParamIsNotNullOrEmpty()` guards. 

1. The custom guard `EnsureThat.ParamIsNotNull()` should be replaced by the dotnet guard `ArgumentNullException.ThrowIfNull()`
2. The custom guard `EnsureThat.StringParamIsNotNullOrEmpty()` should be replaced by the dotnet guard `ArgumentException.ThrowIfNullOrEmpty()`
3.  The `EnsureThat` class and file should be deleted from the code base.
4. The following files should be refactored:
    - Testing/VelaptorTests/Guards/EnsureThatTests.cs
    - Velaptor/UI/Window.cs
    - Velaptor/UI/Button.cs
    - Velaptor/UI/Label.cs
    - Velaptor/Hardware/SystemDisplay.cs
    - Velaptor/Input/Keyboard.cs
    - Velaptor/Input/Mouse.cs
    - Velaptor/Content/TextureLoader.cs
    - Velaptor/Content/AtlasLoader.cs
    - Velaptor/Content/SoundPathResolver.cs
    - Velaptor/Content/ContentLoader.cs
    - Velaptor/Content/Factories/SoundFactory.cs
    - Velaptor/Content/Factories/FontFactory.cs

> [!Note]
> 1. The exception messages that are generated by the new dotnet guards are different than the custom guard.  This means the unit tests will all need to be updated as well.
> 2. There are many files to be refactored, but we are completing the work in chunks that are dispersed among additional issues.
> 3. If there are any test methods that are parameterized for testing an empty or null `string`, split the unit tests out into 2 tests.  One test will be for the null check and the other will be for the empty check.  Make sure to rename/name the unit tests names appropriately. 
> **Example:** If the name of the parameterized unit test method is `Load_WithNullOrEmptyParam_ThrowsException`, this unit test could check the null value of the `string` and be named `Load_WithNullParam_ThrowsException`.  The new unit test method to check the empty `string` would then be named `Load_WithEmptyParam_ThrowsException`.

### Acceptance Criteria

```[tasklist]
### ToDo
- [x] All instances in the files listed below with the custom guard `EnsureThat.ParamIsNotNull()` replaced by the dotnet guard `ArgumentNullException.ThrowIfNull()`
- [x] All instances in the files listed below with the custom guard `EnsureThat.StringParamIsNotNullOrEmpty()` replaced by the dotnet guard `ArgumentException.ThrowIfNullOrEmpty()`
- [x] The `EnsureThat` class adjusted to only contain pointer check guards.
```

```[tasklist]
### The following files are refactored:
- [x] Testing/VelaptorTests/Guards/EnsureThatTests.cs
- [x] Velaptor/UI/Window.cs
- [x] Velaptor/UI/Button.cs
- [x] Velaptor/UI/Label.cs
- [x] Velaptor/Hardware/SystemDisplay.cs
- [x] Velaptor/Input/Keyboard.cs
- [x] Velaptor/Input/Mouse.cs
- [x] Velaptor/Content/TextureLoader.cs
- [x] Velaptor/Content/AtlasLoader.cs
- [x] Velaptor/Content/SoundPathResolver.cs
- [x] Velaptor/Content/ContentLoader.cs
- [x] Velaptor/Content/Factories/SoundFactory.cs
- [x] Velaptor/Content/Factories/FontFactory.cs
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Issue Dependencies

- #782
- #784
- #785
- #786

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by thestbar** [comment]
@CalvinWilkinson could you please assign this issue to me?

**Comment by CalvinWilkinson** [comment]
Hello @thestbar, I was just wondering if you will be able to complete this task. I understand that you may have been occupied with other things, which is perfectly fine. However, I just wanted to check with you since I was hoping to include this in the upcoming release, which is approaching soon.

**Comment by CalvinWilkinson** [comment]
@thestbar Another side note, if you need more time, that is completely fine.  We can add it to a later release.  😀

**Comment by thestbar** [comment]
@CalvinWilkinson Hello, indeed I have limited time, but I believe I will manage to do it this weekend, I got some days off now for Christmas 😀 Are you ok with this? Do we have a standard day for the release, so I can arrange my time to try to push it on this window?

**Comment by CalvinWilkinson** [comment]
> @CalvinWilkinson Hello, indeed I have limited time, but I believe I will manage to do it this weekend, I got some days off now for Christmas 😀 Are you ok with this? Do we have a standard day for the release, so I can arrange my time to try to push it on this window?

There is no push for this to go out in the release.  Since it is just a coding practice/standard thing it is not a bug and it does not directly affect the user in any way, so there is no rush.  It's just that it was slotted for _**v1.0.0-preview.31**_ and I will be doing a release soon so I needed to know if I could get it out in time or just push it to another release.  😊

I will just leave it as is and if you get it done before I do a release, then awesome.  If not, I will just move it to _**v1.0.0-preview.32**_ instead.

**Comment by CalvinWilkinson** [comment]
Hey @thestbar!!  Hope things are well!!

I was just wondering if you had a status on this?

**Comment by thestbar** [comment]
Hello @CalvinWilkinson I did not have a lot of free time to fully finish it. I am half way through it! Sorry, for the long delay 😞

**Comment by CalvinWilkinson** [comment]
> Hello @CalvinWilkinson I did not have a lot of free time to fully finish it. I am halfway through it! Sorry, for the long delay 😞

That is ok @thestbar.  No apology is necessary.  We are all busy with life!!
If it was a high priority, I would be super transparent and just take it over myself.  I appreciate your help so it is yours.  😀

I just wanted to know the status is all.

**Comment by CalvinWilkinson** [comment]
@thestbar I was wondering if this is ready to go.

I would have released it in `v1.0.0-preview.34` but was not sure if you were finished with it or not.  So I moved it to `v1.0.0-preview.35`.

**Comment by CalvinWilkinson** [comment]
Work completed and PR approved and merged by @CalvinWilkinson.

**Reason:**
No response since Feb 5th.

Thanks for your contribution @thestbar!  Greatly appreciate it!!
If you need anything else or are still interested in contributing, I am still here. Cheers!!
