### ISSUE TITLE
🚧Replace custom guards

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#784]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Replace the custom guards with built-in dotnet guards.  The custom guards to be replaced are the `EnsureThat.ParamIsNotNull()` and `EnsureThat.StringParamIsNotNullOrEmpty()` guards. 

1. The custom guard `EnsureThat.ParamIsNotNull()` should be replaced by the dotnet guard `ArgumentNullException.ThrowIfNull()`
2. The custom guard `EnsureThat.StringParamIsNotNullOrEmpty()` should be replaced by the dotnet guard `ArgumentException.ThrowIfNullOrEmpty()`
3. The following files should be refactored:
   - Velaptor/Content/Factories/TextureFactory.cs
   - Velaptor/Content/AtlasData.cs
   - Velaptor/Content/Caching/SoundCache.cs
   - Velaptor/Content/Caching/TextureCache.cs
   - Velaptor/Content/Fonts/FontLoader.cs
   - Velaptor/Content/Fonts/WindowsFontPathResolver.cs
   - Velaptor/Content/Fonts/Font.cs
   - Velaptor/Content/Fonts/FontPathResolver.cs
   - Velaptor/Content/Fonts/ContentFontPathResolver.cs
   - Velaptor/Content/Fonts/Services/FontStatsService.cs
   - Velaptor/Content/Fonts/Services/FontService.cs
   - Velaptor/Content/SoundLoader.cs
   - Velaptor/Content/Texture.cs

> **Note**
> 1. The exception messages that are generated by the new dotnet guards are different than the custom guard.  This means the unit tests will all need to be updated as well.
> 2. There are many files to be refactored, but we are completing the work in chunks that are dispersed among additional issues.
> 3. If there are any test methods that are parameterized for testing an empty or null `string`, split the unit tests out into 2 tests.  One test will be for the null check and the other will be for the empty check.  Make sure to rename/name the unit tests names appropriately. 
> **Example:** If the name of the parameterized unit test method is `Load_WithNullOrEmptyParam_ThrowsException`, this unit test could check the null value of the `string` and be named `Load_WithNullParam_ThrowsException`.  The new unit test method to check the empty `string` would then be named `Load_WithEmptyParam_ThrowsException`.

### Acceptance Criteria

```[tasklist]
### ToDo
- [x] All instances in the files listed below with the custom guard `EnsureThat.ParamIsNotNull()` replaced by the dotnet guard `ArgumentNullException.ThrowIfNull()`
- [x] All instances in the files listed below with the custom guard `EnsureThat.StringParamIsNotNullOrEmpty()` replaced by the dotnet guard `ArgumentException.ThrowIfNullOrEmpty()`
```

```[tasklist]
### The following files are refactored:
- [x] Velaptor/Content/Factories/TextureFactory.cs
- [x] Velaptor/Content/Caching/SoundCache.cs
- [x] Velaptor/Content/Caching/TextureCache.cs
- [x] Velaptor/Content/Fonts/FontLoader.cs
- [x] Velaptor/Content/Fonts/WindowsFontPathResolver.cs
- [x] Velaptor/Content/Fonts/FontPathResolver.cs
- [x] Velaptor/Content/Fonts/ContentFontPathResolver.cs
- [x] Velaptor/Content/Fonts/Services/FontStatsService.cs
- [x] Velaptor/Content/Fonts/Services/FontService.cs
- [x] Velaptor/Content/Texture.cs
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by sbundaz** [comment]
I take this

**Comment by CalvinWilkinson** [comment]
Removed the items below from the _**Acceptance Criteria**_:
- _**Velaptor/Content/SoundLoader.cs**_
- _**Velaptor/Content/Fonts/Font.cs**_
- **_Velaptor/Content/AtlasData.cs_**

This work was done with the issue:
- #782
