### ISSUE TITLE
🚧Create up down control

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#79]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create a control that has 2 buttons that when clicked, will increment and decrement a numerical value.

This is a composite control.  What this means is that it will be a control that is made up of other controls.
The number value that will be displayed in a _**TextBox**_ control.  The value up and down buttons will be _**Button**_ controls.

### Acceptance Criteria

**This issue is finished when:**
- [ ] The value displayed will only show numerical data
- [ ] The up down buttons will be located to the right of the value and the buttons will be stacked vertically on top of each other with the **up button** on top of the **down button**
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Issue Dependencies

- #76 
- #75 
- #78

**Comment by kselena** [comment]
Reviewed

**Comment by CalvinWilkinson** [comment]
**Closed Without Implementation**

**Reason:**
This is due to the change in direction in regards to the UI control API side of Velaptor.  It was decided to deprecate and stop development of the UI API.
