### ISSUE TITLE
🚧Improve factories

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#791]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the factory system by doing the following:

> **Note**
> This issue was created as a result of a research issue:
> - #754 

1. Remove the `IContentLoader` and `ContentLoader` types and related code from the code base.
    > **Note**
    > This will enforce only one way to load content which will be with the `ContentLoaderFactory`.
1. Convert the `RendererFactory` into a static class just like the `ContentLoaderFactory`.
    > **Note**
    > This will make it easier for the user because they will not have to create an object instance every time just to create renderers.  90% of the time, the renderer object instance is only used one time anyway.  This will also prevent more GC collections.

> **Warning**
> This contains https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes!!

### Acceptance Criteria

- [x] The `IContentLoader` and `ContentLoader` types removed
- [x]  The `RendererFactory` converted into a static class.
- [x] Doc website checked for required changes
    - [x] Issue created if required
    - [x] API docs for this branch with guide changes complete
        > **Note**
        > A release of _**Velaptor version v1.0.0-preview.30**_ will be performed after this issue has been complete
        > and the API docs have been complete from this branch.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Related Work

- KinsonDigital/VelaptorDocs#126

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Put on hold to wait for completion of issue
- KinsonDigital/VelaptorDocs#126
