### ISSUE TITLE
🚧Update trigger api doc release script

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#794]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the _**trigger-api-docs-release.ts**_ script to use the new _**kd_clients**_ deno third-party package.
The thing to update is the use of the `WorkflowClient`.

Also, setup a **_deps.ts_** file for managing the dependencies.

### Acceptance Criteria

- [ ] The _**trigger-api-docs-release.ts**_ script has been updated
- [ ] A _**deps.ts**_ file for centralized deno script dependency management is set up.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
