### ISSUE TITLE
🚧Refactor FontStats to readonly record

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#801]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor the `FontStats` struct to a `readonly record struct`.  This will provide performance benefits as well as make the struct data immutable. 

If applicable, when refactoring the code, use the `with` keyword.

This struct holds data required for creating font atlas textures when loading fonts, which dictates how the text will be rendered with a particular font.  

Also, refactor the `public` fields to `public init` properties.   This will provide the ability to set the initial values of the properties as well as keep the structure immutable.

Make sure that the XML docs for the properties have been updated.
Example:
```diff
/// <summary>
- /// The font family.
+ /// Gets the font family.
/// </summary>
- public string FamilyName;
+ public string FamilyName;
```

> [!Warning]
> Be careful with refactoring code related to this `struct`.  The impact could entirely break the font creation process and in turn how text is rendered.

> [!Note]
> **Things To Consider:**
> - The `IEquatable<T>` is not required for `record`'s.  This is because the `Equals()` method that the interface provides is built into records.
> - Methods like the `Equals()` `override bool Equals()` and `GetHashCode()` are built-into records

Delete the `FontStatsTests` file.  The `struct` is so simple combined with the removal of the `Equals()` methods, that there is nothing to test anymore.

Also, add the `[ExcludeFromCodeCoverage]` attribute to the entire struct with a justification message of "Tests not necessary".

### Acceptance Criteria
```[tasklist]
### Tasks
- [ ] The `FontStats` structure has been refactored to a `readonly record` struct.
- [ ] The `FontStatsTests` file has been deleted.
- [ ] Related code that uses the `struct` has been refactored
- [ ] XML docs updated where applicable
- [ ] The `[ExcludeFromCodeCoverage]` has been added to the entire struct
- [ ] Any unused usings in the `FontStats` file removed
- [ ] Manual testing of text rendering performed using the _**VelaptorTesting**_ project
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by sbundaz** [comment]
@CalvinWilkinson I can take it.
