### ISSUE TITLE
🚧Refactor FontAtlasMetrics to readonly record

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#802]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor the `FontAtlasMetrics` struct to a `readonly record struct`.  This will provide performance benefits as well as make the struct data immutable.  When refactoring the code, use the `with` keyword.

This struct holds data required for creating font atlas textures when loading fonts, which dictates how the text will be rendered with a particular font.  

Also, refactor the `public` fields to `public init` properties.   This will provide the ability to set the initial values of the properties as well as keep the structure immutable.

Make sure that the XML docs for the properties have been updated.
Example:
```diff
/// <summary>
- /// The number of rows in the atlas.
+ /// Gets the number of rows in the atlas.
/// </summary>
- public uint Rows;
+ public uint Rows;
```

> **Warning**
> Be careful with refactoring code related to this `struct`.  The impact could entirely break the font creation process and in turn how text is rendered.

**Things To Consider:**
- Methods like the `Equals()` `override bool Equals()` and `GetHashCode()` are built-into records

Delete the `FontAtlasMetricsTests` file.  The `struct` is so simple combined with the removal of the `Equals()` methods, that there is nothing to test anymore.

### Acceptance Criteria

- [x] The `FontAtlasMetrics` structure has been refactored to a `readonly record` struct.
- [x] Related code that uses the `struct` has been refactored 
- [x] The `FontAtlasMetricsTests` file has been deleted.
- [x] XML docs updated where applicable

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by map-b** [comment]
I'll do this.

**Comment by CalvinWilkinson** [comment]
> I'll do this.

The issue has been assigned.  😀

I asked before but you must have missed the comment I made in another issue you did.  I was just wondering if you are on the KinsonDigital discord server?  I mixed you up with somebody else and I don't know what your discord server name is.  That is if you even have an account or are even on the server.  If not, that is fine, but if you are, I wanted to make sure that I could collaborate with you there as well.

Btw, thanks for your contributions!!  Greatly appreciated!!

**Comment by map-b** [comment]
Sorry for that. No, I'm not in the discord server. If I finally get in there I will tell you.

**Comment by map-b** [comment]
One doubt about the issue. 
I've checked the result from `GetHashCode()`, the old custom method returns a not reproducible value but the new one from the built-in `record` returns a reproducible one (always the same value).  * I got curious from the `[ExcludeFromCoverage]` justification. Is this expected?

**Comment by CalvinWilkinson** [comment]
> One doubt about the issue. I've checked the result from `GetHashCode()`, the old custom method returns a not reproducible value but the new one from the built-in `record` returns a reproducible one (always the same value). * I got curious from the `[ExcludeFromCoverage]` justification. Is this expected?

This is expected yes.

**Comment by CalvinWilkinson** [comment]
> Sorry for that. No, I'm not in the Discord server. If I finally get in there I will tell you.

Ok cool.  Not a problem.  Just want to make sure I know who is who in both systems.  I have been attaching personal notes to discord profiles so that way I know who they are in GitHub etc.
