### ISSUE TITLE
🚧Improve keyboard performance

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#804]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

## **OLD DESCRIPTION**
~~Refactor the `KeyboardState` struct to a `readonly record struct`.  This will provide performance benefits as well as make the struct data immutable.~~

~~This `struct` is responsible for holding information about the state of the keyboard at a particular point in time.~~

~~Currently, there is a `struct` field that is used to hold the default state of all the available keyboard keys.  The name of this field is `keyStates`.  The method `InitKeys()` method is used to initialize the state of every single keyboard key to a default state of `false` where `false` represents that the key is _**NOT**_ in the down state.   Since we are changing the `struct` to a `readonly record struct`, we have to set the `keyStates` to be `readonly`.  This will change how we set up the default state of the keyboard keys.  To solve this, we have to change the `InitKeys()` method to a `static` method.  Then we can just set the `keyStates` field to `readonly` and initialize it to the result of the static `InitKeys()` method.~~

Refactor the keyboard input-related types to improve performance.  This will involve in-depth perf testing using benchmark dotnet.  The goal here is to simply improve the performance of keyboard input and reduce memory allocations and GC pressure as much as we can.

**Things To Consider:**
- The `IEquatable<T>` is not required for `record`'s.  This is because the `Equals()` method that the interface provides is built into records.
- Methods like the `Equals()` `override bool Equals()` and `GetHashCode()` are built-into records

Remove tests in the `KeyboardStateTests` file.

### Acceptance Criteria

```[tasklist]
- [x] Keyboard related input types refactored accordingly
- [x] Interface implementation of the `Equals()` method has been removed
- [x] The overridden `Equals()` method has been removed
- [x] The `GetHashCode()` method has been removed
- [x] The `==` operator has been removed
- [x] The `!=` operator has been removed
- [x] The `EqualsOperator_WhenInvokedWithEqualOperands_ReturnsTrue` following tests in the `KeyboardStateTests` file removed
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
