### ISSUE TITLE
🚧Improve mouse performance

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#805]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the performance of the mouse input by refactoring the mouse-related types.

**Things To Consider:**
- The `IEquatable<T>` is not required for `record`'s.  This is because the `Equals()` method that the interface provides is built into records.
- Methods like the `Equals()` `override bool Equals()` and `GetHashCode()` are built-into records

Remove tests in the `MouseStateTests` file.

### Acceptance Criteria
```[tasklist]
### Tasks
- [x] Create mouse baseline performance project
- [x] Mouse-related input types refactored accordingly
- [x] Interface implementation of the `Equals()` method has been removed
- [x] The overridden `Equals()` method has been removed
- [x] The `GetHashCode()` method has been removed
- [x] The `==` operator has been removed
- [x] The `!=` operator has been removed
- [x] All tests updated accordingly
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
> [!WARNING]
> Introduced the following https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes
> 1. Refactored the `MouseState` struct to a `readonly` struct.
