### ISSUE TITLE
🚧Refactor GlfwVideoMode to readonly struct

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#806]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor the `GlfwVideoMode` struct to a `readonly record struct`.  This will provide performance benefits as well as make the struct data immutable.  When refactoring the code, use the `with` keyword.

This struct holds data required for creating font atlas textures when loading fonts, which dictates how the text will be rendered with a particular font.  

Also, refactor the `public` fields to `public int` properties.   This will provide the ability to set the initial values of the properties as well as keep the structure immutable.

Make sure that the XML docs for the properties have been updated.
Example:
```diff
/// <summary>
- /// The width, in screen coordinates, of the GLFWVideoMode.
+ /// Gets the width, in screen coordinates, of the GLFWVideoMode.
/// </summary>
- public int Width
+ public int Width { get; init; }
```

### Acceptance Criteria

- [x] The `GlfwVideoMode` structure has been refactored to a `readonly record` struct.
- [x] Related code that uses the `struct` has been refactored 
- [x] XML docs updated where applicable

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by map-b** [comment]
Started work.

**Comment by CalvinWilkinson** [comment]
> Started work.

Just quick FYI.  Make sure that you don't actually start the work until I have assigned it to you.  The reason for this is because the vast amount of work to be done across the organization, sometimes the issues become obsolete or need additional info.  Sometimes the direction of things have changed.  If you don't wait for me to assign it to you and you start working, it might be too late before I see it and assign it to you and then you would of done all the work for nothing. 

I don't want that to happen to outside contributors.  I would rather have it on me then on you guys.

I hope that is ok!!  🙂
