### ISSUE TITLE
🚧Refactor Line to record struct

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#807]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor the `Line` struct to a `record struct`.  This will provide performance benefits as well as make the struct data immutable.  When refactoring the code, use the `with` keyword.

This struct holds data required for creating font atlas textures when loading fonts, which dictates how the text will be rendered with a particular font.  

> **Warning**
> This issue will introduces https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes due to the `Line` struct being part of the public API.

### Acceptance Criteria

- [ ] The `Line` structure has been refactored to a `record struct`.
- [ ] Related code that uses the `struct` has been refactored 
- [ ] The `LineTests` updated.
- [ ] XML docs updated where applicable

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
