### ISSUE TITLE
🚧Improve mouse event data for mouse related control events

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#81]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Currently, when a _**MouseUp**_ or _**MouseDown**_ event is fired for a UI control, the event argument data sent to the handler is a barebones empty event.

Refactor and improve the `MousePositionEventArgs` class to be able to send out the mouse position as well as button information such as if the left, right, and middle buttons are in the down or up position.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Refactor the name of the `MousePositionEventArgs` to `MouseEventArgs`
- [ ] Add boolean property indicating if the left button is in the down position.
- [ ] Add boolean property indicating if the right button is in the down position.
- [ ] Add a boolean property indicating if the middle/scroll button is in the down position.
- [ ] Add event args to the `MouseUp` event
- [ ] Add event args to the `MouseDown` event
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Reviewed

**Comment by CalvinWilkinson** [comment]
This issue has been put on https://github.com/KinsonDigital/Velaptor/labels/on%20hold because:

The direction that the UI is going to take will probably change.  The team is thinking about utilizing [ImGui dotnet](https://github.com/ImGuiNET/ImGui.NET) instead.  This is a very well-known library with lots of uses and will reduce the workload for the team in regards to maintaining the UI side of things.  There is a good chance that we will be removing UI functionality from Velaptor so we can concentrate on game dev.
