### ISSUE TITLE
🔬Look for areas of dotnet 7 & 8 improvements 

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#810]
## Complete The Item Below

- [X] I have updated the title without removing the 🔬 emoji.

### What To Research

Look for areas of improvement and csharp 11 & 12 features to take advantage of throughout the code base.  For each feature, create issues if possible to perform the refactoring work to implement the changes.

#### **Resources:**
- [csharp 11 features](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11)
- [csharp 12 features](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12)
- [dotnet 9](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/overview)

---

## **Ideas:**

1. **use of `required` keyword (C# 11):**
Look for areas where the `required` properties can and should be used.
    - Go [here](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required) for more information on required properties.
2. **Use of `CollectionsMarshal`**
    - Goto this [video](https://www.youtube.com/watch?v=0iTMIxZeyXg) (Nick Chapsas)
3. **[`nameof` improvements](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#extended-nameof-scope) (C#11):**
Go through the code base and improve places where the `nameof` keyword can be used.  One of the biggest improvements can be in attributes.
4. **Use Of `SearchValues` struct(C#12):**
    - This can give us some huge perf benefits.  Especially when it comes to rendering text.  Go through the code base and find all areas where this could help us out.
    - Go [here](https://www.youtube.com/watch?v=IzDMg916t98) for a video on details of the new type.
5. **Look for `.ToArray()` uses and find how to remove them to reduce allocations**
6. Look into this [blog post](https://www.code4it.dev/blog/top-6-string-performance-tips/) for more string perf opportunities
7. Look for opportunities for improvement by using the `SearchValues<T>` feature.
    - This requires dotnet 9
8. 

#### Research Results

1. Did not find any use cases for the `required` keyword
2. 

### Things to improve:
1. Improve the `KeyboardDataService.cs` file by doing suggested refactorings of the `Enum` type.

### Acceptance Criteria

```[tasklist]
- [ ] Research complete and issues created _(if needed)_.
- [ ] If any issues were created, they have been added to the _**Related Work**_ section below.
```

#### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
