### ISSUE TITLE
🚧Update to dotnet 8

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#815]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update projects to dotnet 8. This will require going to each project and updating the _**.csproj**_ file.  The repository variable will also need to be updated as well after release.  

Update the language version in all projects to C# 12.

> **Warning**
> Make sure to update the repo variable value to the correct version or builds and tests will not work correctly.

```[tasklist]
### Acceptance Criteria
- [x] All projects updated to dotnet 8
- [x] C# language set to version 12
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Issue Dependencies

- KinsonDigital/Infrastructure#185

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
