### ISSUE TITLE
🚧Update workflows to use preview infrastructure

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#816]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the workflows to use the current preview version _**v13.4.0-preview**_ of _**Infrastructure**_.  There have been many internal changes to **Infrastructure** so it was decided to put it through its paces in preview for testing before updating all of the projects to use the newest version.

Update all of the applicable workflows to use _**Infrastructure**_ version _**v13.4.0-preview**_.

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] Application workflows updated to use preview version of Infrastructure
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
