### ISSUE TITLE
🚧Create a control factory for creating control instances

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#83]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create a factory class to create controls of various types.  This will make it easier to create controls without needed to deal with manually creating dependencies to inject them via constructor injection.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Factory created for constructing controls
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Groomed.  Duplicate of #87
