### ISSUE TITLE
🚧Improve font system

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#84]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

## Description

Improve the font system

### **Issue 1 (Font Loading):**
Currently, fonts are only loaded in the _**Content**_ directory path.  We need a way to search, find, and load system fonts.  
This is going to be different per operating system.  Create a dir path resolver to search and find system fonts for _**Windows**_.  Once this is complete, this will provide a foundation for other operating system font loading.  The operating system must be detected, then the proper resolver implementation injected into the `FontLoader`.  The loader must be able to search and find system fonts and return a list of all the fonts of the different styles for each font style. 

**Example:**
If the requested font is _**TimesNewRoman**_, then all 3 different font files for Regular, Bold, Italic, or of the correct style combination should be returned.  Currently it is unknown how performant the loading and creating of fonts will be because the font loading process creates a texture atlas during runtime.  

Another thing to consider is that if we are going to load system fonts instead of from the content location, this means that loading fonts by file name is not an approach we should take.  When loading fonts, we should load fonts by a font family name with font settings.  This means that we need to look into the **_FreeType_** library and see if we can find out what the font family is as well as the style. This will be used to check each file to see if it matches the font family and style when resolving font paths with the resolvers.

### **Issue 2 (Combined Font Style Rendering):**
A font with a combined style is itself a different font file.  Each font with a set style always has its own file.  

**Example:**
If the user requests the font family of **Times New Roman** with a style set to bold AND italic, this would actually be a completely separate file then for the **Times New Roman** bold font family.

**Windows File Examples:**
NOTE: These are located in the path _**C:\Windows\Fonts\**_ directory
**Times New Roman (Bold) File Name** --> timesbd.ttf
**Times New Roman (Bold & Italic)** --> timesbi.ttf

### **Issue 3 (Fonts That Do Not Exist):**
Currently there is a different font file for each style or combination of styles.  This means that if a bold font file exists but an italic one does not exist, then italic cannot be loaded when the person switches to another font style during runtime.  This has to be handled gracefully.  Throw a **FontDoesNotExistException** if this occurs.

Need to setup regular, bold, italic, and bold italic _**Times New Roman**_ fonts as an embedded resource and then build a service to pull the fonts out for loading and use. This will be the default font just in case a font is not found, or a font error occurs. 

### **Issue 4 (Font Settings):**
Currently, there is a requirement to have a JSON file that contains various font settings such as style and size.  This concept and everything related need to be removed.  The reason for this is due to the change in how fonts will be loaded.  Since it is currently required to have a JSON file, that means loading _**system**_ fonts would also require a JSON file and it would have to exist in the content directory.  This does not align with the direction of changes we want to make.

Change the `ContentLoader` class and other references using it to take in font settings as parameters such as size, style and font family.  This will also require changes to the `ContentLoader.Load<T>(string)` method by adding generic constraints to all of the other `IContent` types _**EXCEPT**_ `IFont`.  Create an overload method to the `ContentLoader` class and `IContentLoader` interface that should be constrained to only the `IFont` type to make sure that the font load overload method does not have to deal with other content types.  This overload method will have the additional font setting parameters.

**Overloaded Load Font Method Signature:**
`Load<T>(string family, int size = 12, FontStyle style = FontStyle.Regular) where T : class, IFont`

### **Research**
- [x] See if **FreeType** has the ability to detect which font style a font file is
    - It does have the ability.  This can be pulled right from the `FT_Face_Rec` type.  Refer to the link below for more info
        - [Get Font Style](https://freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_facerec)

---

### **Change font loading services**
- [x] Move all font related types in the `Velaptor.Content` namespace to `Velaptor.Content.Font`
- [x] Create a new `WindowsFontPathResolver` implementation of the `IPathResolver` interface
    - This will be used to resolve the dir path to the windows system fonts
- [x] Refactor the `FontPathResolver` class name to be named `ContentFontPathResolver`
    - ⚠️NOTE⚠️ This will be used to resolve to the content path that lives in the same location as the executable
    - This service will be used in the new service to first check for fonts in the content directory before checking the system
    - This will get injected into the new service that has the name `FontPathResolver` which is the new name of the class above.  Which used to be `FontPathResolver`
- [x] Create a new service named `FontPathResolver` that will take in other resolvers to resolve font dir paths
    - ⚠️NOTE⚠️ This is the new service but is using the old service name that is now `ContentFontPathResolver` and the `WindowsFontPathResolver` and `ContentFontPathResolver` will get injected into this server.
    - [x] Inject the `IPlatform` into this service
    - [x] Inject and use the new `ContentFontPathResolver` for resolving the dir path to a font in the root content location
    - [x] Inject and use the new `WindowsFontPathResolver`
        - Resolves the dir path to windows system fonts if no fonts were found in the content path first
- [x] Refactor the `ContentLoaderFactory` class to inject the correct system font path resolver implementation based on the current system. 

---

### **Font Loading**
- [x] Setup the _**Times New Roman**_ fonts of regular, bold, italic, and bold italic as an embedded resource.
    - [x] Refactor `EmbeddedResourceLoaderService` `IEmbeddedResourceLoaderService` types
        - [x] Rename the `EmbeddedResourceLoaderService` class to `TextResourceLoaderService`
        - [x] Make the interface `IEmbeddedResourceLoaderService` a generic that determines the type of data returned by the `LoadResource()` method.
    - [x] Create new `IEmbeddedResourceLoaderService` implementation named `EmbeddedFontResourceService`
        - [x] This service will check to see if the resource exists and throw and exception if it does not.
        - [x] This service will return a `Stream` object that can be used to copy the embedded font file to the Font content directory
    - [x] Setup the `FontLoader` implementation to check and see if the default embedded fonts have been extracted, and if not, extract the default fonts embedded resources into the Content/Fonts directory.
    - [x] Update the `Label` class to request the **_TimesNewRoman-Regular_** font which is a default extracted embedded resource font.
- [x] Check to see if the _**FreeType**_ library has a way to check a font files family and style.  If so, add the proper implementations to the native interop system to take advantage of these checks so the resolvers can use them to find the proper font files.
- [x] When switching between one font style and another, throw a custom exception named `FontDoesNotExistException` if the font does not have that particular style
- [x] Add a property to the `Font` and `IFont` types named `AvailableStyles` that is a list of all of the styles available for the currently loaded font.
- [x] Gracefully unload one font and load another.
- [x] Load the different font required when the user changes the value of the `IFont.Style` property
- [x] Load the different font required when the user changes the value of the `IFont.Size` property
- [x] **Measure** and **improve** the performance of the font loading to understand if switching to different font styles is viable during runtime
- [x] Build caching system that the texture loading process can take advantage of
- [x] Build caching system that the font loading process can take advantage of

---

### **Direct Texture File Loading**

These are changes for the `TextureLoader` class for loading textures.  These will enable the ability to create texture atlas textures from font files, or directly from _**.png**_ files.  This also adds special syntax to the incoming value for bringing in extra data like the font size for creating font atlas textures.  This is required because each font size will be a different texture.

- [x] Process texture files differently depending on if the incoming name is a file path or not a file path
    - [x] Maintain the functionality of the value of `name` not being a file path.  This will signify that the texture needs to be loaded from the application's texture content directory and the file path will be figured out using the `texturePathResolver` injected into the `TextureLoader`
    - [x] If `name` is a full file path, then the resolver will not be used, and the image created using this path
    - [x] Check if the file exists and if not, throws an exception
        - [x] Add exception documentation to the load method for this exception
    - [x] Throw an exception if the file type is **NOT** a _**.png**_ or _**.ttf**_ file
        - [x] Add exception documentation to the load method for this exception
    - [x] If the value of `name` is a _**.ttf**_ true type font file, then it needs to be parsed to see if the font size is included withing the value of `name`.
        - Font file size syntax: C:\Windows\Fonts\times.ttf|size:22

---

### **Misc**
- [x]  Change the data type of the `IFont.Size` property and all required uses and referecenes from `int` to `uint`
    - 💣Breaking Change
- [x] Add new property to `IFont` and `Font` of the new enum type below called `FontSource` that shows if the font was loaded from the system vs the application content directory
    ```` cs
    /// <summary>
    /// Represents the source of where a font was loaded from.
    /// </summary>
    /// <remarks>
    ///     When loading fonts, the font that is attempting to be loaded will be
    ///     checked for its existence in the application's content directory first.
    ///     If the font does not exist there, then the font will be checked for
    ///     its existence in the system.  If the font does not exist in the application's
    ///     content directory or the system, then an exception will be thrown.
    /// </remarks>
    public enum FontSource
    {
        /// <summary>
        /// Loaded from the application's content directory.
        /// </summary>
        Content,

        /// <summary>
        /// Loaded from the system.
        /// </summary>
        System,
    }
    ````

- [x] `IFont.GetAvailableGlyphCharacters()` method
    - 💣 Breaking change
- [x] Unit tests added

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [x] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass
