### ISSUE TITLE
🚧Process all warnings

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#844]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Over time, the warnings throughout the code base have been building up.  Go through the entire code base and refactor the code to meet the coding requirements set by the project.

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] Code base refactored to meet coding standards
- [x] Remove all `[Serializable]` attributes with associate ctor from exception classes
- [x] Tests that use `Theory` attribute have been refactored to use `TheoryData<T>` instead
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
