### ISSUE TITLE
🚧Replace all UI controls with IMGUI

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#859]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Replace all of the UI controls in the **_VelaptorTesting_** project with IMGUI controls.

This will remove the internal dependency of the deprecated UI controls.  This way when it is time to remove all of the UI controls from the codebase/API, Velaptor itself will not depend on it anymore so we can move forward.

Integrate the stats ImGui control group/window into Velaptor.  This should be shown/hidden using the key combination _**Ctrl + Shift + Alt + ~**_.

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] VelaptorTesting application does not use any of the deprecated UI controls/types
- [x] The _**Text Box Scene**_ is removed
- [x] `Invoker` wrapper around `ImGui` methods created
- [x] Integrate the stats ImGui control group/window into Velaptor
- [x] `IOpenGlService` and `OpenGlService` files/types moved to a _**Services**_ folder
- [x] Write unit tests for `ImGuiFacade` class
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
