### ISSUE TITLE
🚧Refactor how sound is used

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#86]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Currently _**Velaptor**_ has its own `Sound` and `ISound` types.  These are really nothing but wrappers around the sound types from _**CASL**_.  

For testing purposes, we need to create a new internal factory class for creating new `CASL.ISound` instances instead of creating a new instance of the `CASL.Sound` concrete type.  This is preventing the ability to create unit tests for the `Velaptor.Sound` class as well as the `SoundFactory` class.

> **Note**
The goal is to hide any reference or implementation of `CASL` types.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Create a new internal factory class called `CASLSoundFactory`
- [ ] Velaptor `Sound` class removed
- [ ] Create unit tests for the `Velaptor.Sound` class.
- [ ] Create unit tests for the `SoundFactory` class.
- [ ] `SoundLoader` code coverage increased to 100%
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Groomed
