### ISSUE TITLE
🚧Create a control factory for creating controls

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#87]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create a control factory in the `Velaptor.UI` namespace.

This factory will be static and be used to easily create controls.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Add method to factory to create a button
- [ ] Add method to factory to create a label
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Reviewed

**Comment by CalvinWilkinson** [comment]
This has already been done.
Issue closed
