### ISSUE TITLE
🚧Refactor moq code to nsubstitute

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#871]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor all of the _**MOQ**_ related code to _**NSubstitute**_ code.

**Refactor the following files:**
- FontRendererTests.cs

> [!Note]
> The _**NSubstitute**_ nuget package has already been added to the unit test project.
> Some code has already been converted.

> [!Important]
> Do not update the _**NSubstitute**_ nuget package.  This will be managed by the _**Renovate**_ dependency management system.

> [!Tip]
> If there are any types that are complicated to read or type out after the conversion to the new code, you can _**POSSIBLY**_ use the new [any type alias](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-12#alias-any-type) feature introduced in _**C#12**_.

For more information about _**NSubstitute**_, go to the [NSubstitute Docs](https://nsubstitute.github.io/help.html)

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [ ] FontRendererTests.cs
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
