### ISSUE TITLE
🚧Create sound test scene for testing application

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#88]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create a sound test scene that can be used to test out functionality with sounds.

This will be a testing scene added to the testing application _**VelaptorTesting**_.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Create new sound testing scene
    - [ ] The scene must have buttons to click to help run the tests
    - [ ] Create button for playing sound
    - [ ] Create button for stopping sound
    - NOTE: The CASL library is a heavily testing library.  All we need to make sure of is that we can play and stop sounds.  This is to verify that sounds are at least loaded and can be used.  If this can be done, the Velaptor side of things are fine.
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [x] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Groomed.  Decided not to implement.
