### ISSUE TITLE
🚧Create logo icon to use for nuget.org

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#89]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Create a logo in **_.png_** and _**.ico**_ format for the purpose of nuget.org and other various places where needed.

The _**.png**_ version of the icon should go into the **./Documentation/Images/** directory in the project.

The **_.ico_** version of the icon should go into the root of the _**Velaptor**_ project which will be automatically picked up in the nuget package on package creation and will also be automatically used on nuget.org
- Do not add it to the root of the solution.  It gets added to the root of the project directory within the project.  Refer to **CASL** project to see how it is done.

### Acceptance Criteria

**This issue is finished when:**
- [x] PNG version of the icon created
- [x] ICO version of the icon created
- [x] ICO file gets included in nuget package

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

**Comment by kselena** [comment]
Groomed
