### ISSUE TITLE
🚧Fix rendering text bug

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#898]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

> [!Important]
> Before diving into this, there is some suspicion that issue #902 might be the cause of this problem. This issue has already been completed.  Check to see if the bug still exists before changing anything

When rending text using `IFont` and `IFontRenderer`, the text is shown at first for the first 1-3 frames and disappears.  The only way to get the text to show again is to resize the window manually using the mouse by grabbing the edges of the window.

> [!Note]
> Instead of manually resizing the window, you can get the text to show by also just maximizing the window.

**Refer to the video below:**
https://github.com/KinsonDigital/Velaptor/assets/85414302/9240d663-2b3b-4e9d-b0f5-37891afc7552

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Issue Dependencies

- #902 

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by mathew-odwyer** [comment]
~A little more information on this just in case - this also occurs with texture rendering as well.~  ~I think i was really tired when I wrote this. It only happens with text rendering.~

Never mind. It happens with text and texture rendering. I have a sneaking suspicion that this issue and #902 are somehow related but I haven't investigated enough to be sure.

**Comment by CalvinWilkinson** [comment]
It is possible.  I will make a note in one issue and add it as a dependency.

**Comment by CalvinWilkinson** [comment]
Closed without changes

**Reason:**
Issue #902 fixed this issue.
