### ISSUE TITLE
🚧 Add more info to nuget package for nuget.org to use

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#91]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Take advantage of the new nuget.org NuGet package feature that can [package readme files](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile) files on the package page.

Add more links to the NuGet package such as MIT for the license, nuget.org, and the main GitHub page for the project.
Update the author to the NuGet package to show **Kinson Digital Team & Contributors**.

![image](https://user-images.githubusercontent.com/85414302/187389598-8a989474-85ef-47f6-981d-28f5e4ce9a67.png)

### Acceptance Criteria

**This issue is finished when:**
- [ ] Setup NuGet package to use the projects README file
- [ ] More links added to the NuGet package
- [ ] Author updated to the NuGet package

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone

**Comment by kselena** [comment]
Groomed

**Comment by CalvinWilkinson** [comment]
Closed without implementation

**Reason:** Already completed by another issue
