### ISSUE TITLE
🚧Remove deprecated controls

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#933]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Remove the following deprecated controls:
1. ITextCursor
2. IControl
3. Button
4. ControlBase
5. Label
6. TextBox
7. TextCursor
8. TextSelection

> [!Note]
> Remove any other related code, references, and docs related to the old deprecated UI control API.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] IControl removed
- [x] Button removed
- [x] ControlBase Removed
- [x] Label Removed
- [x] TextBox Removed
- [x] ITextCursor removed
- [x] TextCusor Removed
- [x] ITextSelection Removed
- [x] TextSelection Removed
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
> [!Warning]
> Introduced the following https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes
> This is to remove the deprecated control UI.
> 1. Removed the `TextBox` control
> 2. Removed the `Button` control
> 3. Removed the `Label` control
> 4. Removed the `ControlBase` class
> 5. Removed the `IControl` interface
> 6. Removed the `ISizable` interface
