### ISSUE TITLE
🚧Add ability for button to have custom label

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#94]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Currently the `Button` class creates its own standard label to be able to render text on the face of the button and the label cannot be changed.  Change the button so the label settings can be changed and also a custom label pre-created and set

### Acceptance Criteria

**This issue is finished when:**
- [ ] If the label is null when calling the `Button.LoadContent()` method is invoked, then this means that a custom label was not sent in via the constructor.  In this case, just have the `Button` class create a default label.
- [ ] Add a constructor to the `Button` class to be able to take a label.
- [ ] Add `Label` readonly property to the button so the label can be changed.
- [ ] Add unit test for the Enabled property to verify that the label enabled property is matching
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

### Issue Dependencies

- #196

**Comment by kselena** [comment]
Groomed

**Comment by CalvinWilkinson** [comment]
Closed without any changes.

It was decided to be implemented in issue #211 instead due to the issues discovered with labels.
