### ISSUE TITLE
🚧Improve testing app

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#950]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

1. Replace the texture in the _**Non Animated Graphics Scene**_ in the _**VelaptorTesting**_ application with the _**Velapator**_ logo.
2. Swap the gradient stop and start controls in the _**Shape Scene**_
![image](https://github.com/KinsonDigital/Velaptor/assets/85414302/cff26b97-ea72-4ac6-b5e8-32edbe44999f)
3. Also, create a new demo video so it includes the new scene.
4. Swap out the audio with a metroid song in the audio scene

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] Texture swapped with logo
- [x] New video created for next release for each changes scene
- [x] Swap gradient stop and start labels for shape scene
- [x] Audio swapped with metroid song in audio scene
- [x] The _**Animated Texture Rendering**_ scene has been recreated
- [x] The _**Keyboard Input**_ scene has been recreated
- [x] The _**Layered Line Rendering**_ scene has been recreated
- [x] The _**Layered Rect Rendering**_ scene has been recreated
- [x] The _**Layered Text Rendering**_ scene has been recreated
- [x] The _**Layered Texture Rendering**_ scene has been recreated
- [x] The _**Line Rendering**_ scene has been recreated
- [x] The _**Mouse Input**_ scene has been recreated
- [x] The _**Non Animated Texture Rendering**_ scene has been recreated
- [x] The _**Shape Rendering**_ scene has been recreated
- [x] The _**Sound**_ scene has been recreated
- [x] The _**Text Rendering**_ scene has been recreated
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
