### ISSUE TITLE
🚧Add render overloads

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#957]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add new overloads to the `ITextureRenderer` interface.

**The following overloads should be added:**
1. `void Render(ITexture texture, int x, int y, float angle, float size, int layer = 0);`
2. `void Render(ITexture texture, Vector2 pos, float angle, float size, int layer = 0);`
3. `void Render(ITexture texture, int x, int y, float angle, float size, Color color, int layer = 0);`
4. `void Render(ITexture texture, Vector2 pos, float angle, float size, Color color, int layer = 0);`
5. `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, int frameNumber, int layer = 0);`
6. `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, Color color, int frameNumber, int layer = 0);`
7. `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, float angle, int frameNumber, int layer = 0);`
8. `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, float angle, float size, int frameNumber, int layer = 0);`
9. `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, float angle, Color color, int frameNumber, int layer = 0);`
10. `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, float angle, float size, Color color, int frameNumber, int layer = 0);`
11. `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, float angle, float size, Color color, RenderEffects effects, int frameNumber = 0, int layer = 0);`

**Reason:**
The reason for this is to be able to easily render a texture and use size without having to be forced to use the overload with the largest quantity of parameters when all you need is the size.

The Velaptor docs need to be updated by finding any code samples that use more complicated texture renderer methods than necessary.  

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] Issue created to update various docs to use simpler overloads in the code samples.
- [x] `void Render(ITexture texture, int x, int y, float angle, float size, int layer = 0);` as been added
- [x] `void Render(ITexture texture, Vector2 pos, float angle, float size, int layer = 0);` as been added
- [x] `void Render(ITexture texture, int x, int y, float angle, float size, Color color, int layer = 0);` as been added
- [x] `void Render(ITexture texture, Vector2 pos, float angle, float size, Color color, int layer = 0);` as been added
- [x] `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, int frameNumber, int layer = 0);` has been added
- [x] `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, Color color, int frameNumber, int layer = 0);` has been added
- [x] `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, float angle, int frameNumber, int layer = 0);` has been added
- [x] `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, float angle, float size, int frameNumber, int layer = 0);` has been added
- [x] `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, float angle, Color color, int frameNumber, int layer = 0);` has been added
- [x] `void Render(IAtlasData atlas, string subTextureName, Vector2 pos, float angle, float size, Color color, int frameNumber, int layer = 0);` has been added
- [x] 'void Render(IAtlasData atlas, string subTextureName, Vector2 pos, float angle, float size, Color color, RenderEffects effects, int frameNumber = 0, int layer = 0);' has been added
- [x] size and angle parameters swapped for the private `RenderBase` method
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
