### ISSUE TITLE
🚧 Add multi-line text, rotation, and scaling

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#96]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add the following features to text rendering

- [x] Add the ability to render multi-line text 
- [x] Add ability to rotate text
- [x] Add ability to scale text

### Acceptance Criteria

**This issue is finished when:**
- [x] Code documentation added if required
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [X] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [X] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

### Issue Dependencies
None

### Related Work

- #84
