### ISSUE TITLE
🚧Enhance font path resolution

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#964]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, if there is no **Content** directory in the same location as the running **_Velaptor_** application, then the Windows system fonts directory path is used.

This is not ideal because when it comes to fonts if you have not created a Font directory in the application's Content directory, one will be created automatically.

The **Fonts** directory will be created automatically and then _**Velaptor's**_ default fonts will be pulled from the embedded resources and copied into the folder for use.

Even if the requested font is not one of the default fonts, the folders should be automatically created and font resources dumped into the folder. 

The problem is that if a user creates a font loader and the **Content** directory does not exist, it will attempt to use the operating system's font directory to load fonts.  What should happen is if the **Content** and/or the **Content/Fonts** directory does not exist, it should be created automatically.

---

**Extra:**
The following classes need to have the `Path` type replaced with `IPath` from System`.IO.Abstractions`:
1. `ContentFontPathResolver`
2. `AtlasJSONDataPathResolver`
3. `TexturePathResolver`
4. `ContentPathResolver`
5. `AudioPathResolver`

> [!Note]
> Of course, all unit tests for the above classes will need to be updated

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
