### ISSUE TITLE
🚧Upgrade codebase to NET 6.0+ and newest verion of C# 10

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#97]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

- [x] Upgrade code base to NET 6.0
    - [x] Update the `NET_SDK_VERSION` and `ARTIFACT_FOLDER_NAME` environment variables in the `preview-release.yml` workflow file
    - [x] Update the `NET_SDK_VERSION` and `ARTIFACT_FOLDER_NAME` environment variables in the `qa-prod-releases.yml` workflow file
    - [x] Update the `NET_SDK_VERSION` environment variable name in the `build-status-check.yml` workflow file
    - [x] Update the `NET_SDK_VERSION` environment variable name in the `unit-testing-status-check.yml` workflow file
    - [x] Update the `NET_SDK_VERSION` environment variable name in the `preview-qa-release.yml` workflow file
- [x] Upgrade version of C# from C#9 to C#10

### Items Below Not Implemented.  Refer to comment to learn more.

- ⛔ ~~Refactor code to take advantage of new C# 10 features~~
    - ⛔ ~~[Global Using Directives](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#global-using-directives)~~
        - ⛔ ~~Also move all using to be above the namespace declaration~~
    - ⛔ ~~[File-Scoped Namespace Declaration](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#file-scoped-namespace-declaration)~~
    - ⛔ ~~[Constant Interpolated Strings](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#constant-interpolated-strings)~~
        - ~~This can possibly be used with the unit tests for constructing paths.  Also look in the non-unit test code base~~
- ⛔ ~~Any other refactors suggested by Rider~~

### Acceptance Criteria

**This issue is finished when:**
- [x] All unit tests pass

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [x] Unit tests have been written and/or adjusted for code additions or changes
- [x] All unit tests pass

**Comment by kselena** [comment]
Groomed

**Comment by CalvinWilkinson** [comment]
The items below were originally planned for this issue but due to the scope of changes, it was decided to break them into other various changes.

- #180
- #181 
- #182
