### ISSUE TITLE
🚧Update copyright in project file to 2022

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#98]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Update the copyright in the project file from `2020` to `2022`

### Acceptance Criteria

**This issue is finished when:**
- ~☑️ Code documentation added if required~
- ~☑️Unit tests added~
- ~☑️All unit tests pass~

### ToDo Items

- [x] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- ~☑️Unit tests have been written and/or adjusted for code additions or changes~
- [x] All unit tests pass
