### ISSUE TITLE
🚧Require fully file names for content loading

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#987]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, the file extension is not required when loading content, which is a limitation. This is because the only file extension (and file format type) for images are _**.png**_ files.  In the future, we are adding support for more file formats, which will address this limitation.  This means that Velaptor will have to deal with the scenario of 2 different file formats that have the same base name but different extensions.

Example: my-file.bmp and my-file.png

This means that _**Velaptor**_ will not know which file to choose from when an incoming file name without the extension is used. 

> [!Warning]
> This is a breaking change due to a behavior change!!

A lot of, if not all, of the path resolver classes, search for _**.png**_ files and find a match.  Adding this change means that searching for files is not required anymore.  Simply check if the file exists, and if it does not, throw an exception.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
