### ISSUE TITLE
🚧Add half width and height properties to UI control system

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#99]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Add 2 additional properties to the UI controls that are read only that represent the half width and height

- [ ] Add half width property
- [ ] Add half height property
- [ ] Make sure to add this as a read only property to the proper UI control interfaces and implement to ControlBase

NOTE: Eventually once the shape primitives feature has been implemented, the user will have the ability to manually set the width and height of the control due to the graphic not being a texture anymore.  

### Acceptance Criteria

**This issue is finished when:**
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Groomed

**Comment by sbundaz** [comment]
I'll do it.
